### PR TITLE
LPS-125700 Bridge CommerceAccountGroup service to AccountGroup service

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-125700](https://issues.liferay.com/browse/LPS-125700).

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:upgrade

**Comment by drewbrokke** [comment]
ci:test:accounts

**Comment by drewbrokke** [comment]
ci:test:commerce

**Comment by drewbrokke** [comment]
@patriciajeanperez I think these failures are related, but I'm not sure if we need to update the tests or if I need to adjust the code. Would you be willing to take a quick look?

**Comment by patriciajeanperez** [comment]
Hey @drewbrokke, 

1. [com.liferay.account.service.test.AccountEntryServiceWhenSearchingAccountEntriesTest](https://testray.liferay.com/reports/production/logs/2021-05/test-1-9/test-portal-acceptance-pullrequest(master)/4715/modules-integration-mysql57-jdk8/0/0/jenkins-console.txt.gz)

`     [exec] com.liferay.account.service.test.AccountEntryServiceWhenSearchingAccountEntriesTest > testShouldReturnNoAccountEntriesWithoutManageAccountsPermission STARTED
     [exec] 2021-05-03 20:49:30.126 INFO  [com.liferay.account.test-executor-thread][CompanyIndexFactory:57] liferay-61271
     [exec] 2021-05-03 20:49:30,133 com.liferay.account.test-executor-thread ERROR Attempted to append to non-started appender ropwobdf`

2. [com.liferay.account.service.test.AccountGroupLocalServiceTest > testSearchAccountGroups](https://testray.liferay.com/reports/production/logs/2021-05/test-1-9/test-portal-acceptance-pullrequest(master)/4715/modules-integration-mysql57-jdk8/0/0/jenkins-console.txt.gz)

`java.lang.AssertionError: expected:<[{mvccVersion=0, externalReferenceCode=, accountGroupId=81801, companyId=20103, userId=20131, userName=Test Test, createDate=Mon May 03 21:00:37 GMT 2021, modifiedDate=Mon May 03 21:00:37 GMT 2021, defaultAccountGroup=false, description=6UTJvld7, name=O2tp1X5v, type=static}, {mvccVersion=0, externalReferenceCode=, accountGroupId=81802, companyId=20103, userId=20131, userName=Test Test, createDate=Mon May 03 21:00:37 GMT 2021, modifiedDate=Mon May 03 21:00:37 GMT 2021, defaultAccountGroup=false, description=NQu0Y52h, name=RRkHL2be, type=static}]> but was:<[{mvccVersion=0, externalReferenceCode=, accountGroupId=81802, companyId=20103, userId=20131, userName=Test Test, createDate=Mon May 03 21:00:37 GMT 2021, modifiedDate=Mon May 03 21:00:37 GMT 2021, defaultAccountGroup=false, description=NQu0Y52h, name=RRkHL2be, type=static}, {mvccVersion=0, externalReferenceCode=, accountGroupId=81801, companyId=20103, userId=20131, userName=Test Test, createDate=Mon May 03 21:00:37 GMT 2021, modifiedDate=Mon May 03 21:00:37 GMT 2021, defaultAccountGroup=false, description=6UTJvld7, name=O2tp1X5v, type=static}]>`

3. Our search functional test for Account Groups also fail which could be related to these failures. Searching for `Delete AG` displays `Search AG` as well.

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:upgrade

**Comment by drewbrokke** [comment]
ci:test:accounts

**Comment by drewbrokke** [comment]
ci:test:commerce

**Comment by patriciajeanperez** [comment]
Upgrades and failures tests are unrelated. Test fix for the Account Groups test will be sent in a separate pull.

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
