### PR TITLE
LPS-201266 Update projectTemplateTokens

### PR DESCRIPTION
**Pull request by Seiphon**

### CODE REVIEW

**Comment by Seiphon** [comment]
ci:test:sf

**Comment by Seiphon** [comment]
ci:test:relevant

**Comment by Seiphon** [comment]
ci:test:project-templates

**Comment by Seiphon** [comment]
ci:test:project-templates

**Comment by Seiphon** [comment]
ci:test:project-templates

**Comment by Seiphon** [comment]
ci:test:project-templates

**Comment by Seiphon** [comment]
Hi @drewbrokke , the test are alread passed here https://github.com/Seiphon/liferay-portal/pull/147, but it always failed in this pr, it seems like a ci issue

**Comment by drewbrokke** [comment]
@Seiphon can you check the merge conflicts on this one and resend? There was a recent update to the project templates so this may have been solved already. Thanks!

**Comment by Seiphon** [comment]
Sure, will check it

**Comment by Seiphon** [comment]
This issue does have been resolved already

**Pull request closed without merging**
