### PR TITLE
LPS-110473 Reactivate backend tests

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-110473](https://issues.liferay.com/browse/LPS-110473).<br><br>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/86817

**Comment by patriciajeanperez** [comment]
ci:close

**Pull request closed without merging**
