### PR TITLE
LPS-101098 Create an API method to search for users assigned to an account

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by pei-jung** [comment]
Hi Drew,

Can you please double check my work and forward it to Brian if everything looks good? Thanks!

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Closing for now. We'll go with the classic index search approach for now by delegating the actual search call to UserLocalService.

**Pull request closed without merging**
