### PR TITLE
LPS-125700 Bridge CommerceAccountGroup service to AccountGroup service

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-125700](https://issues.liferay.com/browse/LPS-125700).<br/><br/>FOR CI ONLY

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
Roughly analyse for the test result.
The failed tests seems all related to the commits.
- [LocalFile.CPCommercePriceLists#AssertPriceListCanBeAssociatedWithAccountAndAccountGroup](https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=5,label_exp=!master/455891//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_CPCommercePriceLists_AssertPriceListCanBeAssociatedWithAccountAndAccountGroup_), the Account Groups under Control Panel > Users not accessible.
- 2 kind of failures in the upgrade tests.
- - got warning message when upgrade from 73 to master
```
     [java] 2021-03-02 22:58:19.306 WARN  [main][BaseDB:107] Table 'lportal.CommerceAccountGroup' doesn't exist: create index IX_E487EEC8 on CommerceAccountGroup (companyId, externalReferenceCode);
     [java] 2021-03-02 22:58:19.306 INFO  [main][BaseDB:99] create index IX_6A32E160 on CommerceAccountGroup (companyId, type_);
     [java] 2021-03-02 22:58:19.307 WARN  [main][BaseDB:107] Table 'lportal.CommerceAccountGroup' doesn't exist: create index IX_6A32E160 on CommerceAccountGroup (companyId, type_);
     [java] 2021-03-02 22:58:19.307 INFO  [main][LoggingTimer:44] Completed com.liferay.portal.upgrade.internal.index.updater.IndexUpdaterUtil#updateIndexes#Updating database indexes for com.liferay.commerce.account.service in 26 ms
```
- - got error message when upgrade from 72/71/70/62 to master
```
     [java] 2021-03-02 22:59:37.359 ERROR [main][VerifyProcessTrackerOSGiCommands:297] com.liferay.portal.verify.VerifyException: com.liferay.portal.kernel.exception.ModelListenerException: com.liferay.account.exception.DefaultAccountGroupException$MustNotUpdateDefaultAccountGroup: The default account group 42109 cannot be updated
     [java] com.liferay.portal.verify.VerifyException: com.liferay.portal.kernel.exception.ModelListenerException: com.liferay.account.exception.DefaultAccountGroupException$MustNotUpdateDefaultAccountGroup: The default account group 42109 cannot be updated
```
- The failed integration tests related

**Comment by drewbrokke** [comment]
ci:test:

**Comment by drewbrokke** [comment]
ci:close

**Comment by drewbrokke** [comment]
See https://github.com/drewbrokke/liferay-portal/pull/1326

**Pull request closed without merging**
