### PR TITLE
LPS-121897 Migrate v2 usages in portal-instances/portal-instances-web

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @drewbrokke,

Attached is an update for http://issues.liferay.com/browse/LPS-121897.

**Test Plan:**
1. Login to Liferay
2. Click on the **Applications Menu**
3. Click on **Control Panel** -> **System** -> **Virtual Instances**
4. Click the `+` to add a new instance
portal-instances

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
ci:test:sf

**Comment by jonmak08** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
The failed relevant not related, it's more like due to server issue, will retrigger the relevant.

**Comment by Sharryxue** [comment]
ci:test:relevant

**Review by julien — APPROVED** [review]

**Review by ambrinchaudhary — APPROVED** [review]

**Review by markocikos — APPROVED** [review]

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
