### PR TITLE
LPS-73594

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
See https://github.com/hhuijser/liferay-portal/pull/2916 for more info

**Comment by yuhai** [comment]
Hi @drewbrokke 

Hope you are well.

Since the issue came from EE customer. Could you please review this PR when you have time?

Regards,
Hai

**Comment by drewbrokke** [comment]
Hi @yuhai, yes I can look at it today.

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
