### PR TITLE
[TS] LPS-129958

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-129958

From @dacousalr:

> In order to work as any other selectors like Site Memberships selector, I propose to get all the selected elements instead of just the selected elements of the current page.

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
LGTM 👍

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
