### PR TITLE
LPS-114004 Replace layout classes with new clay taglibs in account-admin-web

### PR DESCRIPTION
**Pull request by eduardoallegrini**
Hey @drewbrokke , this is a simple code replacement that uses the new Clay Taglibs for old code like `<div class="sheet sheet-lg">` > `<clay:sheet>`.

Please, could you check if the module is still showing correctly or reply with instructions to see it?

I can't provide an official documentation right now, we have discussed the whole thing in this pr (https://github.com/liferay/clay/pull/3204) but I'm creating a quick list of the usages found so far in this google sheet (https://docs.google.com/spreadsheets/d/1mXjvokQRqSMuQtpghUAFLb2Igd21zgJvc8whUmV_-EU/edit?usp=sharing)

/cc @jbalsas @marcoscv-work

### CODE REVIEW

**Comment by eduardoallegrini** [comment]
ci:test:sf

**Comment by eduardoallegrini** [comment]
ci:test:stable

**Comment by eduardoallegrini** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
