### PR TITLE
[TS] LPS-102423 StaleObjectStateException upon login when value of LDAP attribute is changed

### PR DESCRIPTION
**Pull request by NorbertKocsis**
https://issues.liferay.com/browse/LPS-102423

Detailed explanation about why the change was neccesary can be found here:
https://issues.liferay.com/browse/PTR-1212?focusedCommentId=1960896&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1960896

Thanks!
Norbert

### CODE REVIEW

**Comment by NorbertKocsis** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Hey @NorbertKocsis, would it be a reasonable effort to add a regression test case for this fix?

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
@NorbertKocsis overall, the fix looks fine. However, after looking at this some more, I definitely think we need to add a regression integration test case. 

We need to make sure that the conditions under which this failure occurs are clear, as I suspect this is an issue that is present in other parts of the User service, and possibly other services. I think we should be able to reproduce the issue without needing to involve the LDAPUserImporter.

Can you please push a test case? Let me know what you think. Thanks!

**Pull request closed without merging**
