### PR TITLE
LPS-71186

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Hey Drew, do you mind reviewing this one?
More info from Hai here: https://github.com/hhuijser/liferay-portal/pull/2829

**Comment by drewbrokke** [comment]
@hhuijser sounds good. I'll look at it today.

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
Pull request sent to https://github.com/ealonso/liferay-portal/pull/833.  Thanks!

**Pull request closed without merging**
