### PR TITLE
LPS-104594 Allow search for users by email address domains

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:solr

**Comment by lipusz** [comment]
ci:test:search

**Comment by pei-jung** [comment]
Hi @xbrianlee,

I think only the `ElasticsearchIndexInformationTest.testGetFieldMappings` failure is related to my changes. Can you check if there's any other failures that I might have overlooked? Thanks!

/cc @patriciajeanperez

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
@xbrianlee I found the cause of the failure in `ElasticsearchIndexInformationTest`. It will be fixed in my next pull

**Comment by patriciajeanperez** [comment]
cc @joshchong

**Comment by joshchong** [comment]
hey @pei-jung @drewbrokke, for the next PR, please run the following search suites: 

```
ci:test:search
ci:test:search-solr
ci:test:search-es7
```

Thanks!

**Comment by joshchong** [comment]
Also, the UserIndexerIndexedFieldsTest modules-integration failures look related to this PR as well. Can you guys take a look?

**Comment by drewbrokke** [comment]
Test PR sent here: https://github.com/drewbrokke/liferay-portal/pull/922

**Pull request closed without merging**
