### PR TITLE
LPS-67830 Allow administrators to configure captcha using System Settings, allowing export and import of configurations

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @jorgeferrer

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:reopen

**Comment by pei-jung** [comment]
Hey Drew,

Please ignore the test failures for now. We'll need QA to update the tests later. Thanks!

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pei-jung** [comment]
Resent here https://github.com/drewbrokke/liferay-portal/pull/278

**Pull request closed without merging**
