### PR TITLE
LPS-78950 The isMale field in Users does not offer all the options that are often needed

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-78950](https://issues.liferay.com/browse/LPS-78950).

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test

**Comment by drewbrokke** [comment]
@jpince I don't think these test failures are related, can you confirm (or deny)?

**Comment by jpince** [comment]
ci:close @drewbrokke from modules-compile, looks related?
```
     [exec] > Task :apps:site-navigation:site-navigation-menu-item-node:classes
     [exec] /opt/dev/projects/github/liferay-portal/modules/util/portal-tools-sample-sql-builder/src/main/java/com/liferay/portal/tools/sample/sql/builder/DataFactory.java:1449: error: cannot find symbol
     [exec] 		contactModel.setMale(true);
     [exec] 		            ^
     [exec]   symbol:   method setMale(boolean)
     [exec]   location: variable contactModel of type ContactModel
     [exec] Note: /opt/dev/projects/github/liferay-portal/modules/util/portal-tools-sample-sql-builder/src/main/java/com/liferay/portal/tools/sample/sql/builder/DataFactory.java uses or overrides a deprecated API.
     [exec] Note: Recompile with -Xlint:deprecation for details.
     [exec] Note: /opt/dev/projects/github/liferay-portal/modules/util/portal-tools-sample-sql-builder/src/main/java/com/liferay/portal/tools/sample/sql/builder/DataFactory.java uses unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] 1 error
     [exec] > Task :apps:layout:layout-taglib:expandJSCompileDependencyComliferayfrontendtaglib400
     [exec] > Task :apps:layout:layout-taglib:expandJSCompileDependencies
     [exec] 
     [exec] > Task :util:portal-tools-sample-sql-builder:compileJava FAILED
```

**Comment by jpince** [comment]
@brianchiu @kyle-miho please look at failing nav tests, failing at `NavigationMenusAdmin.addMenu`. Probably unrelated to this pull?

**Comment by jpince** [comment]
@drewbrokke I'm concerned about the failures in these two integration tests, I don't see them in upstream, but have no idea if this pull would have caused them.

CompanyLocalServiceTest.testAddAndDeleteCompanyWithLayoutSetPrototype
`java.lang.AssertionError: {level=ERROR, loggerName=com.liferay.portlet.sites.util.SitesImpl, message=Merge fail count increased to 1 for layout set prototype 48422 and layout set 48421`
CompanyLocalServiceTest.testAddAndDeleteCompanyWithLayoutSetPrototypeLinkedUserGroup
`java.lang.AssertionError: {level=ERROR, loggerName=com.liferay.portlet.sites.util.SitesImpl, message=Merge fail count increased to 1 for layout set prototype 49099 and layout set 49098`
https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/234896/AXIS_VARIABLE=5,label_exp=!master/consoleFull

all other backend test failures look unrelated

**Comment by kyle-miho** [comment]
@jpince site-navigation-menu-admin-web had a compile error, which i am 90% sure is the reason why the poshi errors occured in both batches. I'll look into this.

BUILD FAILED in 2m 15s
     [exec] > Task :apps:site-navigation:site-navigation-admin-web:jarSourcesCommercial
     [exec] > Task :apps:site-navigation:site-navigation-admin-web:assemble

**Comment by kyle-miho** [comment]
Hey @jpince the Navigation Menu failures are also upstream, so I am pretty sure this pull does not affect navigation menus.

https://testray.liferay.com/home/-/testray/case_results/448284783?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D448278131%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc

**Comment by drewbrokke** [comment]
Pushed a new commit to this branch to fix the compile failure.  Re-running tests.

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test

**Comment by drewbrokke** [comment]
ci:stop

**Comment by drewbrokke** [comment]
ci:stop

**Comment by drewbrokke** [comment]
Resent as https://github.com/drewbrokke/liferay-portal/pull/697

**Comment by drewbrokke** [comment]
ci:stop

**Pull request closed without merging**
