### PR TITLE
LPS-111509 Rename default account roles and add descriptions

### PR DESCRIPTION
**Pull request by pei-jung**
Hey @drewbrokke,

I ended up just adding the English description for the roles since that's consistent with the pattern in other system roles.

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
PR sent to https://github.com/pei-jung/liferay-portal/pull/609

**Pull request closed without merging**
