### PR TITLE
LPS-63462 Do not translate value

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
@csierra do we need to change [ConfigurationModelToDDMFormValuesConverter](https://github.com/drewbrokke/liferay-portal/blob/master/modules/apps/foundation/configuration-admin/configuration-admin-web/src/main/java/com/liferay/configuration/admin/web/util/ConfigurationModelToDDMFormValuesConverter.java#L154) as well?

**Comment by csierra** [comment]
I have doubts with that one (https://github.com/drewbrokke/liferay-portal/blob/master/modules/apps/foundation/configuration-admin/configuration-admin-web/src/main/java/com/liferay/configuration/admin/web/util/ConfigurationModelToDDMFormValuesConverter.java#L154) because if the name of the method...

if you see it is causing problems and have tested it please modify it

**Comment by drewbrokke** [comment]
@ciserra Looks like we need to fix it there too.  From the looks of it, it
looks like not translating that value will remove the entire need to used
LocalizedValue there at all.  Is there any reason to continue using
LocalizedValue at all in either case?  
  

\--  

Drew Brokke

Software Engineer

Liferay, Inc.

  

On Mar 31 2016, at 2:25 pm, Carlos Sierra Andrés
&lt;notifications@github.com&gt; wrote:  

> I have doubts with that one (<https://github.com/drewbrokke/liferay-
portal/blob/master/modules/apps/foundation/configuration-admin/configuration-
admin-web/src/main/java/com/liferay/configuration/admin/web/util/Configuration
ModelToDDMFormValuesConverter.java#L154>) because if the name of the method...

>

> if you see it is causing problems and have tested it please modify it

>

> —  
You are receiving this because you commented.  
Reply to this email directly or [view it on
GitHub](https://github.com/drewbrokke/liferay-portal/pull/183#issuecomment-204
135592)

**Comment by csierra** [comment]
Hey @drewbrokke...

I was discussing exactly this with @JorgeFerrer yesterday. That why were we using LocalizedValue for this. I don't really know wether we can use a different type in DDM.

**Comment by JorgeFerrer** [comment]
Thanks for figuring this out guys

**Comment by drewbrokke** [comment]
@JorgeFerrer of course!

Pull request sent to JorgeFerrer#700

**Pull request closed without merging**
