### PR TITLE
LPS-187460 Upgrade JSON-java version to 20230618

### PR DESCRIPTION
**Pull request by Seiphon**

### CODE REVIEW

**Comment by Seiphon** [comment]
ci:test:sf

**Comment by Seiphon** [comment]
ci:test:relevant

**Comment by Seiphon** [comment]
ci:test:sf

**Comment by Seiphon** [comment]
ci:test:relevant

**Review by drewbrokke — APPROVED** [review]
LGTM 👍 Thanks @Seiphon!

**Comment by drewbrokke** [comment]
ci:forward:force

**Pull request closed without merging**
