### PR TITLE
Lps 54663 2

### PR DESCRIPTION
**Pull request by arbetts**
good luck

### CODE REVIEW

**Comment by arbetts** [comment]
ci:stop

**Comment by arbetts** [comment]
ci:cancel

**Comment by arbetts** [comment]
ci:abort

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by arbetts** [comment]
@drewbrokke 

one thing i forgot to mention upstairs was that everything was working as long as i didn't use ReindexStatusMessageSenderUtil in SearchEngineInitializer. I was able to send status updates from other classes, which is why i thought this might be an issue with OSGI

**Pull request closed without merging**
