### PR TITLE
LPS-65393

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
ci:reopen

@drewbrokke failure wasn't due to this pull

**Comment by mhan810** [comment]
ci:stop

**Comment by drewbrokke** [comment]
ci:retest

**Comment by drewbrokke** [comment]
ci:retest

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
Pull request sent to https://github.com/pei-jung/liferay-portal/pull/145 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
