### PR TITLE
[TS] LPS-77366 Create a Config Admin entry to enable stricter permission checking on roles when editing the Permissions for a resource like a document or web article

### PR DESCRIPTION
**Pull request by peterpetrekanics**
Dear Drew,

As discussed earlier, I am sending this PR to you - please review my code changes and let me know if there is anything I should change.
If you find the changes ok please forward the pull to the next approver.

Link to the LPS ticket:
[LPS-77366](https://issues.liferay.com/browse/LPS-77366)

Manual testing shows that the fix correctly resolves the issue.

Thank you,
Peter

### CODE REVIEW

**Comment by peterpetrekanics** [comment]
ci:test:sf

**Comment by peterpetrekanics** [comment]
There was a minor SF issue (an unneeded line break) that I have corrected in my repo and pushed it back again. Will re-run the ci:tests now

**Comment by peterpetrekanics** [comment]
ci:test:sf

**Comment by peterpetrekanics** [comment]
ci:test

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
@peterpetrekanics this looks good. I went ahead and made one small adjustment to the language keys.  See https://github.com/brianchandotcom/liferay-portal/pull/66634/commits/46f020e986ce237737e55f0c6809f126f1f65eb7.

PR sent to https://github.com/brianchandotcom/liferay-portal/pull/66634.

**Pull request closed without merging**
