### PR TITLE
[TS] LPS-103098

### PR DESCRIPTION
**Pull request by ChrisKian**
Resent from https://github.com/drewbrokke/liferay-portal/pull/918 with your comment [here](https://github.com/drewbrokke/liferay-portal/pull/918#issuecomment-553979448) addressed in the final commit.  Please let me know if you have any questions, thanks!

https://issues.liferay.com/browse/LPS-103098

CC @robertoDiaz

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
Hey @ChrisKian, I don't think we can throw an exception here. In testing it, portal does not even start up because this exception gets thrown when the default admin user is added during company creation. We can probably get away with doing this kind of check up in the portlet layer.

**Comment by ChrisKian** [comment]
Hey @drewbrokke, I've pushed new changes to the PR, which I have fully tested this time.  Let me know what you think, thanks!

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
PR sent to https://github.com/brianchandotcom/liferay-portal/pull/81167

**Pull request closed without merging**
