### PR TITLE
LPS-109571 Impersonate user fails to search its organization

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-109571](https://issues.liferay.com/browse/LPS-109571).<br><br>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
@patriciajeanperez is this a real failure?

**Comment by patriciajeanperez** [comment]
Hi @drewbrokke, a lot of builds were manually aborted because the load yesterday was too high. I will retrigger.

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
