### PR TITLE
LPS-116199 Users cannot be assigned to sites when users.search.with.index=false

### PR DESCRIPTION
**Pull request by pei-jung**
Hey Drew,

Can you review this to make sure I don't cause any regressions with my changes? Thanks\!

### CODE REVIEW

**Comment by Sharryxue** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
LGTM 👍

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
