### PR TITLE
LPS-155917 Use of library with known vulnerability: Angular ^5.0.0

### PR DESCRIPTION
**Pull request by simonjhy**

### CODE REVIEW

**Review by drewbrokke — APPROVED** [review]

**Comment by drewbrokke** [comment]
ci:forward

**Review by drewbrokke — CHANGES_REQUESTED** [review]
@simonjhy looks like there are some usages inside of `gradleTest` in `gradle-plugins-workspace` that we need to update as well. Can you update those as well? Thanks!

**Comment by simonjhy** [comment]
> @simonjhy looks like there are some usages inside of `gradleTest` in `gradle-plugins-workspace` that we need to update as well. Can you update those as well? Thanks!

OK

**Review by drewbrokke — APPROVED** [review]

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
@simonjhy looks like some related CI failures. Please look into those. Once we are green we can forward this one.

**Pull request closed without merging**
