### PR TITLE
LPS-124628 Don't publish account app

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-124628](https://issues.liferay.com/browse/LPS-124628).<br/><br/>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez @jpince @brianchandotcom

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
@jpince I've got a failure here but I doubt it's related. Can you confirm and send on if we're good?

**Comment by jpince** [comment]
ci:forward retesting, adding this file shouldn't change any portal logic nor cause test failures.

@patriciajeanperez can you please follow up on the error? Pretty sure I've seen this before `NoSuchUserException: No User exists with the key`

**Comment by patriciajeanperez** [comment]
Hi @jpince, yeah I just saw this error in my other pull this morning. I can manually forward if it fails again.

**Pull request closed without merging**
