### PR TITLE
[TS] LPS-92932

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-92932

From @istvansajtos:

> The issue is that certain local service methods call filterFindBy and filterCountBy (instead of calling findBy and countBy) thus filtering the results by permission. This goes against what our materials say.
> 
> The LPS contains a scenario that represents the issue with user groups. 

Let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
@ChrisKian @istvansajtos can you guys check direct usages of `UserGroupLocalService` and `UserGroupService` in addition to the Util?  I think there are a couple more we need to get.

**Pull request closed without merging**
