### PR TITLE
[TS] LPS-116382

### PR DESCRIPTION
**Pull request by jonathanmccann**
Hi @drewbrokke,

This change makes the validation logic mimic other areas of the portal (https://github.com/liferay/liferay-portal/blob/master/modules/apps/login/login-authentication-facebook-connect-web/src/main/java/com/liferay/login/authentication/facebook/connect/web/internal/struts/FacebookConnectStrutsAction.java#L456-L473) as well as the description for the property `company.security.strangers.with.mx`:

```
# Set this to true if strangers can create accounts with email addresses
# that match the company mail suffix. This property is not used unless
# "company.security.strangers" is also set to true.
```

Please let me know if you have any questions or concerns.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
# The Semantic version is updated in [LPS-92704](https://github.com/liferay/liferay-portal/commit/60f1817582649d02c74d1f88c05465d74ad0ada4) and 
[LPS-92704](https://github.com/liferay/liferay-portal/blob/master/portal-kernel/src/com/liferay/layout/admin/kernel/util/packageinfo)
# Error in [ProjectTemplatesRESTBuilderTest.testCompareRESTBuilderPluginVersions](https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1,label_exp=!master/279410//testReport/com.liferay.project.templates.rest.builder/ProjectTemplatesRESTBuilderTest/testCompareRESTBuilderPluginVersions) should be fixed in upstream according to the conversation in slack
# Issue in [PortalLogAssertorTest.testScanXMLLog](https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/279411/AXIS_VARIABLE=0,label_exp=!master/testReport/junit/com.liferay.portal.log.assertor/PortalLogAssertorTest/testScanXMLLog) is addressed in [LPS-105888](https://issues.liferay.com/browse/LPS-105888)

**Comment by Sharryxue** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Hey @jonathanmccann, can we add a test case for this as well?

**Comment by jonathanmccann** [comment]
@drewbrokke I force pushed a couple of tests. Let me know if there is anything else.

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
LGTM 👍

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
