### PR TITLE
LPS-74459

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:reopen

**Comment by arthurchan35** [comment]
ci:retest

**Comment by arthurchan35** [comment]
ci:retest

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
Pull request sent to https://github.com/brianchandotcom/liferay-portal/pull/51422. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
@arthurchan35 thanks for this fix.  In the future, remember to include the ticket number in the commit messages. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by arthurchan35** [comment]
@drewbrokke Terrible sorry, I somehow forgot to add the number. Will remember next time.

**Pull request closed without merging**
