### PR TITLE
UAD Summary Page

### PR DESCRIPTION
**Pull request by willnewbury**
updated with the changes you wanted

### CODE REVIEW

**Comment by willnewbury** [comment]
ci:test

**Comment by drewbrokke** [comment]
@willnewbury the PMD failure above comes from defining unused variables in the stub *ActionCommands.  Once you fix that you can just force push.

**Comment by drewbrokke** [comment]
ci:test

**Comment by willnewbury** [comment]
ci:reopen

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
PR sent to https://github.com/brianchandotcom/liferay-portal/pull/55459.

**Pull request closed without merging**
