### PR TITLE
POSHI-601 Reduce bundle size

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [POSHI-601](https://issues.liferay.com/browse/POSHI-601).<br/><br/>/cc @kenjiheigel

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
Looks good to me!

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
ci:forward:force

**Comment by drewbrokke** [comment]
ci:stop

**Comment by drewbrokke** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/138211

**Pull request closed without merging**
