### PR TITLE
LPS-113146 Too many sites can throw error with SQL Server.

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-113146](https://issues.liferay.com/browse/LPS-113146).<br><br>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez

### CODE REVIEW

**Comment by drewbrokke** [comment]
@hongvo2308 @holatuwol

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
@ChrisKian is it a reasonable amount of effort to add a test case for this too?

**Comment by ChrisKian** [comment]
Hey @drewbrokke,

That should be fine, I'll do so now off this branch

**Comment by drewbrokke** [comment]
Thanks @ChrisKian

**Comment by drewbrokke** [comment]
ci:stop

**Comment by drewbrokke** [comment]
Closing for now

**Comment by ChrisKian** [comment]
Resent here: https://github.com/drewbrokke/liferay-portal/pull/1053

**Pull request closed without merging**
