### PR TITLE
[TECHNICAL-SUPPORT] LPS-99455

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/76819

**Pull request closed without merging**
