### PR TITLE
[TECHNICAL-SUPPORT] LPS-86711

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @wanderlast

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
I added a test case and bumped the package version, then sent a test pull to myself: https://github.com/drewbrokke/liferay-portal/pull/659

**Comment by drewbrokke** [comment]
PR sent to https://github.com/brianchandotcom/liferay-portal/pull/64825 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
