### PR TITLE
LPS-122001 Add missing tags to the schema to make all endpoints visible in the explorer

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-122001](https://issues.liferay.com/browse/LPS-122001).

/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:forward

**Comment by patriciajeanperez** [comment]
ci:forward

**Comment by patriciajeanperez** [comment]
ci:forward

**Comment by patriciajeanperez** [comment]
ci:forward

**Comment by drewbrokke** [comment]
@patriciajeanperez is this failure a flaky test? Can we retest?

**Comment by patriciajeanperez** [comment]
ci:forward

**Comment by yichenroy** [comment]
ci:forward

**Comment by yichenroy** [comment]
Investigating the forwarding failure.

**Comment by yichenroy** [comment]
ci:forward

**Pull request closed without merging**
