### PR TITLE
LPS-82295 - Setup wizard new design

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by marcoscv-work** [comment]
image

**Comment by marcoscv-work** [comment]
ci:test

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/60173. [See changes here.](https://github.com/drewbrokke/liferay-portal/compare/3d9396b40ecb~1...3d9396b40ecb) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
