### PR TITLE
LPS-93442 Using uiRequired field for auto tagging

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Hi @drewbrokke,

Just so you don't forget about this :)

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
PR sent to https://github.com/4lejandrito/liferay-portal/pull/246

**Pull request closed without merging**
