### PR TITLE
LPS-78950 The isMale field in Users does not offer all the options that are often needed

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-78950](https://issues.liferay.com/browse/LPS-78950).

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test

**Comment by drewbrokke** [comment]
@jpince any red flags here?

**Comment by jpince** [comment]
@drewbrokke looks ok to me

**Comment by drewbrokke** [comment]
PR sent to https://github.com/brianchandotcom/liferay-portal/pull/66186

**Pull request closed without merging**
