### PR TITLE
[TS] LPS-130651

### PR DESCRIPTION
**Pull request by ChrisKian**
Ticket: https://issues.liferay.com/browse/LPS-130651

From @ericyanlr:

> This is a continuation of the Permission Filter changes from [LPS-130220](https://issues.liferay.com/browse/LPS-130220) (which has been partially reverted)
> 
> **Goal of Proposed Fix**
> The goal of this fix is to:
> - Resolve the slow loading of Users & Organizations page
> - While preserving the current expected behavior for Site Memberships / Accounts / Users & Orgs, such as:
>   - Users having the ability to see users that they created
>   - Site Administrators being able to see all users
>   - Account Managers being able to see all Account Entry users
> - And also avoid re-introducing regressions from our first attempt:
>   -  LPS-130626 User with add user permission not able to view the user he added 
>   -  LPS-130611 User with Account Manager role not able to view the account user 
>   -  LPS-130601 Comparison failure on UserLocalServiceTest.testSearchWithGroupId 
> 
> The approach I took is to expand the permission filtering criteria only when needed and when the requesting user has the proper permissions. And to have clearly defined conditions, which allows us to properly return the expected subset of users, instead of just returning all users.

### CODE REVIEW

**Comment by ChrisKian** [comment]
Passing SF test: https://github.com/ChrisKian/liferay-portal/pull/295#issuecomment-820837157
Passing relevant tests: https://github.com/ChrisKian/liferay-portal/pull/295#issuecomment-820886459

**Comment by Sharryxue** [comment]
ci:test:usm

**Comment by drewbrokke** [comment]
@Sharryxue are these USM suite failures unique?

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:reevaluate:1177401_7580

**Comment by drewbrokke** [comment]
ci:reevaluate:1177401_7580

**Comment by drewbrokke** [comment]
ci:test:usm

**Comment by Sharryxue** [comment]
No specific issue found in usm test suite.

**Comment by ericyanLr** [comment]
Hi @drewbrokke ,

One thing that came to mind is the fact that we'll eventually have to backport to 72x. However, DSLQuery is not available on 72x and so I guess an option could be to use DynamicQuery for the backport if we choose to use DSLQuery.

Another thing to point out is that DSLQuery on master supports caching, but not on 73x. And so, performance between 73x and master may be different.

Just wanted to share these thoughts in case it makes a difference in the approach we would like to take for this solution and for the backport to 72x.

**Comment by drewbrokke** [comment]
@ericyanLr re: backporting to 7.2.x: DynamicQuery is definitely an option, though IIRC they are never cached, so there's always the possibility of a performance hit with them. I guess the concern is the same as with 7.3.x DSLQueries not being cached.

Perhaps we could do manual testing using DynamicQuery to simulate the worst case scenario?

@preston-crary is it on the roadmap to backport DSLQuery caching to 7.3.x? Or to backport DSLQuery to 7.2.x at all?

**Comment by Preston-Crary** [comment]
@drewbrokke no not really. Backporting any of that would require customers to regenerate their services and update their build.

**Comment by Preston-Crary** [comment]
Another option is to search only using the database. Seems weird to need to do lots of queries in order to filter index search results. Could also consider adding more info to the search index to help with the search, but make sure not to add too much if you go that route. Caching performance is never the most important factor because sometimes cache is missed.  Focus on getting it faster when there's a worst case (cache miss) without sacrificing other cases too much.

**Comment by drewbrokke** [comment]
Closing based on my discussion with @ericyanLr and @joshuacords.

**Pull request closed without merging**
