### PR TITLE
[TS] LPS-92932

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-92932](https://issues.liferay.com/browse/LPS-92932)

Hi @drewbrokke ,

This is the continuation of https://github.com/drewbrokke/liferay-portal/pull/833. Sorry for the delayed update.

As per [your request](https://github.com/drewbrokke/liferay-portal/pull/833#issuecomment-499197180), I've double-checked the direct usages of the affected local service methods, but no change was necessary as accesses come from restricted portlets. (E.g. the affected `UserGroupLocalService` methods are accessed only from `UserGroupItemSelectorViewDisplayContext` which is used solely by _/modules/apps/user-groups-admin/user-groups-admin-item-selector-web_)

Thank your for reviewing,
Istvan

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
PR sent to https://github.com/istvansajtos/liferay-portal/pull/38

**Pull request closed without merging**
