### PR TITLE
LPS-199149 Remove manual env variable setting from workspace build.gradle files

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-199149](https://issues.liferay.com/browse/LPS-199149).

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:liferay-sample-workspace

**Comment by drewbrokke** [comment]
@gamerson

**Comment by drewbrokke** [comment]
ci:test:liferay-sample-workspace

**Comment by drewbrokke** [comment]
ci:test:liferay-sample-workspace

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
ci:help

**Comment by drewbrokke** [comment]
ci:test:liferay-sample-workspace

**Review by gamerson — APPROVED** [review]
LGTM!

**Comment by drewbrokke** [comment]
See https://github.com/liferay-devtools/liferay-portal/pull/23

**Pull request closed without merging**
