### PR TITLE
LPS-115019 Add a "view state" display context holder for search containers to the Clay Taglib

### PR DESCRIPTION
**Pull request by ngriffin7a**
/cc @jbalsas @brunobasto @david-truong @wincent

### CODE REVIEW

**Comment by ngriffin7a** [comment]
@drewbrokke If you would, please fix the SF problem if it happens again. I can't reproduce it locally.

Also, the top commit has a new file named viewstate-jsptaglibrary_1_0.xsd

Please ask Brian to publish it at http://docs.liferay.com/xml/ns/viewstate/viewstate-jsptaglibrary_1_0.xsd

The `gw validateTLD` task will FAIL unless that XSD is first published.

Also the file might need to appear in portal-web/docroot/dtd as well. I guess we'll find out when `ci:test` runs.

**Comment by david-truong** [comment]
@ngriffin7a you should send that file by itself and then send the rest of the pull afterwards

**Comment by ngriffin7a** [comment]
@drewbrokke Please incorporate Dave's suggestion by sending the file separately, after you've done your code review. Thanks.

**Comment by Sharryxue** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
Hello @ngriffin7a,
Thanks for sending the fix for the [TLD](https://github.com/drewbrokke/liferay-portal/pull/1136/commits/fe4055ad1ba7ef650ce0e052366e3eb02117f91c), however it fails for _liferay-clay.tld is not a valid XML document_, would you please double checking. Would you please check it again? Thanks.
And the same SF issue happens again.
/cc @drewbrokke

**Comment by ngriffin7a** [comment]
Hi @Sharryxue, after @drewbrokke asks Brian to publish the XSD to docs.liferay.com, then the TLD validation will succeed.

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Pull request closed without merging**
