### PR TITLE
LPS-104594 Allow search for users by email domains

### PR DESCRIPTION
**Pull request by pei-jung**
Hi Drew,

Can you review this and see if I miss anything? Thanks\!

/cc @alee8888

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:test:accounts

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Pull request closed without merging**
