### PR TITLE
LPS-85520 liferay-portal - TEST PROPERTIES DELETE ME

### PR DESCRIPTION
**Pull request by drewbrokke**

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test

**Comment by drewbrokke** [comment]
ci:stop

**Comment by drewbrokke** [comment]
ci:test

**Comment by jpince** [comment]
@drewbrokke the first one was a random failure.

2nd one is waiting in line due to CI maintenance :/ https://loop.liferay.com/home/-/loop/feed/13736993

**Comment by jpince** [comment]
ci:test

**Comment by jpince** [comment]
ci:test last one aborted for out of memory error

**Comment by jpince** [comment]
ci:test

**Comment by jpince** [comment]
@drewbrokke did you forward this to BChan? I couldn't find a PR...

**Comment by drewbrokke** [comment]
Hey @jpince, I needed to make an additional change, so this pull is not ready to be forwarded. Thanks for checking.

**Comment by drewbrokke** [comment]
@jpince I'm working on a number of changes to these components as part of https://issues.liferay.com/browse/LPS-85721.  I'm going to try to fix this issue as part of those changes (since they end up changing the SQL that breaks the tests anyways).  Go ahead and ignore for now, I'll re-enable them when I send those changes.

**Comment by jpince** [comment]
@drewbrokke thanks, ignored in
https://github.com/liferay/liferay-portal/commit/35b072f4ad788baf3fd0b05db6798c2d6e7245c2
.

**Comment by jpince** [comment]
@drewbrokke messed up the first ignore, please also revert
https://github.com/liferay/liferay-portal/commit/c89291e56e2fa4c08b10649081f2d5185383e6dd
when it's fixed. Sorry about this!

**Pull request closed without merging**
