### PR TITLE
[TS] LPS-116317

### PR DESCRIPTION
**Pull request by ChrisKian**
From @kevhlee:

https://issues.liferay.com/browse/LPS-116317

> The issue is that a redirect URL needs to be passed to the edit page's form. Failure to do this results in the back arrow and cancel buttons lacking back URLs and thus no longer functioning. To resolve this issue, I record the render URL used during the creation of the organizationScreenNavigationDisplayContext and pass it as input to the edit page's form.
> 
> This is a new pull request based on work mentioned here: https://github.com/drewbrokke/liferay-portal/pull/1120.
> 
> With regards,
> Kevin

CC @wanderlast

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by kevhlee** [comment]
Hi @drewbrokke,

It's been a while since this pull request has seen activity. Have you had the chance to look at this pull yet?

/cc @ChrisKian

**Comment by drewbrokke** [comment]
@kevhlee my apologies, I'll review it now

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by kevhlee** [comment]
@drewbrokke No worries!

**Comment by drewbrokke** [comment]
See https://github.com/ChrisKian/liferay-portal/pull/243

**Pull request closed without merging**
