### PR TITLE
LPS-118750 | master

### PR DESCRIPTION
**Pull request by jpince**
https://issues.liferay.com/browse/LPS-118750

@drewbrokke sending this on top of #1161 to test complete removal from the bundle

### CODE REVIEW

**Comment by jpince** [comment]
ci:test:sf

**Comment by jpince** [comment]
ci:test:relevant

**Comment by jpince** [comment]
ci:test:lpkg

**Comment by Sharryxue** [comment]
The SF issue probably indroduced by [commit](https://github.com/liferay/liferay-portal/commit/6ee562ecd852dd35fd64ab14328e540a8e2b24b6). Contact Hugo for help. Refer [slack](https://liferay.slack.com/archives/C1SJ64S9X/p1599095676003000).

**Comment by Sharryxue** [comment]
Can retriger the tests after [commit](https://github.com/brianchandotcom/liferay-portal/pull/93704) get merged.

**Comment by Sharryxue** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
ci:test:lpkg

**Comment by jpince** [comment]
Will rebase and resend once https://github.com/brianchandotcom/liferay-portal/pull/93762 is merged to upstream

**Pull request closed without merging**
