### PR TITLE
LPS-181508 In order to use supported JDK versions, we need to upgrade to Gradle 7 to use newer JDK

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-181508](https://issues.liferay.com/browse/LPS-181508).

@simonjhy @lawrence-lee

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
ci:forward

**Comment by simonjhy** [comment]
ci:test:project-templates

**Comment by drewbrokke** [comment]
ci:forward:force

**Comment by drewbrokke** [comment]
ci:help

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Comment by Kvale1733** [comment]
Hey guys looks like there were some CI issues yesterday. So ci:test:project-templates looks like it passed but it actually ran no tests if you check. So I'd rerun it. 

Mentioning this as I saw this PR due to https://liferay.atlassian.net/browse/LRQA-82347

**Comment by drewbrokke** [comment]
ci:close

**Pull request closed without merging**
