### PR TITLE
LPS-76354

### PR DESCRIPTION
**Pull request by jonathanmccann**
@drewbrokke Sending this through you since it seems more related to Users than Announcements, but let me know if you'd like to have this go elsewhere.

Based off of LPS-216, it seems the Website option should always be checked, however, we're depending on disabled checkboxes to achieve that. Instead, we should enforce this rule in the backend so that it never changes.

I would have liked to remove the entire Website option since I don't see the use for it but that requires a major version increase to portal-kernel which I'd like to avoid.

Let me know if you have any questions.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test

**Comment by drewbrokke** [comment]
Thanks for sending this my way, @jonathanmccann.  I'll try to take a look today.

**Comment by drewbrokke** [comment]
Hey @jonathanmccann what is the thought behind updating the AnnouncementsDelivery and User apis instead of just hard-coding true into the AnnouncementsDelivery in the ActionCommand?  Seems like that would accomplish the same thing.  Is it to prevent that value from being updated in the same way anywhere else?

I'm not too familiar with the purpose of AnnouncementsDelivery, but this has me wondering what that field is even for.

**Comment by drewbrokke** [comment]
An additional change we can consider making is to remove the checkbox from the UI, but I'm not sure if that violates some hidden product definition ;)

**Comment by jonathanmccann** [comment]
I wanted to make sure that the value wouldn't be updated to false via any other means.

The field itself is completely useless. It's never read anywhere and is only there for visual purposes. This is why I wanted to remove it completely, but that caused a major version increase in portal-kernel, like I mentioned. Also, like you, I'm not sure if someone somewhere enjoys having those checkboxes shown.

**Comment by drewbrokke** [comment]
@jonathanmccann that makes sense, thanks for clarifying.  In that case I'm fine with these changes.

**Comment by drewbrokke** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/53599. [See changes here.](https://github.com/drewbrokke/liferay-portal/compare/ea5ea0cc9974~24...ea5ea0cc9974) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
