### PR TITLE
LPS-127843 Flip IndexableAdvice to do sync indexing by default, and add a manual switch to allow override.

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-127843](https://issues.liferay.com/browse/LPS-127843).<br/><br/>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez

cc @shuyangzhou @arboliveira

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:forward

**Comment by Sharryxue** [comment]
The failure in [FacetedSearcherTest.testSearchByKeywordsIgnoresInactiveSites](https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=3,label_exp=!master/453705//testReport/com.liferay.portal.search.facet.faceted.searcher.test/FacetedSearcherTest/testSearchByKeywordsIgnoresInactiveSites) not related to the commit, issue addressed in [LPS-125464](https://issues.liferay.com/browse/LPS-125464).

**Comment by drewbrokke** [comment]
ci:forward

**Comment by patriciajeanperez** [comment]
hi @drewbrokke, the test failure is not related.

**Comment by patriciajeanperez** [comment]
Pushed to https://github.com/brianchandotcom/liferay-portal/pull/99177

**Comment by patriciajeanperez** [comment]
ci:close

**Pull request closed without merging**
