### PR TITLE
LPS-53392 Executing build-service-portal

### PR DESCRIPTION
**Pull request by achaparro**

### CODE REVIEW

**Comment by achaparro** [comment]
Hi @drewbrokke,

From @lipusz:

**Modified Services**:
- Core: `Contact, EmailAddress, MBMailingList, User` when upgrading to 7.0.3  
- Modules:
-- `contacts-service` when upgrading from 1.0.0 to 1.0.1  
-- `shopping-service` from 1.0.0 or 2.0.0 to 2.0.1

@Ithildir, we need to publish a new version of service-builder so that gradlew build-service from modules takes the new type in portal-model-hints.xml. Could you take care of it?

Thanks.

cc/ @lipusz @ugurcancetin

**Comment by Ithildir** [comment]
@achaparro: Brian will do it once he receives the pull. On CI, the local SB is already deployed and used, as you can see [here](https://github.com/liferay/liferay-portal/blob/master/build-test-batch.xml#L2258).

Do you notice any problems on CI or to test the code locally?

**Comment by achaparro** [comment]
I experienced an issue locally since even deploying the new service builder wasn't enough to the execution of build-service from modules realizes about this change:
https://github.com/drewbrokke/liferay-portal/pull/289/commits/b4b4dc8d09299e4df29f4c38ffeb6e30a38b8ea5#diff-175f153b9b1be4f463343378bbc62346R12

It worked in the portal but not in modules, but I think that it will be solved once we publish the new service builder version since the module will include the new portal-model-hints.xml:
https://github.com/liferay/liferay-portal/blob/master/modules/util/portal-tools-service-builder/bnd.bnd

Thanks.

**Comment by Ithildir** [comment]
Yeah, if you want to use the locally deployed SB on Gradle, you have to run it like this:
```bash
./gradlew buildService -Pcom.liferay.portal.tools.service.builder.ignore.local=false
```
Otherwise, you can simply run `ant build-services` from `portal-impl` after having done a `gradlew deploy` from `modules/util/portal-tools-service-builder`.

**Comment by achaparro** [comment]
Hi @Ithildir,

That's good to know I will test both options.

Thanks!

@drewbrokke, sorry for the noise ;-)

**Comment by drewbrokke** [comment]
@achaparro thanks for all this.  Lots of changes :)  I'm glad we decided to make email a hint-collection at the end.  Much less error-prone 👍  I'll double-check the changes.  I'd also like @jorgeferrer to glance at it (since there's so much).

**Comment by JorgeFerrer** [comment]
Hey Drew, is there anything in particular that you would like me to look at?

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
ci:reopen

**Comment by pei-jung** [comment]
Fixed test failure and resent here https://github.com/drewbrokke/liferay-portal/pull/292

**Pull request closed without merging**
