### PR TITLE
LPS-117852 companyId property not included when exporting factory configurations using Instance Settings portlet

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-117852](https://issues.liferay.com/browse/LPS-117852).<br><br>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez @stian-sigvartsen

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:forward

**Comment by Sharryxue** [comment]
Seems the failure not specific to this pull, will retrigger the relevant test.

**Comment by Sharryxue** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
ci:forward

**Pull request closed without merging**
