### PR TITLE
LPS-182369 Add snakyaml dependency to settings.gradle

### PR DESCRIPTION
**Pull request by Seiphon**

### CODE REVIEW

**Comment by Seiphon** [comment]
ci:test:sf

**Comment by Seiphon** [comment]
ci:test:relevant

**Comment by Seiphon** [comment]
ci:test:project-templates

**Comment by Seiphon** [comment]
ci:test:project-templates

**Comment by gamerson** [comment]
hey @Seiphon  have you tested this change in the `/workspaces/liferay-sample-workspace` along with the other `/workspaces/liferay-*-workspace` folders just as a test?

**Comment by gamerson** [comment]
Also we need to add unicode into the client-extension.yaml to verify this fix is correct.

**Comment by Seiphon** [comment]
in this case, the dependencies order is matterr, I will confirm that with @ling-alan-huang first, and I will resend the pr later

**Pull request closed without merging**
