### PR TITLE
LPS-111079 Personal accounts can only be associated with one account user

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-111079](https://issues.liferay.com/browse/LPS-111079).<br><br>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@pei-jung would you be willing to double-check this form me? Thanks!

**Comment by drewbrokke** [comment]
@pyoo47 is this something I can retest?

**Comment by pei-jung** [comment]
LGTM

**Comment by drewbrokke** [comment]
ci:forward

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
