### PR TITLE
LPS-125699 Bridge CommerceAccountGroupRel service to AccountGroupAccountEntryRel service

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-125699](https://issues.liferay.com/browse/LPS-125699).<br/><br/>for CI testing only. Do not forward.

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:commerce

**Comment by drewbrokke** [comment]
ci:test:users

**Comment by drewbrokke** [comment]
ci:test:accounts

**Comment by patriciajeanperez** [comment]
ci:test:bundle

**Comment by patriciajeanperez** [comment]
Hey @drewbrokke, looks like the failure for most tests are caused by this:

`com.liferay.portal.kernel.search.SearchException: java.lang.NullPointerException`
`Caused by: java.lang.NullPointerException
     [exec]     	at com.liferay.account.service.persistence.impl.AccountGroupRelPersistenceImpl.findByC_C(AccountGroupRelPersistenceImpl.java:729)`

Please see [Jenkins Console](https://testray.liferay.com/reports/production/logs/2021-06/test-1-25/test-portal-acceptance-pullrequest(master)/594/modules-integration-mysql57-jdk8/0/6/jenkins-console.txt.gz) for full log.

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:commerce

**Comment by drewbrokke** [comment]
ci:test:users

**Comment by drewbrokke** [comment]
ci:test:accounts

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:stop

**Comment by drewbrokke** [comment]
ci:stop

**Pull request closed without merging**
