### PR TITLE
LPS-86506 Fail search organization with tag

### PR DESCRIPTION
**Pull request by stsquared99**

### CODE REVIEW

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
@stsquared99 looks like some SF failures.  Just force push and ping me once they're fixed.

**Comment by stsquared99** [comment]
ci:test:sf

**Comment by stsquared99** [comment]
@drewbrokke good to go

**Comment by drewbrokke** [comment]
PR sent to https://github.com/brianchandotcom/liferay-portal/pull/64693 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
