### PR TITLE
[TS] LPS-109824

### PR DESCRIPTION
**Pull request by ChrisKian**
From @jesseyeh-liferay:

> ## Previous Pull Requests
> 
> https://github.com/wanderlast/liferay-portal/pull/46 > https://github.com/ChrisKian/liferay-portal/pull/190 > https://github.com/drewbrokke/liferay-portal/pull/992 > https://github.com/brianchandotcom/liferay-portal/pull/85985
> 
> ## Overview
> 
> This is an update to [LPS-109824](https://issues.liferay.com/browse/LPS-109824) which changes the rename to be more specific as described [here](https://github.com/brianchandotcom/liferay-portal/pull/85985#issuecomment-596826659).

CC @wanderlast

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
