### PR TITLE
LPS-92968 Use liferay-npm-scripts on users-admin-web

### PR DESCRIPTION
**Pull request by diegonvs**

### CODE REVIEW

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by jbalsas** [comment]
I think this is conflicting because it somehow got in... updating the LPS

**Comment by drewbrokke** [comment]
@jbalsas was it not intended for me to pass this pull on to Brian? I apologize if I was supposed to wait.

**Comment by jbalsas** [comment]
No, that's perfect, it's just that the PR is still open and the ticket was in a weird state, that's all :)

**Comment by drewbrokke** [comment]
Oh lol whoops, my bad

**Comment by drewbrokke** [comment]
thanks @jbalsas !

**Pull request closed without merging**
