### PR TITLE
Drewbrokke lps 73348 review 309

### PR DESCRIPTION
**Pull request by joshuacords**
https://issues.liferay.com/browse/LPS-73348
https://issues.liferay.com/browse/LPP-25804

Improved permission change and remove warnings.

### CODE REVIEW

**Comment by joshuacords** [comment]
https://github.com/drewbrokke/liferay-portal/pull/309#issuecomment-317124836 reveals some problem with the current implementation. I'm working on finding the source.

**Comment by joshuacords** [comment]
ci:reopen

**Comment by joshuacords** [comment]
ci:retest

**Comment by joshuacords** [comment]
Added 67a84b61737a6d8c53d44b29ea28a0c7d0d4a730 to handle empty arrays which where causing the problems mentioned here: https://github.com/drewbrokke/liferay-portal/pull/309#issuecomment-317124836

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
Looks like some SF errors.  Fix those up real quick and then resend.

**Comment by joshuacords** [comment]
Sorry about that. Resent here: https://github.com/drewbrokke/liferay-portal/pull/312

**Pull request closed without merging**
