### PR TITLE
LPS-195170 fix gradle eclipse plugin and other gradle plugin gradleTest error

### PR DESCRIPTION
**Pull request by simonjhy**

### CODE REVIEW

**Comment by simonjhy** [comment]
ci:test:gradle-plugins

**Comment by simonjhy** [comment]
ci:test:sf

**Comment by simonjhy** [comment]
ci:test:relevant

**Comment by simonjhy** [comment]
ci:test:gradle-plugins

**Comment by simonjhy** [comment]
ci:test:stable

**Comment by simonjhy** [comment]
ci:test:sf

**Comment by simonjhy** [comment]
ci:test:stable

**Comment by simonjhy** [comment]
ci:test:relevant

**Comment by simonjhy** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Comment by simonjhy** [comment]
ci:test:gradle-plugins

**Comment by simonjhy** [comment]
ci:test:gradle-plugins

**Comment by simonjhy** [comment]
ci:test:stable

**Comment by simonjhy** [comment]
ci:test:relevant

**Comment by simonjhy** [comment]
ci:test:gradle-plugins

**Comment by simonjhy** [comment]
ci:test:gradle-plugins

**Comment by simonjhy** [comment]
ci:test:stable

**Comment by simonjhy** [comment]
ci:test:relevant

**Comment by simonjhy** [comment]
ci:test:gradle-plugins

**Comment by simonjhy** [comment]
ci:test:stable

**Comment by simonjhy** [comment]
ci:test:relevant

**Comment by simonjhy** [comment]
ci:test:relevant

**Pull request closed without merging**
