### PR TITLE
LPS-78919 Add address text localizer for Japanese addresses

### PR DESCRIPTION
**Pull request by yasuflatland-lf**
Hi @drewbrokke, it took so long, here is PR for LPS-78919. I'm not sure if you are still in charge of this component, so please let me know if I need to send a PR to the other person.

### CODE REVIEW

**Comment by pei-jung** [comment]
Hi @yasuflatland-lf 

Based on the requirements on the ticket, you'll need to check the language that the address is inputted in and then format it accordingly.

Maybe something like this to check if address is written in English alphabets:
```
/**
* Check if address is written in Roman characters.
*/
public static boolean isRomanizedAddress(String address) {
	return address.matches("[\\w\\s\\-\\,\\.]+");
}
```

**Comment by yasuflatland-lf** [comment]
@jordirodo , it is not necessarily to be romaji, right?

**Comment by drewbrokke** [comment]
@yasuflatland-lf @jordirodo I believe @pei-jung is referring [to this comment here](https://issues.liferay.com/browse/LPS-78919?focusedCommentId=1268756&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1268756). If that is indeed a requirement, you'll need to update the formatter like Pei-Jung mentioned to handle both cases.

**Comment by pei-jung** [comment]
@drewbrokke looks like we don't need to worry about the input language for the Japan addresses, see [Yasu's comment here](https://issues.liferay.com/browse/LPS-78919?focusedCommentId=1887707&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1887707).  You can move forward with this pull. :)

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
PR sent to https://github.com/brianchandotcom/liferay-portal/pull/75543

**Pull request closed without merging**
