### PR TITLE
LPS-103098 Add tests

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Hey @drewbrokke 

I've added the requested tests (see https://github.com/drewbrokke/liferay-portal/pull/899#issuecomment-544711724)

cc/ @ChrisKian see https://github.com/drewbrokke/liferay-portal/pull/918/commits/5fe3e5492fe1ecfb0b7a0abd281ca0c3bc1de9da

Regards!!

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
Hey guys,

What is the status of this??

**Comment by drewbrokke** [comment]
Hey @robertoDiaz sorry I wasn't able to review yet. I can do it now. Thanks for checking.

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
@robertoDiaz @ChrisKian in looking at this again, I'm a little confused as to the scope of the issue the ticket is trying to address. The current changes are fine, but only address the issue in the Roles Admin portlet when updating assignees for a role.

However, the gif attached to the ticket demonstrates the issue as seen through Users Admin when editing a user, and this pull does not address that. The update call in Users Admin does not pass through the `unsetRoleUsers` (the one that now throws the exception), and so a success message is still seen.

If this was intended (to allow the success message to still show in Users Admin), then we need to update the ticket scope to limit the issue to just what is observed in Roles Admin.  Otherwise, we need to re-work the solution to include that Users Admin use case.

Let me know what you think. Thanks!

**Comment by ChrisKian** [comment]
Resent here: https://github.com/drewbrokke/liferay-portal/pull/920

**Comment by drewbrokke** [comment]
PR sent to https://github.com/brianchandotcom/liferay-portal/pull/81167

**Pull request closed without merging**
