### PR TITLE
[TS] LPS-102637 Api allows to add invalid sites

### PR DESCRIPTION
**Pull request by NorbertKocsis**
https://issues.liferay.com/browse/LPS-102637

### CODE REVIEW

**Comment by NorbertKocsis** [comment]
ci:test:relevant

**Comment by NorbertKocsis** [comment]
Hi,

Did you have a chance to take look at this?

Thanks!
Norbert

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
PR sent to https://github.com/brianchandotcom/liferay-portal/pull/79314

**Pull request closed without merging**
