### PR TITLE
LPS-58210 use the registries to generate the list of portlets

### PR DESCRIPTION
**Pull request by juliocamarero**
Hi @drewbrokke 

this is the new API to list the apps in the control panel or site administration. Let me know if you find any problem with this or if I should send this to someone else. thanks!

cc @JorgeFerrer

### CODE REVIEW

**Comment by juliocamarero** [comment]
Hi @drewbrokke

this is the new API to list the apps in the control panel or site administration. Let me know if you find any problem with this or if I should send this to someone else. thanks!

cc @JorgeFerrer

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
This looks good, @juliocamarero! Forwarding to @pei-jung for additional review.

**Comment by drewbrokke** [comment]
Pull request forwarded to https://github.com/pei-jung/liferay-portal/pull/66. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
