### PR TITLE
LPS-115444

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-115444

Fixes regression caused by [LPS-113325](https://issues.liferay.com/browse/LPS-113325)

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
See https://github.com/drewbrokke/liferay-portal/pull/1109

**Pull request closed without merging**
