### PR TITLE
LPS-58022 User not found if you search for it in Users and Organizations on the Browse tab

### PR DESCRIPTION
**Pull request by pei-jung**
Please see https://github.com/pei-jung/liferay-portal/pull/57.

Let me know if you have any questions. Thanks!

/cc @jorgeferrer

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:retest

**Comment by lipusz** [comment]
Hi @pei-jung 

>Organization admin shouldn't see the users panel on the 'Browse' tab since he/she doesn't have permission to access users outside of his/her organization.

Actually, it's not that simple imho. If a user has VIEW permission on a user, he/she should be able to see and this permission check is ensured either via the BaseSearchResultPermFilter (index-based search) or inline permission-check (DB-search), so I'm not convinced we really need that condition.

In addition, the browse tab is not intuitive: it's nowhere documented or stated that the search box works differently. I mean, the "All Orgs" and "All Users" tab are trivial (search in orgs/users only), but it's not obvious on the "Browse" tab for end-users.

**Comment by pei-jung** [comment]
Hi @lipusz,

If we remove those permission checks, the user (in this case, the organization admin) will see the users that do not belong to any organization. The actions on the users have already been filtered so that the org admin won't be able to do any action on them except viewing them. However, we'll have inconsistencies between the list of users shown in "Browse" and "All Users" tabs.

Here is the omniadmin's view of the "Browse" tab:
screen shot 2015-08-26 at 10 10 52 am

Here is the org admin's view of the "Browse" tab:
screen shot 2015-08-26 at 10 07 36 am

org admin's view of "All Users" tab:
screen shot 2015-08-26 at 10 07 39 am
Note: Users without organizations are not listed here.

If you search for any user without organization in the search box (for example, Nancy), no user is found. This is the same result in both "Browse" and "All Users" tab. As far as I can tell, I think the search box works consistently in all three tabs. But I get your point. I think there might be some issue with user search when getting the users for the "Browse" tab. I'll look into it.

**Comment by drewbrokke** [comment]
Closing for additional work <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
