### PR TITLE
LPS-199270 Upgrade to Spring 5.3.27

### PR DESCRIPTION
**Pull request by mbowerman**
Hello @drewbrokke,

Are you the correct person to send this to? If not, do you know who is?

This is upgrading the spring dependencies in the portletmvc4spring framework to address known vulnerabilities.

Ticket: [LPS-199270](https://liferay.atlassian.net/browse/LPS-199270)

### CODE REVIEW

**Comment by mbowerman** [comment]
Hello @drewbrokke,

Have you had a chance to look at this?

**Comment by gamerson** [comment]
ci:test:project-templates

**Comment by gamerson** [comment]
hey @mbowerman  could you have a look at those failing test cases and see if they are legit or if it is just the test asserts need to be updated?

**Comment by drewbrokke** [comment]
Hey @mbowerman sorry about the delay. You're in the right place. I'll give this a look this week.

**Comment by mbowerman** [comment]
Unfortunately I can't seem to access the Test Report. I'm not sure if that's because I don't have permissions, or because it's no longer there since I took too long to look at it. I'll try running the tests again.

**Comment by mbowerman** [comment]
ci:test:project-templates

**Comment by drewbrokke** [comment]
ci:test:project-templates

**Comment by drewbrokke** [comment]
Running a baseline here: https://github.com/drewbrokke/liferay-portal/pull/1543

**Comment by drewbrokke** [comment]
From what I can tell, the test [failures on this pull](https://github.com/drewbrokke/liferay-portal/pull/1531#issuecomment-1781893001) match the [failures on the baseline pull](https://github.com/drewbrokke/liferay-portal/pull/1543#issuecomment-1781969452). I think we should be ok to forward this one and fix the failures separately. @gamerson any objections?

**Review by gamerson — APPROVED** [review]
LGTM! Since Drew established the baseline failures are the same.

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
