### PR TITLE
LPS-108707 Revert LPS-107527

### PR DESCRIPTION
**Pull request by jesseyeh-liferay**

### CODE REVIEW

**Comment by jesseyeh-liferay** [comment]
ci:test:sf

**Comment by jesseyeh-liferay** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
PR sent to https://github.com/brianchandotcom/liferay-portal/pull/85120

**Pull request closed without merging**
