### PR TITLE
LPS-87539 When you delete a portal instance data is not deleted from DB

### PR DESCRIPTION
**Pull request by rgusztus**
Hi @drewbrokke 

I'm sending this PR regarding https://github.com/drewbrokke/liferay-portal/pull/801.
Can you please review it and let me know?

Thank you!

Best Regards,
Robert

### CODE REVIEW

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by rgusztus** [comment]
Hi @drewbrokke ,

Hope you're doing fine!
I was wondering if you had a chance to take a look to this PR?

Thanks,
Robert

**Comment by drewbrokke** [comment]
Hey @rgusztus, overall the fix looks fine, however I still am unable to delete the company due to the issue described in https://issues.liferay.com/browse/LPS-88699, so I can't verify.  Do you have any workarounds I can use?

**Comment by drewbrokke** [comment]
PR sent to https://github.com/brianchandotcom/liferay-portal/pull/73572

**Pull request closed without merging**
