### PR TITLE
[TS] LPS-102295

### PR DESCRIPTION
**Pull request by brianikim**
Hello,

https://issues.liferay.com/browse/LPS-102295

See ticket for issue description.

The reason the issue occurs is because prior to the fix introduced in LPS-103122 (https://issues.liferay.com/browse/LPS-103122), our liferay-release-tools invalidated the session if license was not deployed before basic configuration was completed.

Because LPS-103122 now has been merged, we are able to introduce this fix by adding SETUP_WIZARD_PASSWORD_UPDATED as an attribute that needs to be carried over from the invalidated session when [renewSession](https://github.com/liferay/liferay-portal/blob/42b9105d120818f69e4e9c675ec6fd1ee8eda9a6/portal-impl/src/com/liferay/portal/security/auth/session/AuthenticatedSessionManagerImpl.java#L365-L406) is called after basic configuration is completed.

As a result, when [isValidatePassword](https://github.com/liferay/liferay-portal/blob/42b9105d120818f69e4e9c675ec6fd1ee8eda9a6/portal-impl/src/com/liferay/portal/action/UpdatePasswordAction.java#L172-L187) is called for the initial password set-up, you will be able to re-use the default password as expected.

cc/ @holatuwol

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
PR sent to http://github.com/brianchandotcom/liferay-portal/pull/79591

**Pull request closed without merging**
