### PR TITLE
[TS] LPD-17832 2023.q4 branch is broken: 2023.q4.5 identifies as q4.1

### PR DESCRIPTION
**Pull request by IstvanD**
Hi @drewbrokke 

Could you please review this pull request?

**Please note that this issue is critical as it disables hotfixing for this version.**

Motivation
=======
**2023.q4.5** was released, however, it identifies as **q4.1**. The commit 97de7dbd14a6ec050c320513a2d357b73fee32f3 caused this problem.

Proposed Solution
========
Setting the correct latest release versions for `release.info.version.display.name[release-2023.q3-private]` and `release.info.version.display.name[release-2023.q4-private]`.

Steps to Verify
========
Please see the linked LPD for the reproduction steps.
https://liferay.atlassian.net/browse/LPD-17832

Thank you and best regards,
István

### CODE REVIEW

**Comment by drewbrokke** [comment]
@IstvanD looks fine to me, just need a sign-off from @CAustin582.

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by IstvanD** [comment]
Hello,

The test failures are not related to the solution.

Best regards,
István

**Comment by IstvanD** [comment]
Hi @drewbrokke,
I'm closing this pull request as Zsolt Balogh has sent is as well and it has been committed to master.
https://github.com/brianchandotcom/liferay-portal/pull/147316

**Pull request closed without merging**
