### PR TITLE
LPS-102069 Be yourself again from an impersonated user should render current user's profile

### PR DESCRIPTION
**Pull request by knchau**
https://issues.liferay.com/browse/LPS-102069

Issue: When user ends impersonation in "My Profile" or "My Dashboard", the user is not redirected to their profile or dashboard. The user is redirected to the impersonated one's. 

Solution: Since "My Profile" and "My Dashboard" contain one parameter in URL, the logic determines to replace the impersonated user's screen name with the current user's screen name. This new URL will be used as the link for the `Be Yourself Again`.

### CODE REVIEW

**Comment by knchau** [comment]
ci:test:sf

**Comment by knchau** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
@knchau thanks for sending this fix. If I'm being honest, doing a straight string replacement seems error-prone. If the impersonated user's screen name matches any other element of the URL, you'll end up with unexpected behaviors, or simply an error page for a resource not found. I think we should find a way to be more targeted/precise.

My guess is that this scenario will really only ever be a problem with the Profile and Dashboard pages. If that's the case, maybe we could try to get a whole new URL?  Perhaps check first to see if we're in the user's Profile or Dashboard page, then if so, get the real user's Profile/Dashboard page.

Thanks again! I'm gonna close this one for now. Feel free to resend or let me know if you have any question or need clarifications.

cc @SamZiemer

**Pull request closed without merging**
