### PR TITLE
LPS-89996 Allow users to quickly toggle the scope of reviewable data among instance, personal site, and regular sites

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @stsquared99

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
PR sent to https://issues.liferay.com/browse/LPS-89996

**Pull request closed without merging**
