### PR TITLE
[TS] LPS-106589

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-106589

From @NorbertKocsis:

> The solution is based on the one on https://issues.liferay.com/browse/LPS-53189

Upon asking him if there was a way to show an error message once the user was locked out:

> I don't really see a nice way to show the error, and after entering a wrong pasword several times I think the user will figure what happened. Otherwise if he tries to log back in the portal will tell he is locked out.

This is because once the user is logged out, they are redirected away from the Account Settings page, where we would display the error.

Please let me know if you have any questions, thanks!

CC @lipusz since this has security implications.

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by lipusz** [comment]
Please send it to @csierra too for review. Thanks!

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
PR sent to https://github.com/csierra/liferay-portal/pull/608

**Pull request closed without merging**
