### PR TITLE
LPS-122525 We can cause an infinite loop if call the getSegmentsEntryRoles with the NO Liberal permission checker (because the ES queries call again the role contributor).

### PR DESCRIPTION
**Pull request by cgoncas**
Hey @drewbrokke !!

We have found a bug with the SegmentsEntryRoleContributor, looks like we can generate an infinite loop if we keep the permission checker when the method getSegmentsEntryIds is called.

Could you take a look at this solution?

**How to reproduce the bug**

- Startup Liferay
- Navigate to Control Panel > Users and Organizations
       - Create user: test1
- Navigate to Control Panel > Users and Organizations > Organizations
       - Create organization: testOrg
- Navigate Back (<)
       - Assign user to testOrg: test1
- Navigate to Liferay Site > People > Memberships > Organizations
       - Assign testOrg to site
- Navigate to Liferay Site > People > Segments
       - Create User Segment: testSegment
- Add Organization Condition: organization equals testOrg
- Click Save
- Login as user: test1

Thanks!!

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Hi @cgoncas, this fix looks good! Would it be a reasonable amount of effort to also include a test case in `SegmentsEntryRoleContributorTest`?

**Comment by cgoncas** [comment]
Sure @drewbrokke !!

I have added a test in the commit https://github.com/drewbrokke/liferay-portal/pull/1203/commits/ebcb652dbb3b95339db2d87558b96a0061691e21.

Thanks!!!

**Comment by drewbrokke** [comment]
LGTM 👍

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
