### PR TITLE
LPS-202874 Client extension zip does not get deployed from a project with a version declared

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-202874](https://issues.liferay.com/browse/LPS-202874).

### CODE REVIEW

**Review by gamerson — APPROVED** [review]
LGTM!

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
ci:forward:force

**Pull request closed without merging**
