### PR TITLE
LPS-115779 Simplify AccountRoleLocalServiceImpl to use OrderFactoryUtil.addOrderByComparator

### PR DESCRIPTION
**Pull request by alee8888**
https://issues.liferay.com/browse/LPS-115779

@pei-jung @jonmak08

### CODE REVIEW

**Comment by alee8888** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
Hey @alee8888, looks like a rebase error on this one. Can you update and push/resend?

**Comment by alee8888** [comment]
@drewbrokke Rebased and forced push the changes. Retested the following and they passes:

AccountRoleLocalServiceTest.testSearchAccountRoles
AccountRoleLocalServiceTest.testSearchAccountRolesWithPagination

**Comment by alee8888** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
Thanks @alee8888! LGTM 👍

**Pull request closed without merging**
