### PR TITLE
LPS-111078 As an account manager, I want to specify whether an account type is Business or Personal

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-111078](https://issues.liferay.com/browse/LPS-111078).<br><br>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
@pei-jung would you be willing to look this one over for me? Please let me know if I should change anything or if I missed something. Thanks!

**Comment by pei-jung** [comment]
LGTM 👍

**Comment by drewbrokke** [comment]
ci:stop

**Comment by drewbrokke** [comment]
ci:stop

**Comment by drewbrokke** [comment]
Thanks @pei-jung !

**Comment by drewbrokke** [comment]
ci:stop

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
ci:stop

**Comment by drewbrokke** [comment]
See https://github.com/drewbrokke/liferay-portal/pull/1087

**Pull request closed without merging**
