### PR TITLE
[TS] LPS-94026

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-94026

CC @NorbertKocsis

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
@ChrisKian do you need me to keep this pull around, or is the related issue pretty much settled?

**Comment by ChrisKian** [comment]
I think we can close this one out.  Thanks @drewbrokke

**Pull request closed without merging**
