### PR TITLE
[Testing porpouses- DO NOT MERGE] LPS-104916 New log category

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
@robertoDiaz is this pull still something I should keep open? Just wanna make sure before I start closing things.

**Comment by robertoDiaz** [comment]
Closing.
Best regards!!

**Pull request closed without merging**
