### PR TITLE
LPS-81837

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-81837

The difference between how we store org logos is between 62x and 7010, in which we add the "logoId" column to the Organization_ table.  So, 62x and lower, we are actually storing the logoId in the LayoutSet table, under both the public and private pages (it's a different logoId for each, but it points to the same image).  And in 7010 and up, we store it in the Organization_ table under the "logoId" column.

I chose to only include this fix as a 7.0 upgrade process because once the DB has been upgraded to 7000 and up, there is no way to know for sure if the user intended to set a logo for their org or for the layoutSet of their org.  This is because post 7000, the logoId field in the layoutSet table (which was previously used for the org's logo), is now used for the public/private layoutSet's logo.  In the off chance a user wants their layoutSets to have logos but not their org, we would mess that up.

The fix itself is pretty straight-forward.  We grab the logoId and groupId from the layoutSet table whenever the logoId is present and we are dealing with a public layoutSet (to avoid duplication).  Next, we match that groupId to the classPK (or organizationId) from the Group_ table, and lastly we take the classPK match it to the Organization_ table, and insert the logoId.  After that, the logo is successfully found.

Please let me know if you have any questions.

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
Test failures look unrelated

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
PR sent to https://github.com/brianchandotcom/liferay-portal/pull/65609

**Pull request closed without merging**
