### PR TITLE
LPS-121991 Upgrade portal Address with new fields

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @alee8888

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
Hello @pei-jung,
Most of the tests failed for a Startup error: Unresolved Requirement(s), would you please double cheking the version issue?

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
Hello @pei-jung,
For the _service-builder-jdk8_ failure not sure if it need additional commits, [full log](https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/202459//consoleText).
The failed functional upgrade tests seems related to the changes here, refer the partial error message, [full log](https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/450163/AXIS_VARIABLE=0,label_exp=!master/consoleFull)
``` 
LIFERAY_ERROR: Key column 'externalReferenceCode' doesn't exist in table: create index IX_CBAD282F on Address (companyId, externalReferenceCode);
LIFERAY_ERROR: Key column 'groupId' doesn't exist in table: create unique index IX_15411410 on Address (uuid_, groupId);
LIFERAY_ERROR: Unknown column 'addressimp0_.externalReferenceCode' in 'field list'
LIFERAY_ERROR: Unknown column 'addressimp0_.externalReferenceCode' in 'field list'
LIFERAY_ERROR: Unknown column 'addressimp0_.externalReferenceCode' in 'field list'
```

**Comment by pei-jung** [comment]
See https://github.com/drewbrokke/liferay-portal/pull/1196.

**Pull request closed without merging**
