### PR TITLE
LPS-111626 Add POST endpoint for creating new users

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-111626](https://issues.liferay.com/browse/LPS-111626).<br><br>@brianchandotcom this pull adds the changes you requested [here](https://github.com/brianchandotcom/liferay-portal/pull/88364#issuecomment-624246915).<br><br>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
@pyoo47 @patriciajeanperez is this failure seen elsewhere? My pull doesn't kernel.

**Comment by pyoo47** [comment]
@drewbrokke I've been seeing this failure on other pull requests today. I don't think this is an issue with your pull request.

**Comment by drewbrokke** [comment]
Thanks @pyoo47. Is this the kind of failure where I can just re-run, or do I need to wait for the fix?

**Comment by pyoo47** [comment]
You'll have to wait for the fix. Unfortunately, I'm not sure of the status of such a fix and/or who's working on it. I'll throw a question into #d-quality-assurance and see if anyone there knows..

**Comment by drewbrokke** [comment]
@pyoo47 thanks for the update.

**Comment by pyoo47** [comment]
@drewbrokke Peter Shin told me how to fix it.. so I added a commit to a pull request that I'm trying to forward.. Hopefully, this will work and get merged.
https://github.com/pyoo47/liferay-portal/pull/1304/commits/d73ff1c358a4e3f89ea1cd399c26c553cc757f57

**Comment by jpince** [comment]
@drewbrokke thanks for escalating this. Fix is here, test should pass if you rebase your branch on Brian Chan's origin https://github.com/brianchandotcom/liferay-portal/commit/12cbd0f9b7e070e36d41928f8a97b4ac518bf9bc

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
