### PR TITLE
LPS-112876 Duplicated entries under Instance Settings > LDAP

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-112876](https://issues.liferay.com/browse/LPS-112876).<br><br>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
@pyoo47 @patriciajeanperez does this failure look related?

**Comment by pyoo47** [comment]
@drewbrokke I think this has been an ongoing issue in upstream? @patriciajeanperez may know more..
https://liferay.slack.com/archives/C010C2JKLTU/p1588030783000100

**Comment by patriciajeanperez** [comment]
@drewbrokke yea, Core team is aware and is working on a fix. This pull looks good.

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
