### PR TITLE
LPS-70824 Control Panel elements are not responsive to role permission definition toggles

### PR DESCRIPTION
**Pull request by pei-jung**
Hey @jorgeferrer,

This is an update for https://issues.liferay.com/browse/LPS-70824. We want to get your opinion on this fix.

The fix for the problem consists of 2 parts:

**1. `Access in My Account` permission has no effect for My Account portlets.**

After discussing with Drew, we decided to remove the logic that implicitly grants permission to  display the My Account portlets in the Control Panel and include the `Access in My Account` permission for the User role by default.

**2. Permissions, such as `Configuration`, `Permissions`, `Preferences`, and `View`, do not apply to Control Panel portlets.**

Currently according to the design of the permission framework, all portlets have the following permissions assigned to them by default: `Access in Control Panel/Add to Page`, `Configuration`, `Permissions`, `Preferences`, and `View`, and they are hard-coded in [ResourceActions](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/security/permission/ResourceActionsImpl.java#L764-L786). So regardless of what is specified in the resource-actions/default.xml, every portlet always have these permissions. However, for admin portlets, only the `Access in Control Panel` permission seems applicable. The other ones dont seem to have any effect.

Places where the other permissions should have been applied but is excluded for control panel portlets:
Showing permissions configuration icon [PermissionsPortletConfigurationIcon](https://github.com/liferay/liferay-portal/blob/master/modules/apps/web-experience/portlet-configuration/portlet-configuration-web/src/main/java/com/liferay/portlet/configuration/web/internal/portlet/configuration/icon/PermissionsPortletConfigurationIcon.java#L158-L160)
Showing preferences and configuration icons with [PortletDisplay](https://github.com/liferay/liferay-portal/blob/master/portal-web/docroot/html/portal/render_portlet.jsp#L826-L830).

If it's true that only the `Access in Control Panel` permission is applicable, a proper fix for this will be to not include the other actions but only `Access in Control Panel` for the control panel portlets. However, when I did that, I got a couple `NoSuchResourceAction` exceptions on startup. Apparently, those permission are also being used in other places than what I mentioned above. Upgrading the database is also another challenge. It's not just as simple as removing entries from the ResourceActions and ResourcePermissions table, but we also need to update the `bitwiseValue` since it's determined by the number of actions, not the type of action. Changes like this should be done in a story not a bug fix. So we decided to just hide the permission from the UI for now and implement the proper fix in a separate ticket.

### CODE REVIEW

**Comment by pei-jung** [comment]
@drewbrokke fyi, I updated the pr to include the change for BaseControlPanelEntry.

**Comment by JorgeFerrer** [comment]
Hey @pei-jung,

Thanks for checking with me. Please see my answers below:

> 1. Access in My Account permission has no effect for My Account portlets.
> 
> After discussing with Drew, we decided to remove the logic that implicitly grants permission to display the My Account portlets in the Control Panel and include the Access in My Account permission for the User role by default.

I've thought about this in the past, but I didn't have the courage to do the change because I wasn't sure of the consequences. I think it's the right move, but make sure you think through the possible scenarios and test for each of them.

> 2. Permissions, such as Configuration, Permissions, Preferences, and View, do not apply to Control Panel portlets.
> [..]
> Currently according to the design of the permission framework, all portlets have the following permissions assigned to them by default: Access in Control Panel/Add to Page, Configuration, Permissions, Preferences, and View, and they are hard-coded in ResourceActions. So regardless of what is specified in the resource-actions/default.xml, every portlet always have these permissions. However, for admin portlets, only the Access in Control Panel permission seems applicable. The other ones dont seem to have any effect.

Agreed
 
> [..]
> If it's true that only the Access in Control Panel permission is applicable, a proper fix for this will be to not include the other actions but only Access in Control Panel for the control panel portlets. 

Agreed. This is something I've had on the back of my mind for a while as well and I agree is the right move.

Related to this, I think we should consider dropping "Access in Control Panel" completely and use "View" instead. I decided to create it originally because we had portlets that were both in the Control Panel/Site Admin and in a site and wanted to make sure the portlet could be made available in one place and not the other. But that situation has shown to be very unusual (and probably not one that should be solved with permissions). 

Keeping "View" would probably simplify things since it's a pretty special permission.

> However, when I did that, I got a couple NoSuchResourceAction exceptions on startup. Apparently, those permission are also being used in other places than what I mentioned above. Upgrading the database is also another challenge. It's not just as simple as removing entries from the ResourceActions and ResourcePermissions table, but we also need to update the bitwiseValue since it's determined by the number of actions, not the type of action. Changes like this should be done in a story not a bug fix. So we decided to just hide the permission from the UI for now and implement the proper fix in a separate ticket.

Can you try with removing all permissions except for VIEW?
We could try the hidden UI approach, but that's bitten us back in the past, when the permission is somehow given but there is no way to see it.

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pei-jung** [comment]
Hey @JorgeFerrer 

I agree that hiding the UI is not the best approach. It hides the problem and can possibly create more problems later on. I'll give another try in removing the unnecessary permissions.

**Comment by drewbrokke** [comment]
@JorgeFerrer

I believe that to fully resolve this issue, we need to break it up into 3 steps:

1. Link up the appropriate permission checkbox (ACCESS_IN_CONTROL_PANEL) so that it actually works.  This is the bare minimum to resolve the issue on the ticket.  For the time being, we will leave the other permission checkboxes in the UI.  It is not ideal, but it does avoid unforeseen regressions.
2. Remove the unnecessary resource permissions for the Control Panel Portlets (e.g. PERMISSIONS, CONFIGURATION, PREFERENCES). This way the superfluous checkboxes will disappear naturally, rather than being artificially hidden.
3. Replace ACCESS_IN_CONTROL_PANEL with VIEW

If you're okay with this plan, I say we go ahead with step 1 in order to at least provide a workable fix for the issue on the ticket.  Thoughts?

**Comment by JorgeFerrer** [comment]
Hey @drewbrokke,

That sounds like a good plan to me. 

Regarding #1 I keep banging my head against the wall to try to remember why we decided to "hardcode" the permission to access the portlets in My Account for all users, but I can't remember any good reason. What we should of course make sure is that we assign that permission by default to the User role. We should specially consider what happens for existing installations.

Regarding #2, thinking about it more, I have some doubts about how to do it because in theory a portlet in control panel could have those elements. There are already several which have a configuration so I wouldn't always remove it. All have permissions, although it's probably confusing to show it there too (I'm ok with always hiding that one). Regarding Preferences, it might be quite unusual to have it but I wouldn't tie it to Control Panel. Instead I think that this option should be disabled (even if shown) for any portlet that doesn't actually have Preferences that each user can use to customize the portlet to his/her needs.

Makes sense?

**Comment by drewbrokke** [comment]
@JorgeFerrer 

> Regarding #1 I keep banging my head against the wall to try to remember why we decided to "hardcode" the permission to access the portlets in My Account for all users, but I can't remember any good reason. What we should of course make sure is that we assign that permission by default to the User role. We should specially consider what happens for existing installations.

The key for this change is that as each panel app is registered, the appropriate permissions are assigned to the User role. See d41008656bdc2ce9cdc53e50f1b9982911d02f6d.

As long as an existing installation gives each PanelApp a chance to re-register with the OSGi container, the permissions should assign properly.

> Regarding #2, thinking about it more, I have some doubts about how to do it because in theory a portlet in control panel could have those elements. There are already several which have a configuration so I wouldn't always remove it. All have permissions, although it's probably confusing to show it there too (I'm ok with always hiding that one). Regarding Preferences, it might be quite unusual to have it but I wouldn't tie it to Control Panel. Instead I think that this option should be disabled (even if shown) for any portlet that doesn't actually have Preferences that each user can use to customize the portlet to his/her needs.

Okay so it looks like we have 3 possible approaches for the three different actions in question:

1. CONFIGURATION - sometimes show, sometimes hide, or just always show?  I think I'm the least clear on this one.
2. PERMISSIONS - always hide since we don't assign individual permissions for Control Panel portlets.
3. PREFERENCES - somehow check to see if a portlet has preferences.  If so, enable the checkbox.  Otherwise, disable it.  You're suggesting we leave it there so that a user could still take advantage of this action if they wanted to?

**Comment by JorgeFerrer** [comment]
> The key for this change is that as each panel app is registered, the appropriate permissions are assigned to the User role. See d410086.

Sounds good. One question is, how do you avoid adding it back on a redeploy later on if it was removed on purpose?

> Okay so it looks like we have 3 possible approaches for the three different actions in question:

CONFIGURATION - **Add only if the portlet has a declared configuration (with configuration-action-class)**
PERMISSIONS - **hide** since we don't assign individual permissions for Control Panel portlets.
PREFERENCES - somehow check to see if a portlet has preferences. If so, enable the checkbox. Otherwise, disable it. ==> This is the hardest because in Liferay we "override" the concept of personal user preferences to use it for configuration. However one portlet coded following the standard could have them. In the case of Liferay the dev would need to specify preferences-owned-by-group=false and preferences-company-wide=false (which is not the case for any of Liferay's portlets). Makes sense?

**Comment by drewbrokke** [comment]
> how do you avoid adding it back on a redeploy later on if it was removed on purpose?

This is a VERY good question.  I just sent you a pull with a possible solution.

https://github.com/JorgeFerrer/liferay-portal/pull/812

**Comment by pei-jung** [comment]
Hey @JorgeFerrer,

> This is the hardest because in Liferay we "override" the concept of personal user preferences to use it for configuration. However one portlet coded following the standard could have them. In the case of Liferay the dev would need to specify preferences-owned-by-group=false and preferences-company-wide=false (which is not the case for any of Liferay's portlets).

Just want to clarify a couple things. When we say portlet preferences, we're talking about the `Look and Feel configuration` of a portlet right? I'm not familiar with the look and feel configuration and am curious what the scope is for this type of configuration and if there's actually any use case for having this action for the control panel portlets because currently we don't show the Look and Feel icon for any portlet in the control panel regardless of permission. I'd like to know the reasoning behind that.

**Comment by JorgeFerrer** [comment]
Hey Pei-Jung,

What I call Preferences (speaking about the UI) is preferences that are
owned by the end user. That is, preferences that any (registered) visitor
to a page could change. In the early days, several portlets at Liferay had
this, but then we took over the PortletPreferences object to store the
configuration set up by an admin. The early meaning can still be achieved
with preferences-owned-by-group=false and preferences-company-wide=false.

Note that when I see the Preferences action in the permission I'm assuming
it's the original notion of user personal preferences, but please double
check.

If so, I think we have several options to clear things up:
1) Make it easier for portlets to support personal user preferences that
are independent of the configuration
2) Get rid of the concept of personal user preferences. This could work out
since we have demoted it so much over the years and it doesn't seem it's
being missed so much

For a long time I though of #1 but lately I'm beginning to consider #2 to
simplify things. What are your thoughts?

Jorge

>

**Pull request closed without merging**
