### PR TITLE
LPS-73725 As a portal admin, I'd like to choose whether to display initials or a generic image for the default user avatar

### PR DESCRIPTION
**Pull request by pei-jung**
Hey Drew,

Can you add an unit test for UserInitialsGenerator? Thanks

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:reopen

**Comment by pei-jung** [comment]
ci:retest

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
Pull request sent to https://github.com/brianchandotcom/liferay-portal/pull/51084 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
