### PR TITLE
LPS-121905 Migrate v2 usages in roles/roles-selector-web

### PR DESCRIPTION
**Pull request by julien**
The <clay:management-toolbar-v2 /> tag has been replaced with the
<clay:management-toolbar /> tag (which uses clay v3).

**Test plan**:
- Form the global menu, select the **Control Panel** tab
- Click on **Users and Organizations**
- Select the **Organizations** tab
- Create a new **Organization**
- Add a user to the new Organization
- Navigate back to the **Organizations** page
- Click on the dropdown menu to the right of the organization's name and
select **Assign Organization Roles**
- Select a **Role**
- In the **Available** tab, select a user and click on **Update
Associations**

### CODE REVIEW

**Comment by julien** [comment]
cc @ambrinchaudhary, @markocikos, @jonmak08

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Review by ambrinchaudhary — APPROVED** [review]

**Review by markocikos — APPROVED** [review]
LGTM!

**Comment by julien** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:close

**Comment by julien** [comment]
Thanks @jbalsas

**Pull request closed without merging**
