### PR TITLE
LPS-121923 Migrate v2 usages in users-admin/users-admin-item-selector-web

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @drewbrokke,

Attached is an update for http://issues.liferay.com/browse/LPS-121923.

**Test Plan:**
1. Login to Liferay
2. Click the **Applications Menu**
3. Click on **Control Panel** -> **Users** -> **Accounts**
4. Click the `+` to add an account
5. Fill in the **Name**
6. Click the **Save** button
7. Click the **Users** link
8. Click the `+` to add an entry
user-admin-item-selector

**NOTE:** the management toolbar in the pages leading up to the `users-admin-item-selector` page, were already buggy to begin.  They are not related to my changes.
image 

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Review by julien — APPROVED** [review]

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by jonmak08** [comment]
ci:test:sf

**Comment by jonmak08** [comment]
ci:test:relevant

**Review by julien — APPROVED** [review]

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
