### PR TITLE
LPS-121924 Migrate v2 usages in users-admin/users-admin-web

### PR DESCRIPTION
**Pull request by julien**
The `<clay:management-toolbar-v2 />` tag has been replaced with the
`<clay:management-toolbar />` tag (which uses clay v3).

Creating users and organizations as well a deleting them
and adding users to organizations works as expected.

**Test plan**:
- From the global application menu select the **Control Panel** tab
- Under **Users**, select **Users and Organizations**
- Check that creating a new user by clicking on the "+" button works
- From the management toolbar check that deactivating the user works
  both from the action button or the dropdown menu
- Select the "Organizations" tab
- From the management toolbar check that removing an organization works
  both from the action button or the dropdown menu
- Select an existing organization by clicking on it's name
- From the management toolbar check that adding a nested user works
- From the management toolbar check that adding a nested organization works
- From the management toolbar check that deactivating, removing or restoring nested
  users or organizations works both from the action button or the dropdown menu

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by julien** [comment]
Hi @drewbrokke, let me know if it's OK when you have a chance - thanks

**Comment by drewbrokke** [comment]
Hey @julien is it intended to have left the inline function calls in the ManagementToolbarDisplayContext? It seems that we're now split between delegating action handling to the props tranformer, and inline function calls.

**Comment by julien** [comment]
Hi @drewbrokke, 

If you're talking about the `javascript:` links, yes - refactoring all the JavaScript is beyond the scope of this issue because we have a lot of modules to migrate, but in any case please let us know what you think.

**Comment by drewbrokke** [comment]
See https://github.com/drewbrokke/liferay-portal/pull/1310. Thanks @julien!

**Pull request closed without merging**
