### PR TITLE
LPS-123864 Add localization to the Country name

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-123864](https://issues.liferay.com/browse/LPS-123864).<br/><br/>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:help

**Comment by pei-jung** [comment]
ci:forward

**Comment by pei-jung** [comment]
ci:forward

**Comment by Sharryxue** [comment]
No unique failure for this pr.
Issue in [rest-builder-jdk8/0](https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/211093/) is addressed in [LPS-124733](https://issues.liferay.com/browse/LPS-124733) and fixed by [commit](https://github.com/brianchandotcom/liferay-portal/pull/96861).
Issue in [CountryLocalServiceTest.testUpdateCountry](https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/371301//testReport/com.liferay.address.service.test/CountryLocalServiceTest/testUpdateCountry) is addressed in [LPS-124798](https://issues.liferay.com/browse/LPS-124798), and will fixed by [commit](https://github.com/pei-jung/liferay-portal/pull/750)
Seems this should either send directly to BChan, or wait for the [commit](https://github.com/pei-jung/liferay-portal/pull/750) of [LPS-124798](https://issues.liferay.com/browse/LPS-124798) get merged.

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
See https://github.com/drewbrokke/liferay-portal/pull/1269

**Pull request closed without merging**
