### PR TITLE
LPS-179114 [client-extensions][workspace] LCP.json or Dockerfile change does not invalidate createClientExtensionConfig task output

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-179114](https://issues.liferay.com/browse/LPS-179114).

/cc @gamerson @petershin

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Comment by gamerson** [comment]
I love PRs that improve things by deleting more lines of code.

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:reevaluate:1407401_1822

**Comment by drewbrokke** [comment]
@petershin @gamerson any objections to forwarding this pull?

**Review by gamerson — APPROVED** [review]
LGTM!

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
