### PR TITLE
LPS-112965 uses generic "type" language key for asset libraries, organizations and site columns in the role selection

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
Hi @drewbrokke 

We changed the label on the selector of roles on the sites/asset libraries/organization to "type" instead of "roleType" that didn't exist.

Can you check if this change is ok?

Thanks!

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
cc/ @adolfopa

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
Hi @drewbrokke ,

We changed the label on the selector of roles on the sites/asset libraries/organization to "type" instead of "roleType" that didn't exist.

Can you check if this change is ok?

Thanks!

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
See https://github.com/drewbrokke/liferay-portal/pull/1050

**Pull request closed without merging**
