### PR TITLE
LPS-114717 User and Organizations Search Filter Types not working

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-114717](https://issues.liferay.com/browse/LPS-114717).<br><br>Hey @joshuacords, I attempted to simplify the test case as much as possible. From my local testing, it fails and passes when it's supposed to. Would you be willing to double-check my work in case I missed anything\? Thanks!<br><br>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez

### CODE REVIEW

**Comment by drewbrokke** [comment]
@joshuacords also see https://github.com/drewbrokke/liferay-portal/pull/1111/commits/711d1c7b7452197b141341421edcf10c1cbd154f. That is the only actual meaningful change as to what's being tested. Basically, I upped the organization type count to 5, and the test started failing. This is because the OrganizationTypeComprator (and the code I copied from it) was comparing types by insertion order instead of by type name like the indexer does, so I updated the inlined comparator to reflect that.

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
The code looks pretty good, the only concerns I have are:
1. This test method will end in a state where there will be organizations without a valid type (since the org types will be deleted) while other test methods in this test class finish. I'm not sure if there could be any problems, but ci:test:relevant should reveal that.
2. It seems like we're just going to assume the only organizations present in the company are ones created by the test. That's the assumption so far, so I guess we can stick to it.

If Relevant passes this looks good. Thanks

**Comment by joshuacords** [comment]
Actually, one potential problem, if there's an exception with OrganizationTestUtil.addOrganization(organizationType) - it happens to have the same name or something fails - we'll end up with Configurations that are never removed. It seems to me the try should cover the for loop including the organization creation clause.

**Comment by joshuacords** [comment]
FYI @drewbrokke, I fixed the flaky test OrganizationLocalServiceWhenSearchingOrganizationsTreeTest.testShouldIncludeSuborganizationsAsAdminUser here https://github.com/drewbrokke/liferay-portal/pull/1112

**Comment by drewbrokke** [comment]
@joshuacords those are good points. I'll update the test case to account for those cases. Even though relevant passed, I agree that it may randomly be flaky at some point in the future.

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
