### PR TITLE
LPS-113325

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-113325

From @rolandpakai 

> The changes are in the user-admin-web and frontend-js-aui-web::util.js
> 
> This issue is related to adding and removing assets in the User's Regular Roles, Organization Roles, Site Roles, Asset Library Roles, Sites, User Groups, Organizations.
> 
> Initial state:
> Adding to the assets was handled by the selectEntity::disableSelectedAssets,
> removing from the assets was handled by sync events, fE: regularRoleSyncEntitiesEventName.
> But when performing a search in the asset lists the searhContainer was not updated by this functions.
> 
> Fixed state:
> Now the selectEntity::syncAssets handles both the adding and removing functionalities.
> And additionally i created a searchContainerUpdateDataStore function which handles the groupId.

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by rolandpakai** [comment]
Hi @drewbrokke 
could you please review this PR?
Thanks, Roland

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
@rolandpakai sorry about the delay! I'm looking at it now.

**Comment by drewbrokke** [comment]
See https://github.com/ChrisKian/liferay-portal/pull/227

**Pull request closed without merging**
