### PR TITLE
LPS-198875 Upgradle plexus-utils version to 3.0.24 to avoid vulnerability

### PR DESCRIPTION
**Pull request by Seiphon**

### CODE REVIEW

**Comment by Seiphon** [comment]
ci:test:sf

**Comment by Seiphon** [comment]
ci:test:relevant

**Comment by Seiphon** [comment]
The sf issue have been fixed in this pr https://github.com/ling-alan-huang/liferay-portal/pull/2243

**Review by drewbrokke — APPROVED** [review]

**Comment by drewbrokke** [comment]
Looks good, thanks @Seiphon!

**Comment by drewbrokke** [comment]
ci:forward:force

**Pull request closed without merging**
