### PR TITLE
LPS-127386 Commerce modules do not resolve on DXP using release packaging

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-127386](https://issues.liferay.com/browse/LPS-127386).<br/><br/>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez @vicnate5

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:upgrade

**Comment by drewbrokke** [comment]
ci:test:license

**Comment by drewbrokke** [comment]
ci:test:lpkg

**Comment by drewbrokke** [comment]
@vicnate5 this lpkg suite failure looks similar to what you referenced here: https://github.com/drewbrokke/liferay-portal/pull/1294#issuecomment-775606237. Is that correct?

**Comment by vicnate5** [comment]
@drewbrokke Yes, this looks good so far. I can check the upgrade suite results when they come in.

**Comment by vicnate5** [comment]
@drewbrokke The `NoSuchRoleException` on Account Manager is still ocurring, but seemingly randomly. It only happens on some of the tests, no apparent relationship to environment or portal version either. Could be a race condition.

Example failure: https://testray.liferay.com/reports/production/logs/test-1-5/1612888046398/test-portal-acceptance-pullrequest(master)/7686/functional-upgrade-tomcat90-mysql57-jdk8/7/15/liferay-log.txt.gz

Example passing: https://testray.liferay.com/reports/production/logs/test-1-5/1612888046398/test-portal-acceptance-pullrequest(master)/7686/functional-upgrade-tomcat90-mariadb102-jdk8/7/0/liferay-log.txt.gz

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:upgrade

**Comment by drewbrokke** [comment]
ci:test:license

**Comment by drewbrokke** [comment]
ci:test:lpkg

**Comment by drewbrokke** [comment]
@vicnate5 are these failures still unique?

**Comment by vicnate5** [comment]
@drewbrokke Looks good now

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
Thanks @vicnate5 !

**Pull request closed without merging**
