### PR TITLE
LPS-127386 Commerce modules do not resolve on DXP using release packaging

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-127386](https://issues.liferay.com/browse/LPS-127386).<br/><br/>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez @vicnate5

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:upgrade

**Comment by drewbrokke** [comment]
ci:stop

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:upgrade

**Comment by drewbrokke** [comment]
ci:test:license

**Comment by drewbrokke** [comment]
ci:test:lpkg

**Comment by vicnate5** [comment]
@drewbrokke This upgrade error is unique (upgrade from 7.1.10.3)
https://testray.liferay.com/reports/production/logs/test-1-5/1612830699473/test-portal-acceptance-pullrequest(master)/7685/functional-upgrade-tomcat90-mysql57-jdk8_stable/0/2/jenkins-console.txt.gz

The lpkg hot deployment failure is unrelated (https://issues.liferay.com/browse/COMMERCE-5427)

**Comment by drewbrokke** [comment]
ci:close

**Pull request closed without merging**
