### PR TITLE
YAML to publish liferay-stripe-workspace

### PR DESCRIPTION
**Pull request by aswinrajeevofficial**
This PR contains a new YAML to publish the Stripe workspace to Nexus.

### CODE REVIEW

**Review by drewbrokke — APPROVED** [review]
LGTM, thanks @aswinrajeevofficial!

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
ci:stop

**Review by drewbrokke — CHANGES_REQUESTED** [review]
Sorry @aswinrajeevofficial I just noticed - is there an associated JIRA ticket for this? We're gonna need that before Brian will merge.

**Comment by aswinrajeevofficial** [comment]
Hey @drewbrokke, I can create one. Should it be an LPD?

**Comment by drewbrokke** [comment]
@aswinrajeevofficial I'm gonna close for now. Please resend to @liferay-devtools once you have a JIRA ticket to send against. Thanks!

**Pull request closed without merging**
