### PR TITLE
LPS-121868

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @drewbrokke,

Attached is an update for http://issues.liferay.com/browse/LPS-121868.

**Test Plan:**
1. Login to Liferay
2. Click on the **Applications Menu**
3. Go to **Control Panel** -> **System Settings**
config-admin

**NOTE:** There seems to be a current bug where when searching it throws a _NullPointer_ exception.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
ci:test:sf

**Comment by jonmak08** [comment]
ci:test:relevant

**Review by julien — APPROVED** [review]

**Comment by jonmak08** [comment]
ci:test:relevant

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by jonmak08** [comment]
ci:test:relevant

**Comment by jonmak08** [comment]
ci:test:relevant

**Review by julien — APPROVED** [review]

**Comment by jbalsas** [comment]
Minimal changes and green, forwarding as agreed with @drewbrokke. Going to try to hit forward from here and see if it does not retrigger tests.

**Comment by jbalsas** [comment]
ci:forward

**Pull request closed without merging**
