### PR TITLE
[TS] LPS-121271

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@jonathanmccann this looks good, so if we can get the tests to pass then we're good to go!

**Comment by drewbrokke** [comment]
@patriciajeanperez do we have functional test coverage for this case? Seems like if we did it should be failing. Would you be willing to double-check that for us? Thanks!

**Comment by patriciajeanperez** [comment]
Hi @drewbrokke, we haven't automated this yet and has only been part of our manual testing. I checked the Announcements component and it seems like no tests are failing there as well. I can manually test this change today and automate in our next sprint.

**Comment by patriciajeanperez** [comment]
Hi @drewbrokke! The failing poshi tests are caused by a different issue. I also tested the change in my local and didn't find any issues.

**Comment by drewbrokke** [comment]
@jonathanmccann can you please rebase and resend? I'll make sure my origin branch is up-to-date. Thanks!

**Comment by jonathanmccann** [comment]
https://github.com/drewbrokke/liferay-portal/pull/1190

**Pull request closed without merging**
