### PR TITLE
LPS-106314, LPS-104660 | master

### PR DESCRIPTION
**Pull request by Sharryxue**
https://issues.liferay.com/browse/LPS-106314
https://issues.liferay.com/browse/LPS-104660

Hello @drewbrokke,
I've made fix for these two issue, would it be possible for you or have someone with helping reviewing the commits when get a chance? Thanks in advance.

### CODE REVIEW

**Comment by Sharryxue** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
PR for LPS-106314 sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/85632

**Comment by drewbrokke** [comment]
PR sent to https://github.com/brianchandotcom/liferay-portal/pull/85780

**Pull request closed without merging**
