### PR TITLE
LPS-109676 Asset Library permissions configuration should be scoped to Asset Library roles

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
Forced push to fix typo in the method description

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
Pr sent to https://github.com/pei-jung/liferay-portal/pull/588

**Pull request closed without merging**
