### PR TITLE
LPS-109676 Use right icon.

### PR DESCRIPTION
**Pull request by cgoncas**
Hey @drewbrokke,

We need to filter the Depot Roles, the same way we do with the Site roles.

Here you have an example of what we need to do, but probably is not a good idea for *portlet-configuration-web* to depends on *depot-api*, so maybe we need a Provider to help exclude some roles.

What do you think? If you think another architecture is better, you can tell us and we would be able to implement it.

/cc @adolfopa @AliciaGarciaGarcia

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
@cgoncas I'm torn two ways on this one. On one hand, I agree that this _should_ have be re-worked so we don't hard-code anything, but I'm inclined to wait a little until things settle between Depot roles and Account roles so we'll have a full picture of what's needed for a new Role type. To me it could be an acceptable trade-off to _temporarily_ have that dependency here in order to have enough perspective to make the SPI. Then once we build out a proper SPI to cover the necessary spots, we can go through and clean up the hard-coded stuff.

I can see it taking some time to do it properly, but I don't want to block your team too much.

@pei-jung I'm curious to hear your input on this idea, especially since you're actively working with development related to Account Roles.

**Comment by drewbrokke** [comment]
ci:stop

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Hey @drewbrokke 

Any update about this? Let me know if you need anything.

Thanks!

**Comment by drewbrokke** [comment]
Hey @adolfopa, sorry about the delay. We are looking at leveraging the current APIs to apply this change in a flexible way. We have an interest in doing this for Account Roles as well. I will try to get this moving by the end of the week.

**Comment by drewbrokke** [comment]
Hi @cgoncas @adolfopa, I wanted to update you about this pull. @pei-jung is actively working on a solution right now. We are currently tweaking a couple things based off of these changes: https://github.com/drewbrokke/liferay-portal/pull/995. Just wanted to keep you in the loop :)

**Comment by drewbrokke** [comment]
@cgoncas @adolfopa please see https://github.com/pei-jung/liferay-portal/pull/588.

**Pull request closed without merging**
