### PR TITLE
LPS-100523

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-100523

Resend of https://github.com/arboliveira/liferay-portal/pull/779, with all the logic moved to UserLocalServiceImpl. Let me know if you'd like me to move the UserReindexManager to a different package, or if you'd like me to implement it differently.

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
@holatuwol I think the classname is fine, but we should change the package. Possibly:
- `com.liferay.portal.util`
- `com.liferay.portal.search`
I'm open to other suggestions as well.

@brianchandotcom any preferences on where a `UserReindexManager` would go inside `portal-impl`?

**Comment by brianchandotcom** [comment]
I'd suggest a new brand package. Open to suggestions. B

**Comment by drewbrokke** [comment]
Unless I'm missing something, `com.liferay.portal.search` is tiny. Like one class and a couple of text files. Perhaps a sub-package there? `com.liferay.portal.search.indexer`?

We also have a file at `portal-impl/src/com/liferay/portlet/usersadmin/util/UserIndexer.java`. The new class could go there as well.

**Comment by drewbrokke** [comment]
PR sent to https://github.com/holatuwol/liferay-portal/pull/101

**Pull request closed without merging**
