### PR TITLE
[TS] LPS-105213

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-105213

CCing @lipusz as this is security related.

Although we are opening the "Forms" site up to be selectable during role permission definition, it shouldn't actually have any negative impact, since selecting "All Sites" already included the Forms site.  It does however allow the user to fix the damage they may have caused described in LPS-105213.

Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
Test failures seem unrelated.  My changes only allow for the Forms site to be selectable, and thus should have no initial impact on anything back-end.

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
PR sent to https://github.com/brianchandotcom/liferay-portal/pull/81599

**Pull request closed without merging**
