### PR TITLE
LPS-83662 Site Content Reviewer role can be deleted despite Workflow Definition associated with it

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @drewbrokke 

Thank you for pointing out the semantic versioning error in https://github.com/drewbrokke/liferay-portal/pull/526#issuecomment-412583176

I corrected that part, and resending the pull request.

Best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:reopen

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by IstvanD** [comment]
Hey @drewbrokke 

I was wondering if you managed to review the change.
Please let me know if you need any help or explanation.

Thank you and best regards,
István

**Comment by drewbrokke** [comment]
Hey @IstvanD, sorry about the delay.  I'm going to finish my review today.  Thanks for checking in!

**Comment by drewbrokke** [comment]
Hey @IstvanD, after looking at this for a little, I'm no longer sure that preventing the role from being deleted is the correct approach.  

It seems that the main technique for handling a situation like this (where invalid data is left over in foreign tables) is to use a ModelListener to remove related data.  A good example of this is [DDMStructureModelListener.java](https://github.com/liferay/liferay-portal/blob/master/modules/apps/journal/journal-service/src/main/java/com/liferay/journal/internal/model/listener/DDMStructureModelListener.java) in the journal-service module.  Rather than preventing the DDMStructure from being deleted, they rather opt to remove any articles that depend on that structure.  While this is extreme, so is deleting a used DDMStructure.  I looked through many other model listeners, and this practice is common.

I think I prefer this approach for 2 reasons:

1. There is no need to handle a ModelListener exception or display a custom message in the UI.  It results in much less code to maintain, and eliminates the need for a new exception type in portal-kernel.  In looking through the code, there are very few places where we ever catch a `ModelListenerException`, even though there are lots of places that could trigger them.
2. There are no hidden rules for when one can or cannot delete a Role.  This is the primary reason I began thinking this way, since I realized that the ModelListener was very aggressive, and I've still not figured out how to delete the role.  This can present a problem when the steps to resolving whatever is blocking a role from deletion are not clearly laid out. I think instead we should be permissive in deleting the role and put the responsibility to clean up on the individual apps.

Thanks for all your work so far. Let me know if you have any questions or thoughts about this.

Please update the branch with these changes and re-send. Closing.

**Comment by drewbrokke** [comment]
@IstvanD one more comment.  If you add a RoleModelListener to the workflow component that simply cleans up in the Workflow tables, those changes do not have to go through our team, because it ultimately does not affect the Roles component at all.

**Pull request closed without merging**
