### PR TITLE
LPS-119517 Remove account-api dependency from users-admin-web

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-119517](https://issues.liferay.com/browse/LPS-119517).<br><br>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
ci:forward

**Comment by Sharryxue** [comment]
Hello @drewbrokke 
The SF issue seems related to these commits, would you please double checking the details.jsp and password.jsp file?
```
     [exec] $ liferay-npm-scripts check
     [exec] apps/users-admin/users-admin-web/src/main/resources/META-INF/resources/organization/details.jsp: BAD
     [exec] apps/users-admin/users-admin-web/src/main/resources/META-INF/resources/user/password.jsp: BAD
```
[modules-unit-project-templates-jdk8](https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1,label_exp=!master/425920//testReport/com.liferay.project.templates.rest.builder/ProjectTemplatesRESTBuilderTest/testCompareRESTBuilderPluginVersions) failed for connection issue, might be flaky
[modules-integration-mysql57-jdk8/0](url) is in commen with upstream and might be flaky, addressed in LRQA-59739

**Comment by drewbrokke** [comment]
See https://github.com/drewbrokke/liferay-portal/pull/1159

**Pull request closed without merging**
