### PR TITLE
LPS-88240

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-88240

Hey Drew, I'm 99% sure this is the solution, but I'm going to have CI run before I assign everything to you.

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:upgrade

**Comment by drewbrokke** [comment]
ci:test:upgrade

**Comment by ChrisKian** [comment]
See my comment [here](https://github.com/drewbrokke/liferay-portal/pull/687#issuecomment-445302391) about why I believe these test failures are false positives.  Assigning this LPS to you now.

**Comment by pei-jung** [comment]
Hi @ChrisKian 

I tried running the upgrade on PostgreSQL with your chage, and it fails with the following error. Looks like the `LayoutSet.privateLayout` field is BOOLEAN in PostgreSQL but TINYINT in MySQL.

<pre>
com.liferay.portal.kernel.upgrade.UpgradeException: com.liferay.portal.kernel.upgrade.UpgradeException: org.postgresql.util.PSQLException: ERROR: operator does not exist: boolean = integer
  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
  Position: 74
	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:101)
	at com.liferay.portal.kernel.upgrade.util.UpgradeProcessUtil._upgradeProcess(UpgradeProcessUtil.java:176)
	at com.liferay.portal.kernel.upgrade.util.UpgradeProcessUtil.upgradeProcess(UpgradeProcessUtil.java:143)
	at com.liferay.portal.kernel.upgrade.util.UpgradeProcessUtil.upgradeProcess(UpgradeProcessUtil.java:125)
	at com.liferay.portal.events.StartupHelper.upgradeProcess(StartupHelper.java:151)
	at com.liferay.portal.events.StartupHelperUtil.upgradeProcess(StartupHelperUtil.java:85)
	at com.liferay.portal.tools.DBUpgrader.upgrade(DBUpgrader.java:174)
	at com.liferay.portal.tools.DBUpgrader.main(DBUpgrader.java:107)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.liferay.portal.tools.db.upgrade.client.DBUpgraderLauncher.main(DBUpgraderLauncher.java:55)
Caused by: com.liferay.portal.kernel.upgrade.UpgradeException: org.postgresql.util.PSQLException: ERROR: operator does not exist: boolean = integer
  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
  Position: 74
	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:101)
	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:142)
	at com.liferay.portal.upgrade.UpgradeProcess_7_0_0.doUpgrade(UpgradeProcess_7_0_0.java:101)
	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:96)
	... 12 more
Caused by: org.postgresql.util.PSQLException: ERROR: operator does not exist: boolean = integer
  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
  Position: 74
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2412)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2125)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:297)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:117)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at com.liferay.portal.upgrade.v7_0_0.UpgradeOrganization.upgradeOrganizationLogoId(UpgradeOrganization.java:41)
	at com.liferay.portal.upgrade.v7_0_0.UpgradeOrganization.doUpgrade(UpgradeOrganization.java:34)
	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:96)
	... 15 more
</pre>

**Comment by ChrisKian** [comment]
Thanks for catching that Pei-jung!  I've rebased and resent with the new solution here: https://github.com/drewbrokke/liferay-portal/pull/689

**Pull request closed without merging**
