### PR TITLE
LPS-128992 Migrate v2 usages in marketplace/marketplace-app-manager-web

### PR DESCRIPTION
**Pull request by julien**
The <clay:management-toolbar-v2 /> tag has been replaced with the
<clay:management-toolbar /> tag (which uses clay v3).

Search for installed applications and modules should work as expected.

**Test plan**
- From the mega menu, select the **Control Panel** tab
- Navigate to **System** > **App Manager**
- Make sure you can search for installed applications and modules

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by julien** [comment]
cc @ambrinchaudhary @markocikos @jonmak08

**Comment by jbalsas** [comment]
ci:forward

**Comment by jbalsas** [comment]
Trivial, so forwarding ourselves to help out @drewbrokke with the workload as agreed

**Pull request closed without merging**
