### PR TITLE
LPS-198873 Upgrade antisamy version to 1.7.4 to avoid vulnerability

### PR DESCRIPTION
**Pull request by Seiphon**

### CODE REVIEW

**Comment by Seiphon** [comment]
ci:test:sf

**Comment by Seiphon** [comment]
ci:test:relevant

**Comment by Seiphon** [comment]
ci:test:relevant

**Review by drewbrokke — APPROVED** [review]

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:forward

**Comment by Seiphon** [comment]
ci:test:relevant

**Review by drewbrokke — CHANGES_REQUESTED** [review]
@Seiphon looks like [these failures](https://github.com/drewbrokke/liferay-portal/pull/1534#issuecomment-1782436356) are related. Can you please look into them?

**Comment by Seiphon** [comment]
OK, will fix the issue and resend the pr

**Pull request closed without merging**
