### PR TITLE
LPS-115541 | master

### PR DESCRIPTION
**Pull request by Sharryxue**
https://issues.liferay.com/browse/LPS-115541

Commit is only for master, thanks.

### CODE REVIEW

**Comment by Sharryxue** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
Looks good! Forwarding.

**Pull request closed without merging**
