### PR TITLE
LPS-130073 Source Formatting: Normalize configuration name lang keys

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-130073](https://issues.liferay.com/browse/LPS-130073).<br/><br/>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez

@topolik FYI a71b04a12ec8 595b0be18e72 f198aadec045

### CODE REVIEW

**Comment by Sharryxue** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
Trigger the relevant ci tests.

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
Follow-up PR with new Source Formatter rule: https://github.com/liferay-usm/liferay-portal/pull/11

**Pull request closed without merging**
