### PR TITLE
LPS-130588 User can perform actions on user group that they have no permission

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-130588](https://issues.liferay.com/browse/LPS-130588).<br/><br/>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
@ChrisKian FYI see e224419232ea

**Comment by drewbrokke** [comment]
ci:stop

**Comment by drewbrokke** [comment]
ci:forward

**Comment by brianchandotcom** [comment]
@drewbrokke I merged this.

**Comment by drewbrokke** [comment]
ci:stop

**Comment by drewbrokke** [comment]
ci:close

**Pull request closed without merging**
