### PR TITLE
LPS-94490 As a developer I'd like Instance Settings to allow factory (repeatable) configuration UIs

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-94490](https://issues.liferay.com/browse/LPS-94490).

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@csierra would you be willing to test this branch and see if it fits your needs? Please let me know if anything does not work correctly or is missing. Thanks!

cc @pei-jung @mhan810 @dejuknow

**Comment by drewbrokke** [comment]
cc @jorgeferrer

**Comment by drewbrokke** [comment]
cc @arthurchan35

**Comment by JorgeFerrer** [comment]
Hey Drew,
It's great to see you've made so much progress on this.
What approach have you followed to "inherit" factory configurations?
I mean, if at the system level there are some instances and then at the instance level some other instances are created, do they get added in addition to the system-level ones? do they replace them? Something else?
Thanks

**Comment by drewbrokke** [comment]
@JorgeFerrer thanks for bringing that up, it's the big question with this change. 

Right now, when you save a factory configuration at the instance scope, it saves it under the extended `factoryPid` of `${factoryPid} + ".scoped"`, so it's actually a completely different `pid` than the ones saved under System Settings (which is just the `factoryPid`).

In the UI of Instance Settings, when viewing the list of factory instances, the system-level factory instances are not shown, only those saved at the company scope.

As far as retrieving factory instances goes, there is not a standard method for that right now. If you wanted to retrieve all defined at the system level in addition to the company level, you'd need to collect them manually.

**Comment by JorgeFerrer** [comment]
Thanks for your answer Drew. 
Regarding ${factoryPid} + ".scoped", doesn't it have the companyId in it? wouldn't configurations for different company ids conflict? 
We should also take into account the possibility of extending the scoping further to groups, even if we don't do it now.

Regarding the retrieval, I believe we should provide some helpers to promote consistency and avoid code duplication. At the very least we should be able to do it through ConfigurationProvider for those use cases where using pull for retrieving the configuration is a valid option.

What do you think?

**Comment by drewbrokke** [comment]
@JorgeFerrer the `companyId` is actually saved into the properties themselves, so there's no need to encode it into the `pid`. Then we can just use standard filtering to get exactly the configurations we need with a filter string like this:
```
(&(service.factoryPid=foo.bar.BazConfiguration.scoped)(companyId=12345))
```
Also, it's fully compatible with groups :). See https://github.com/liferay/liferay-portal/blob/34f07e8117c2d6e2f0376cb5208ff18af7fe1a44/modules/apps/static/portal-configuration/portal-configuration-metatype-api/src/main/java/com/liferay/portal/configuration/metatype/annotations/ExtendedObjectClassDefinition.java#L57-L94. The "propertyKey" for a scope is what's saved to the properties of a configuration.

> Regarding the retrieval, I believe we should provide some helpers to promote consistency and avoid code duplication. At the very least we should be able to do it through ConfigurationProvider for those use cases where using pull for retrieving the configuration is a valid option.

I agree, though I'm not confident of the best approach for factory configurations. ConfigurationProvider already handles non-factory configurations well at all scopes, and we also have a push-based example here (again, not for "factory"): https://github.com/liferay/liferay-portal/blob/34f07e8117c2d6e2f0376cb5208ff18af7fe1a44/modules/apps/product-navigation/product-navigation-personal-menu-web/src/main/java/com/liferay/product/navigation/personal/menu/web/internal/configuration/PersonalMenuConfigurationTrackerImpl.java. Generally, it seems that factory configurations have been handled manually so far since ConfigurationProvider does not deal with them.

So far my best guess is basically using a wrapper class that encompasses two managed service factories, one for system-level and one for all other scopes, and exposes a simple API for retrieving all configurations at a designated scope. I'm very open to design suggestions at this stage.

**Comment by JorgeFerrer** [comment]
> @JorgeFerrer the companyId is actually saved into the properties themselves, so there's no need to encode it into the pid.
Cool!

> So far my best guess is basically using a wrapper class that encompasses two managed service factories, one for system-level and one for all other scopes, and exposes a simple API for retrieving all configurations at a designated scope. I'm very open to design suggestions at this stage.

I haven't looked into it in detail, so you probably know better. Could you code that solution (it can be partial) and send a pull to yourself to show us how it would look like?

**Comment by drewbrokke** [comment]
> Could you code that solution (it can be partial) and send a pull to yourself to show us how it would look like?

I'd be happy to! Though I actually realized we're already most of the way there with `ScopedConfigurationManager`, so I may just try to improve it so we can offer a sane API through `ConfigurationProvider`.

**Comment by csierra** [comment]
hey @drewbrokke, 
I have been looking at this and making some tests. It looks like it does the things that we need. Just one comment, though. I have seen that the configurations that belong to the instances are "stored" with ".scoped." in the pid and "system" configurations are stored without the ".scoped." in the pid and no companyId property. That makes integration with `@Component` more difficult. Would it be possible to differentiate them having "companyId=0" but the same configuration pid?

thanks!

**Comment by drewbrokke** [comment]
@csierra thanks for the response. I will see if we can do that. We may also be able to query on the _absense_ of any of the scope properties (no `companyId` or `groupId` present), which would be even easier.

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@csierra just pushed the change based on your suggestion. See bc9ca15.

**Comment by csierra** [comment]
hey @drewbrokke, 
I have checked the changes and they look good for and seem compatible with using DS components. 
The only problem I see is there are existing usages of `.scoped` configuration PIDs and this change removes that. 

Carlos.

**Comment by drewbrokke** [comment]
Hey @csierra, could you give me an example of what you mean? The current behavior for other non-factory (repeatable) configurations should be preserved.

**Comment by drewbrokke** [comment]
After talking with @csierra, I am going to move forward with this pull in its current state. Now that repeatable configurations all share the same `pid`, they remain compatible with DS paradigms.  It is worth discussing if we should move back to a single `pid` for non-repeatable configurations at some point in the future to make them more compatible with DS tooling.

@JorgeFerrer I'll take a look at extending ConfigurationProvider to provide an API for retrieving these repeatable configurations for apps that are ok with pull-based retrieval.

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
