### PR TITLE
LPS-201698 Include @FeatureFlags in the unit test rule

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-201698](https://issues.liferay.com/browse/LPS-201698).

FYI @4lejandrito @BryanEngler @ethib137

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
Beautiful!

**Comment by drewbrokke** [comment]
Just pushed an update removing `PortalRunModeClassTestRule`. Turns out it is not needed in this case.

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
@drewbrokke good to go from my side.

**Comment by epark18** [comment]
Good to go on QA side.

**Comment by drewbrokke** [comment]
Thanks @epark18!

**Comment by BryanEngler** [comment]
@drewbrokke looks good to me, thanks!

@xbrianlee fyi seems like ElasticsearchIndexSearcherSearchAfterTest didnt run during relevant here? not sure if thats expected or not here? maybe because the test was in the root internal package?

**Comment by drewbrokke** [comment]
ci:forward:force

**Pull request closed without merging**
