### PR TITLE
LPS-88275 Multiple LDAP System Settings entries

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @@ChrisKian @stsquared99

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
PR sent to https://github.com/ChrisKian/liferay-portal/pull/92.

**Pull request closed without merging**
