### PR TITLE
LPS-107623 ConfigurationFieldOptionsProvider lost when editing existing factory instances condition values based on taxonomy of predefined values

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by rotty3000** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
PR sent to https://github.com/brianchandotcom/liferay-portal/pull/83756

**Pull request closed without merging**
