### PR TITLE
LPS-107527

### PR DESCRIPTION
**Pull request by jesseyeh-liferay**
## Problem :grimacing:

This is an update to **[LPS-107527](https://issues.liferay.com/browse/LPS-107527)** that introduces another solution based on the contributor approach from https://github.com/drewbrokke/liferay-portal/pull/970.

## Analysis :nerd_face:

We encounter two issues in the aforementioned pull request:

1. Logic is duplicated in how the [roles](https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-search/portal-search/src/main/java/com/liferay/portal/search/internal/SearchPermissionCheckerImpl.java#L327-L336) and [group roles](https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-search/portal-search/src/main/java/com/liferay/portal/search/internal/SearchPermissionCheckerImpl.java#L379-L385) are obtained between the newly-introduced contributor and the `_createSearchPermissionContext()` method in `SearchPermissionCheckerImpl`
1. [There is a redundancy with how the "roleId" and "roleIds" terms are mirrors of each other](https://github.com/drewbrokke/liferay-portal/pull/970#issue-377379813) in the search query. This occurs because [the "roleId" term is the standardized `TermsFilter` field name](https://github.com/jesseyeh-liferay/liferay-portal/blob/LPS-107527-2/modules/apps/portal-search/portal-search/src/main/java/com/liferay/portal/search/internal/SearchPermissionCheckerImpl.java#L674-L675), but the actual role IDs of interest are associated with the user's "roleIds" term (see Analysis section in https://github.com/wanderlast/liferay-portal/pull/40).

## Solution :tada:

To avoid duplicating logic, we use the contributor to iterate through all of the search query's filters until we find the one with "roleId" as its field name. We then create a copy of this filter, set its field name to "roleIds," and add it as a new filter. We could instead replace the original filter with the new filter, but neither `BooleanFilter` nor `TermsFilter` support editing/removing terms, seemingly by design. As a result, the second issue outlined above remains unresolved.

### CODE REVIEW

**Comment by jesseyeh-liferay** [comment]
ci:test:sf

**Comment by jesseyeh-liferay** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
@jesseyeh-liferay I squashed the test case commits into one, and did a small SF refactor in the contributor class. PR sent to https://github.com/brianchandotcom/liferay-portal/pull/85361

**Pull request closed without merging**
