### PR TITLE
LPS-100616 Remove broken icon link, change href

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @katienesterovich:

Notes from Katie:
> https://issues.liferay.com/browse/LPS-100616
> 
> Previous implementation relied on a discontinued `mystatus` link to return a Skype status-icon. There were two usages - in User Contacts (from LPS ticket) and in Portal Directory widget. There is currently no replacement for the Skype icon in https://issues.liferay.com/browse/LPS-95502 sheet, so I opted to remove it. Additionally, I changed the href syntax used to open Skype (same as used in Loop) since the previous implementation did not work.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
PR sent to https://github.com/brianchandotcom/liferay-portal/pull/81170

**Pull request closed without merging**
