### PR TITLE
[TS] LPS-121467

### PR DESCRIPTION
**Pull request by ChrisKian**
From @kevhlee:

> **Ticket:**
> <https://issues.liferay.com/browse/LPS-121467>
> 
> **Notes:**
> The issue was simply the use of `OrganizationLocalServiceUtil.getTypes()`, which lists all available organization types. We need to only consider the available **children** types.
> 
> Let me know if you have any questions. Thanks!

CC @wanderlast

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
LGTM 👍

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
