### PR TITLE
LPS-71092 Members in a parent site with Site Administrator Role do not have the same rights in the underlying child site

### PR DESCRIPTION
**Pull request by pei-jung**
Hey Drew,

This is an update for [LPS-71092](https://issues.liferay.com/browse/LPS-71092).

A new toggle switch has been added for the Site Admin role.

screen shot 2017-04-05 at 1 12 54 pm

screen shot 2017-04-05 at 1 13 12 pm

/cc @jorgeferrer @ealonso @arthurchan35

### CODE REVIEW

**Comment by pei-jung** [comment]
Hey @Preston-Crary,

Can you take a look at the commit 05f2b13 and see if my changes are good? The issue was adding/removing MANAGE_SUBGROUPS permission to a site role does not take effect immediately until the cache is cleared (going to Server Admin and clear all cache actions). It's due to the `_userPrimaryKeyRolePortalCache` not being cleared when we update the resource permission.

**Comment by Preston-Crary** [comment]
@pei-jung, that's clearing too much.  If you want I can come by and explain how this cache is working.  At least we should only be clearing the _userPrimaryKeyRolePortalCache.  There might be a way to only partially clear that cache.

**Comment by pei-jung** [comment]
@Preston-Crary sure.

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
Pull request sent to https://github.com/pei-jung/liferay-portal/pull/185.

**Pull request closed without merging**
