### PR TITLE
[TS] LPS-107527

### PR DESCRIPTION
**Pull request by ChrisKian**
From @jesseyeh-liferay:

> ## Problem :grimacing:
> 
> **[LPS-107527](https://issues.liferay.com/browse/LPS-107527)**
> 
> Site admins are unable to add new users to a site via Site > People > Membership. This is in contrast to the omni-admin, which does not experience the same issue.
> 
> ## Analysis :nerd_face:
> 
> As the omni-admin, all the users are displayed when attempting to add new users to a site. However, the pool of users displayed to a site admin is incomplete.
> 
> [Diff of the omni-admin (left) and site admin (right) search queries](https://github.com/jesseyeh-liferay/liferay-portal-ee/compare/2af465b..b3f9b4d)
> 
> The site admin query mandates that at least of the conditions in the above diff is true. The following condition in particular
> 
> | Condition | Description |
> | --------- | ----------- |
> | <pre>"terms": {<br>    "roleId" [<br>        "20104",<br>        "20112",<br>        "20111",<br>        "20107",<br>    "boost": 1<br>\}</pre> | `20104` - Guest<br>`20112` - Site Administrator<br>`20111` - Site Member<br>`20107` - User |
> 
> requires that the users to be displayed must have a matching `roleId`. However, if we create a regular, dummy user and examine its sources
> 
> ```
> {
>     ...
>     "_source": {
>         ...
>         "roleId": "20105",
>         "fullName": "dummy user",
>         ...
>         "roleIds": "20107",
>         ...
>     }
> }
> ```
> 
> we can see that a `roleId` of `20105` (Owner) is missing above, and the relevant role (`20107`) is instead contained within `roleIds`.
> 
> ## Solution :tada:
> 
> We alter the query so that `roleId` is instead `roleIds`.
> 
> ## Additional Notes :memo:
> 
> The issue with the site admin not being able to add users can be seen as far back as 7.2 GA1. It is, however, functioning properly on `7.1.x`. Comparing `master` to `7.1.x` reveals a divergence in logic in which [`master` passes a conditional check and proceeds onto permissions filter logic](https://github.com/jesseyeh-liferay/liferay-portal/blob/master/modules/apps/portal-search/portal-search/src/main/java/com/liferay/portal/search/internal/indexer/IndexerSearcherImpl.java#L118), whereas [`7.1.x` fails a similar check](https://github.com/jesseyeh-liferay/liferay-portal-ee/blob/a92d39153a1b0445e5d0edc029616a8d5ed8e71b/portal-kernel/src/com/liferay/portal/kernel/search/BaseIndexer.java#L683).

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
Pull request forwarded to https://github.com/mhan810/liferay-portal/pull/1485.

**Pull request closed without merging**
