### PR TITLE
LPS-50795 Now we can leverage the new remove method to simplify the removal of potential existing tickets

### PR DESCRIPTION
**Pull request by JorgeFerrer**
Please take a look at my changes and test it to make sure I didn't cause any issue. @mikakoivisto Let us know if you have any issues with this solution

### CODE REVIEW

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
It looks like the new method is not implemented.  Is that by design?

**Comment by JorgeFerrer** [comment]
Are you referring to addUniqueTicket()? Why do you say it's not implemented? It deletes previous tickets with the same params and calls the other methods.

**Comment by drewbrokke** [comment]
It's never actually called here: https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/service/impl/UserLocalServiceImpl.java#L3632

**Comment by JorgeFerrer** [comment]
Oh, yeah, sorry I should I clarified that I didn't intend my changes to be complete. We would need to change the invocations that make sense.

BTW, I also didn't remove extraInfo (I forgot). Could you take care of that as well?

When you finish all changes we should simplify the pull by merging some commits. I can do that if you want.

**Comment by JorgeFerrer** [comment]
Closing since this was already applied to master

**Pull request closed without merging**
