### PR TITLE
LPS-69535 Poor Performance in edit_permissions.jsp when Loading Roles

### PR DESCRIPTION
**Pull request by pei-jung**
https://issues.liferay.com/browse/LPS-69535

/cc @jorgeferrer @mbowerman

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:reopen

**Comment by pei-jung** [comment]
Pushed to fix semantic ver.
ci:retest

**Comment by pei-jung** [comment]
ci:retest

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/45728. Thanks <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
