### PR TITLE
LPS-86798

### PR DESCRIPTION
**Pull request by crodriguezy**

### CODE REVIEW

**Comment by crodriguezy** [comment]
cc/ @marianoalvarosaiz

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
PR sent to https://github.com/stsquared99/liferay-portal/pull/15 for peer review <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
