### PR TITLE
[TS] LPS-112246

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-112246

Forwarded from https://github.com/ChrisKian/liferay-portal/pull/268, and initially sent here: https://github.com/ChrisKian/liferay-portal/pull/213#issuecomment-621473308

CC @IstvanD

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
Hi @IstvanD @ChrisKian,

I tried deploying the test.jar in the ticket, but I couldn't get the new category to show up in the Global Menu. I had to register the new category under `PanelCategoryKeys.APPLICATIONS_MENU` instead of `PanelCategoryKeys.ROOT`. Am I missing something here? 

image

I wonder if it's a change introduced by the new global menu in 7.3. If so, we'll probably need to update the solution here to use `PanelCategoryKeys.APPLICATIONS_MENU` since `PanelCategoryKeys.ROOT` is not applicable for registering the top-level categories anymore.

**Comment by IstvanD** [comment]
Hi @pei-jung 

Sorry for the belated answer.
It is not necessary for the new category to show up in the Global Menu. What should be verified is for the "Other" category to be visible in the Define Permissions tab of the newly created role.

Best regards,
István

**Comment by pei-jung** [comment]
ci:close

**Pull request closed without merging**
