### PR TITLE
LPS-186182 Include role briefs as part of the SiteBrief DTO

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-186182](https://issues.liferay.com/browse/LPS-186182).

@zsigmondrab

### CODE REVIEW

**Review by pei-jung — COMMENTED** [review]
LGTM! 👍

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@patriciajeanperez any unique failures in this one?

**Comment by patriciajeanperez** [comment]
@drewbrokke no unique failures on this one, just a version increase required for `com.liferay.headless.admin.user.dto.v1_0.SiteBrief`

**Comment by drewbrokke** [comment]
Thanks @patriciajeanperez!

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
@patriciajeanperez if this one looks good to go, we can manually forward. Thanks!

**Comment by patriciajeanperez** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/135758

**Comment by patriciajeanperez** [comment]
ci:close

**Pull request closed without merging**
