### PR TITLE
LPS-85279 Choose button on assigning roles to User is misaligned

### PR DESCRIPTION
**Pull request by alee8888**
@drewbrokke 
https://issues.liferay.com/browse/LPS-85279

This is a resend of https://github.com/drewbrokke/liferay-portal/pull/567

### CODE REVIEW

**Comment by alee8888** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/63433 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
