### PR TITLE
LPS-63863 individual resource permissions are needed for the group wh…

### PR DESCRIPTION
**Pull request by arbetts**
…en the group is an organization

### CODE REVIEW

**Comment by arbetts** [comment]
ci:retest

**Comment by arbetts** [comment]
ci:retest

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
pull request sent to jorgeferrer#682 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
