### PR TITLE
LPS-108187 As an admin, I want to assign the account manager role to organization users so that they can manage accounts associated to that organization

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @alee8888

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
@drewbrokke Looks like it's not required to set the `showControlPanelIcon` in `ServicePreAction` to view the product menu. I've removed the change from the commit e550764.

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
See https://github.com/pei-jung/liferay-portal/pull/618

**Pull request closed without merging**
