### PR TITLE
LPS-85393

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-85393

Hey Drew,
This issue is kinda tricky in that I'm not 100% sure a solution should even be provided.  Basically, if a user has an exportable field which includes "]]>", we fail when parsing the user's XML-converted-model.  This is because CDATA uses "]]>" as a stop character, and there is no possible way to escape it.  So, I really only see two ways to resolving this issue:

1. Don't allow for certain characters in user fields (or at least prevent "]]>" from being used).
2. "Escape" the stop sequence by splitting it into two CDATA containers.  Here's how it works:

When exporting user data, the XML looks something like this:
`<column-value><![CDATA[FirstName]]> LastName]]></column-value>`
where the first name is "FirstName]]>" and the last name is "LastName".  When parsing the XML, you can see the reader wants to only use this chunk "<![CDATA[FirstName]]>", then parse for the next element.  Since there is no next element, the parser assumes the XML is broken, and throws an error.

My solution would be to simply include "]]" in the first CDATA container, and ">" in the second.  This splits the escape sequence, and allows for it to be used.  Further, there is no limit on how many CDATA containers can be used per element.  The XML would look something like this afterwards:
`<column-value><![CDATA[FirstName]]]]><![CDATA[> LastName]]></column-value>`
If your remove "]]><![CDATA[", you can see it ends up the correct value.

Lastly, if you do test my solution, please note you will receive a different error later on when validating the file name.  The character ">" is a blacklisted character, so the portal throws an exception when trying to create a file called "UAD_FirstName]]> LastName_com.liferay.message.boards.uad_201812132413.zip".  Breakpointing before false is returned in DLValidatorImpl.validateFileName or removing ">" from the character blacklist allows for the export to complete successfully.

Please let me know if you have any questions.  I know the outcome is strange, but this is the only way to "escape" CDATA containers.

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by dejuknow** [comment]
We could also encode the entire text value (eg: html encoding `]]>` becomes `]]&gt;`). But that adds a lot of unnecessary additional processing since encountering `]]>` is quite rare. Personally, I'm fine w/ splitting into two CDATA containers since it's rare and generally accepted [practice](https://stackoverflow.com/questions/223652/is-there-a-way-to-escape-a-cdata-end-token-in-xml) for "escaping" CDATA.

**Comment by dejuknow** [comment]
@ChrisKian For the validating filename issue, that isn't fixed by your PR, right? Can you either create a separate ticket (and link it) for that issue? Or send a separate PR with a fix as part of this ticket (we should escape FirstName and LastName values before creating the export files).

**Comment by ChrisKian** [comment]
Hey @dejuknow,
Correct, the validateFilename issue is not effected by my changes.  I can make a new LPS and send a PR for it.

**Comment by ChrisKian** [comment]
Hey @drewbrokke and @dejuknow,
I decided to force-push the addition validation changes to this PR, rather than open a new LPS.  I'll re-run ci now.

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
Test PR sent here: https://github.com/drewbrokke/liferay-portal/pull/699 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
