### PR TITLE
LPS-121998 Add new service Impl methods to account for the new Country fields

### PR DESCRIPTION
**Pull request by alee8888**
@drewbrokke @pei-jung

https://issues.liferay.com/browse/LPS-121998

### CODE REVIEW

**Comment by alee8888** [comment]
ci:test:sf

**Comment by alee8888** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
Hello @alee8888.
The failure in _ci:test:relevant_ job seems related to the changes, would you please double check?
```
build-common-java.compile:
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-portal/portal-impl/classes
    [javac] Compiling 2549 source files to /opt/dev/projects/github/liferay-portal/portal-impl/classes
 [parallel] /opt/dev/projects/github/liferay-portal/portal-impl/src/com/liferay/portal/service/impl/CountryServiceImpl.java:275: error: cannot find symbol
 [parallel] 		return countryLocalService.updateCountryGroupFilter(
 [parallel] 		                          ^
 [parallel]   symbol:   method updateCountryGroupFilter(long,boolean)
 [parallel]   location: variable countryLocalService of type CountryLocalService
 [parallel] Note: Some input files use or override a deprecated API.
 [parallel] Note: Recompile with -Xlint:deprecation for details.
 [parallel] Note: Some input files use unchecked or unsafe operations.
 [parallel] Note: Recompile with -Xlint:unchecked for details.
 [parallel] 1 error
```

**Comment by alee8888** [comment]
Thanks @Sharryxue yes it i!! I will look into it, thanks again!

**Comment by alee8888** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
Hello @alee8888, 
Seems the failure is related to the changes, would you please double check? Refer to the [full console](https://testray.liferay.com/reports/production/logs/test-1-8/1607489052025/test-portal-acceptance-pullrequest(master)/6667/functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1/jenkins-console.txt.gz)
Some upgrade tests failed due to following error on console, 
`LIFERAY_ERROR: Duplicate entry '0-408' for key 'IX_4B78E87A': create unique index IX_4B78E87A on Country (companyId, number_);`
Besides, there is a warning message in upgrade process
```
     [java] 2020-12-09 07:22:53.100 INFO  [main][BaseDB:99] create unique index IX_4B78E87A on Country (companyId, number_);
     [java] 2020-12-09 07:22:53.126 WARN  [main][BaseDB:107] Duplicate entry '0-408' for key 'IX_4B78E87A': create unique index IX_4B78E87A on Country (companyId, number_);
```

**Comment by drewbrokke** [comment]
@Sharryxue I will be sending myself an updated pull based off of this one and will include a fix for the upgrade test failures.

**Comment by drewbrokke** [comment]
See https://github.com/drewbrokke/liferay-portal/pull/1258

**Pull request closed without merging**
