### PR TITLE
[TS] LPS-124814

### PR DESCRIPTION
**Pull request by jonathanmccann**
There were a few different ways I saw to resolve this issue so if you think a different direction would be better please let me know.

Most of the formatting logic is taken from https://github.com/liferay/liferay-portal/blob/master/modules/apps/login/login-web/src/main/resources/META-INF/resources/login.jsp#L136-L140

Some notes about the implementation:

1. The method was deprecated instead of modifying it to avoid a version increase
2. The date isn't formatted for the log because I thought it would make more sense to have a consistent time zone for the logs
3. The User object is being passed in to avoid complicated fetching logic in the exception class and needing to fetch the user object twice

Please let me know if there are any questions.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
Re-trigger the relavent test since the previous seems hang up.

**Comment by drewbrokke** [comment]
See https://github.com/drewbrokke/liferay-portal/pull/1272

**Pull request closed without merging**
