### PR TITLE
LPS-121998 Add new service Impl methods to account for the new Country fields

### PR DESCRIPTION
**Pull request by alee8888**
@drewbrokke @pei-jung

https://issues.liferay.com/browse/LPS-121995

### CODE REVIEW

**Comment by alee8888** [comment]
ci:test:sf

**Comment by alee8888** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@alee8888 there are merge conflicts here, I think some commits just got merged in from Brian's master branch. Sorry about that. Please rebase and resend.

**Comment by alee8888** [comment]
ci:stop

**Pull request closed without merging**
