### PR TITLE
LPS-112410 Add DELETE endpoint for deleting users

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-112410](https://issues.liferay.com/browse/LPS-112410).<br><br>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
@pyoo47 @patriciajeanperez are these failures present in other pulls? They don't seem related to my changes, but I could be missing something.

**Comment by patriciajeanperez** [comment]
looks like a connection issue mid test run, re-running ci:forward

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
