### PR TITLE
LPS-63834

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
@jorgeferrer fyi, I think this'll force the search engine to complete indexing (e.g. no buffering) before returning control back to the user.

@drewbrokke we may want to actually move that block of code in 3d10e12 to the front-end as opposed to in the service layer since this is a UI issue.

**Comment by drewbrokke** [comment]
@mhan810 I agree it would probably be better to place it in the assignment method of UserGroupsAdminPortlet.  I'll test it.

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
Sent to brianchandotcom#36996.

**Pull request closed without merging**
