### PR TITLE
LPS-83662 Site Content Reviewer role can be deleted despite Workflow Definition associated with it

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @drewbrokke 

Could you please review this pull request?

Please let me know if you're not the reviewer of the Roles component.

Thank you and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test

**Comment by IstvanD** [comment]
ci:reopen

**Comment by drewbrokke** [comment]
Hey @IstvanD, thanks for sending this my way. Overall this looks good, but I'm a little wary of adding a dependency on workflow to the roles admin portlet.  I think the same could be accomplished through the use of a ModelListener, since the `onBeforeRemove` method can throw an exception.  What do you think?

**Comment by drewbrokke** [comment]
@IstvanD please see my above comment and resend with my suggested changes.  If it's indeed not possible any other way, then we can revisit this solution.  Thanks!  Closing for now.

**Comment by IstvanD** [comment]
Hey @drewbrokke 

Thank you very much for your answer and suggestion.
I agree that we shouldn't introduce any dependencies across modules, therefore I modified the solution.
https://github.com/drewbrokke/liferay-portal/pull/525

Could you please review this change?

Thank you and best regards!

István

**Pull request closed without merging**
