### PR TITLE
LPS-115019 Add a "view state" display context holder for search containers to the Clay Taglib

### PR DESCRIPTION
**Pull request by ngriffin7a**
/cc @jbalsas @brunobasto @david-truong @wincent

### CODE REVIEW

**Comment by Sharryxue** [comment]
Trigger the CI test before reviewing started.

**Comment by Sharryxue** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
Hello @ngriffin7a 
Would you please taking care the SF issue and modules-compile-jdk8 failure? Those are failures specific to the commits.

/cc @drewbrokke

**Comment by ngriffin7a** [comment]
@Sharryxue  @drewbrokke I am not able to reproduce the SF failure locally, but I am able to reproduce the `validateTLD` failure. I will work on that now.

**Comment by ngriffin7a** [comment]
See https://github.com/drewbrokke/liferay-portal/pull/1136

**Pull request closed without merging**
