### PR TITLE
LPS-67399 Add a query that returns both organizations and users in order

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pei-jung** [comment]
added test

ci:retest

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
@pei-jung rebase errors.  Please resend. Sorry about that.

**Comment by pei-jung** [comment]
Resent as https://github.com/drewbrokke/liferay-portal/pull/228.

**Pull request closed without merging**
