### PR TITLE
[TS] LPS-122234

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-122234

From @kevhlee:

> **Ticket:**
> https://issues.liferay.com/browse/LPS-122234
> 
> **Description:**
> The issue is simply that the site name is being HTML escaped twice. I removed the usage of `HtmlUtil.escape()` when storing the site name in the `renderResponse` as it seems the site name will be escaped elsewhere.
> 
> Let me know if you have any questions.

CC @wanderlast

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
LGTM 👍 

Looks like the portlet title is being escaped here: https://github.com/liferay/liferay-portal/blob/b81d175c1e665bb5940ca3f5947743277a0b60b1/modules/apps/product-navigation/product-navigation-control-menu-web/src/main/resources/META-INF/resources/entries/portlet_header.jsp#L24

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
