### PR TITLE
LPS-109377 Create AccountRole assignment POST and DELETE endpoints

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-109377](https://issues.liferay.com/browse/LPS-109377).

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@pei-jung would you be willing to give this a quick look and let me know if I should change anything? Thanks!

**Comment by pei-jung** [comment]
LGTM! 👍

**Pull request closed without merging**
