### PR TITLE
LPS-113155 Unable to save Authentication for LDAP in system setting

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-113155](https://issues.liferay.com/browse/LPS-113155).<br><br>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez

### CODE REVIEW

**Comment by drewbrokke** [comment]
cc @Sharryxue

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
@pyoo47 this failure looks unrelated to the changes in this pull. Is that accurate?

**Comment by patriciajeanperez** [comment]
@drewbrokke Flaky test https://issues.liferay.com/browse/LPS-111174, we can re-run

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
