### PR TITLE
[Technical Support] LPS-65275

### PR DESCRIPTION
**Pull request by dustinryerson**
/cc @mbowerman 

https://issues.liferay.com/browse/LPS-65275

### CODE REVIEW

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
Pull request submitted to JorgeFerrer#720.  Thanks!

**Comment by mbowerman** [comment]
Hey @drewbrokke,

After you added [your commit](https://github.com/JorgeFerrer/liferay-portal/pull/720/commits/2a709052d1fb2ddc1ab3915bddd4027407cabdb2), did you test for the case where the portal property is set to true but workflow is disabled for users? The reason I didn't do it that way is because I thought it would fail that use case.

**Comment by drewbrokke** [comment]
That's a good thought, @mbowerman.  I just tested it, and it seems to work fine.  Setting the ThreadLocal to true doesn't seem to have any affect unless the User workflow is enabled.

**Pull request closed without merging**
