### PR TITLE
LPS-195170 fix canBeResolved error in  eclispe after upgrde to Gradle 7

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-195170](https://issues.liferay.com/browse/LPS-195170).

FYI @simonjhy

### CODE REVIEW

**Comment by drewbrokke** [comment]
@simonjhy if this looks good to you, go ahead and forward. Thanks!

**Comment by simonjhy** [comment]
@drewbrokke its ok, thanks

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by simonjhy** [comment]
ci:test:relevant

**Comment by simonjhy** [comment]
ci:test:stable

**Comment by simonjhy** [comment]
ci:test:gradle-plugins

**Comment by simonjhy** [comment]
@drewbrokke I checked the gradle plugs test error. The source format gradle test error need @ling-alan-huang help to check or fix in SF side. The other two issues be  fixed by  ticket https://liferay.atlassian.net/browse/LPS-195620.

**Comment by simonjhy** [comment]
ci:test:stable

**Comment by simonjhy** [comment]
@drewbrokke I fixed several gradleTest error and sent a new pull https://github.com/drewbrokke/liferay-portal/pull/1499 base on this pull.

**Pull request closed without merging**
