### PR TITLE
LPS-114426 buildLang

### PR DESCRIPTION
**Pull request by ealonso**
Hey @drewbrokke @pei-jung,

As part of the changes that we are going to introduce in the Product Menu, we are creating a new Global Menu, see:

Home_-_Liferay

This is the Epic Link https://issues.liferay.com/browse/LPS-112988, If you want, you can access to Figma  to have more details.

The idea is allow the users to configure the permissions for those apps.

I've copied the code from control panel and adapted it to new Global Menu Applications. It is possible that I missed something, since I'm not really familiar with roles, so please let me know if I need to change something else.

Please let me know if you have any question.

Regards,
Eudaldo.

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by pei-jung** [comment]
LGTM

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
