### PR TITLE
LPS-125700 Bridge CommerceAccountGroup service to AccountGroup service

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-125700](https://issues.liferay.com/browse/LPS-125700).<br/><br/>for CI

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:upgrade

**Comment by drewbrokke** [comment]
ci:test:commerce

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:commerce

**Comment by drewbrokke** [comment]
ci:test:accounts

**Comment by drewbrokke** [comment]
ci:test:upgrade

**Comment by Sharryxue** [comment]
Specific issues found in pr:
1. wrong search result returns for deleted account group, refer [POSHI report](https://testray.liferay.com/zh/home/-/testray/case_results/1502113028), and got ES related [console error](https://testray.liferay.com/reports/production/logs/test-1-16/1615334542539/test-portal-acceptance-pullrequest(master)/8009/functional-tomcat90-mysql57-jdk8/0/2/jenkins-console.txt.gz).
2. Issue in [LocalFile.CPCommerceChannels#CreateNewNotificationTemplate](https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=13,label_exp=!master/324553//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_CPCommerceChannels_CreateNewNotificationTemplate_) more like flaky, seems not related
3. Same DB2 upgrade issue, refer [console](https://testray.liferay.com/reports/production/logs/test-1-1/1615334547690/test-portal-acceptance-pullrequest(master)/6513/functional-upgrade-tomcat90-db2111-jdk8/1/6/jenkins-console.txt.gz)
```
     [java] 2021-03-10 02:11:07.887 INFO  [main][UpgradeProcess:101] Upgrading com.liferay.commerce.account.internal.upgrade.v3_0_0.CommerceAccountUpgradeProcess
     [java] 2021-03-10 02:11:07.896 INFO  [main][UpgradeProcess:115] Failed upgrade process com.liferay.commerce.account.internal.upgrade.v3_0_0.CommerceAccountUpgradeProcess in 9 ms
     [java] 2021-03-10 02:11:07.900 ERROR [main][UpgradeStepRegistratorTracker:144] Failed upgrade process for module com.liferay.commerce.account.service
     [java] com.liferay.portal.kernel.upgrade.UpgradeException: com.ibm.db2.jcc.am.SqlSyntaxErrorException: DB2 SQL Error: SQLCODE=-104, SQLSTATE=42601, SQLERRMC=END-OF-STATEMENT;able COMMERCEACCOUNT;IMMEDIATE, DRIVER=4.24.92
```
4. Most upgrade tests failure probably due to flaky issue, since it can not be reproduced on upstream, and the same issue also affect other pr, like in [achaparro#850](https://github.com/achaparro/liferay-portal/pull/850), will retrigger the upgrade test

**Comment by patriciajeanperez** [comment]
Hi @drewbrokke, I checked the Upgrades tests but they are all unrelated. Failures are present in other pulls. The specific error with searching would be searching Account Groups. The following errors would occur and proper results do not show.

`LIFERAY_ERROR: java.lang.RuntimeException: org.elasticsearch.ElasticsearchStatusException: [liferay-45375-workflow-metrics-sla-instance-results/Cj70K8cLSb-N6mEcQxRt_g] ElasticsearchStatusException[Elasticsearch exception [type=resource_already_exists_exception, reason=index [liferay-45375-workflow-metrics-sla-instance-results/Cj70K8cLSb-N6mEcQxRt_g] already exists]]`

The entire log can be viewed [here](https://testray.liferay.com/reports/production/logs/test-1-16/1615334542539/test-portal-acceptance-pullrequest(master)/8009/functional-tomcat90-mysql57-jdk8/0/2/liferay-log.txt.gz). There is another [Commerce functional test](https://testray.liferay.com/reports/production/logs/test-1-18/1615242193892/test-portal-acceptance-pullrequest(master)/5472/functional-tomcat90-mysql57-jdk8/0/5/LocalFile.CPCommercePriceLists_AssertPriceListCanBeAssociatedWithAccountAndAccountGroup/index.html.gz) that is breaking but it doesn't look related. I'll need to verify manually, though. But so far, no console errors.

**Pull request closed without merging**
