### PR TITLE
LPS-77314

### PR DESCRIPTION
**Pull request by noahsherrillwork**
Associated with a separate, more specific ticket per drewbrokke#419.

/cc @pei-jung, @willnewbury, @JorgeFerrer

### CODE REVIEW

**Comment by noahsherrillwork** [comment]
ci:test

**Comment by noahsherrillwork** [comment]
ci:reopen

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
Test PR sent to https://github.com/drewbrokke/liferay-portal/pull/434

**Pull request closed without merging**
