### PR TITLE
LPS-78950

### PR DESCRIPTION
**Pull request by petershin**
@drewbrokke - If the tests pass, please send it to Brian.

@jpince

### CODE REVIEW

**Comment by petershin** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@jpince @petershin it fails on my test pull too: https://github.com/drewbrokke/liferay-portal/pull/708#issuecomment-451609662.  That one just adds a comment to a file in that module so that the relevant tests will run, but besides that there are not changes.

**Comment by jpince** [comment]
@drewbrokke I'm fine if you want to send this to Brian, unless Peter has a strong objection.

**Comment by petershin** [comment]
@jpince - The published version is a snapshot version so CI should have skipped the baseline task.  Tested a fix here and it passed: https://github.com/petershin/liferay-portal/pull/348

Sent Drew's pull with the patch to Brian: https://github.com/brianchandotcom/liferay-portal/pull/66396

@drewbrokke

**Comment by drewbrokke** [comment]
Thanks @petershin!

**Comment by jpince** [comment]
@petershin thanks!

**Pull request closed without merging**
