### PR TITLE
[TECHNICAL-SUPPORT] LPS-83255

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @joshuacords 

Notes from Josh:

> https://issues.liferay.com/browse/LPS-83255
> https://issues.liferay.com/browse/LPP-30788
> 
> These properties are only used in Roles Define Permission page. They were previously used in the other pages in Users, Organizations, and Roles added here: https://issues.liferay.com/browse/LPS-44220 - however the UI of the other pages has changed and the Define Permission page is the only current usage. Because of the limit of their scope along with the generality of their description, customers were expecting much more from these properties.
> 
> Note: the description needs to be updated in the Japanese portal properties as well.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Hey @SamZiemer @joshuacords, thanks for sending this.  Unfortunately, I don't think this is the correct fix, because these properties still affect a much larger scope than just the Roles Define Permissions page.

In master, these properties are checked on [list.jsp](https://github.com/liferay/liferay-portal/blob/master/portal-web/docroot/html/taglib/ui/search_iterator/list.jsp).  This page is shown as the default view when the `search-iterator` taglib is used with no `markupView` or `displayStyle` attribute defined.  See [SearchIteratorTag.java#L79](https://github.com/liferay/liferay-portal/blob/master/util-taglib/src/com/liferay/taglib/ui/SearchIteratorTag.java#L79). There are a number of places where this is the case:

- [wiki/wiki-web/src/main/resources/META-INF/resources/wiki/view_page_activities.jsp](https://github.com/liferay/liferay-portal/blob/master/modules/apps/wiki/wiki-web/src/main/resources/META-INF/resources/wiki/view_page_activities.jsp)
- [wiki/wiki-web/src/main/resources/META-INF/resources/wiki/page_iterator.jsp](https://github.com/liferay/liferay-portal/blob/master/modules/apps/wiki/wiki-web/src/main/resources/META-INF/resources/wiki/page_iterator.jsp)
- [portal-settings/portal-settings-authentication-ldap-web/src/main/resources/META-INF/resources/com.liferay.portal.settings.web/test_ldap_users.jsp](https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-settings/portal-settings-authentication-ldap-web/src/main/resources/META-INF/resources/com.liferay.portal.settings.web/test_ldap_users.jsp)
- [polls/polls-web/src/main/resources/META-INF/resources/polls/view_question_results.jspf](https://github.com/liferay/liferay-portal/blob/master/modules/apps/polls/polls-web/src/main/resources/META-INF/resources/polls/view_question_results.jspf)
- [message-boards/message-boards-web/src/main/resources/META-INF/resources/message_boards/select_category.jsp](https://github.com/liferay/liferay-portal/blob/master/modules/apps/message-boards/message-boards-web/src/main/resources/META-INF/resources/message_boards/select_category.jsp)
- [knowledge-base/knowledge-base-web/src/main/resources/META-INF/resources/search/view_prp_articles.jsp](https://github.com/liferay/liferay-portal/blob/master/modules/apps/knowledge-base/knowledge-base-web/src/main/resources/META-INF/resources/search/view_prp_articles.jsp)
- [knowledge-base/knowledge-base-web/src/main/resources/META-INF/resources/search/search.jsp](https://github.com/liferay/liferay-portal/blob/master/modules/apps/knowledge-base/knowledge-base-web/src/main/resources/META-INF/resources/search/search.jsp)
- [dynamic-data-mapping/dynamic-data-mapping-form-web/src/main/resources/META-INF/resources/display/configuration.jsp](https://github.com/liferay/liferay-portal/blob/master/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-web/src/main/resources/META-INF/resources/display/configuration.jsp)
- [document-library/document-library-web/src/main/resources/META-INF/resources/image_gallery_display/view_folders.jsp](https://github.com/liferay/liferay-portal/blob/master/modules/apps/document-library/document-library-web/src/main/resources/META-INF/resources/image_gallery_display/view_folders.jsp)
- [document-library/document-library-web/src/main/resources/META-INF/resources/document_library/edit_folder.jsp](https://github.com/liferay/liferay-portal/blob/master/modules/apps/document-library/document-library-web/src/main/resources/META-INF/resources/document_library/edit_folder.jsp)
- [bookmarks/bookmarks-web/src/main/resources/META-INF/resources/bookmarks/select_folder.jsp](https://github.com/liferay/liferay-portal/blob/master/modules/apps/bookmarks/bookmarks-web/src/main/resources/META-INF/resources/bookmarks/select_folder.jsp)
- [roles/roles-admin-web/src/main/resources/META-INF/resources/edit_role_permissions_summary.jsp](https://github.com/liferay/liferay-portal/blob/master/modules/apps/roles/roles-admin-web/src/main/resources/META-INF/resources/edit_role_permissions_summary.jsp)
- [roles/roles-admin-web/src/main/resources/META-INF/resources/edit_role_permissions_form.jsp](https://github.com/liferay/liferay-portal/blob/master/modules/apps/roles/roles-admin-web/src/main/resources/META-INF/resources/edit_role_permissions_form.jsp)
- [roles/roles-admin-web/src/main/resources/META-INF/resources/edit_role_permissions_resource.jsp](https://github.com/liferay/liferay-portal/blob/master/modules/apps/roles/roles-admin-web/src/main/resources/META-INF/resources/edit_role_permissions_resource.jsp)
- [portal-search/portal-search-web/src/main/resources/META-INF/resources/open_search.jspf](https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-search/portal-search-web/src/main/resources/META-INF/resources/open_search.jspf)
- [plugins-admin/plugins-admin-web/src/main/resources/META-INF/resources/edit_plugin.jsp](https://github.com/liferay/liferay-portal/blob/master/modules/apps/plugins-admin/plugins-admin-web/src/main/resources/META-INF/resources/edit_plugin.jsp)
- [dynamic-data-lists/dynamic-data-lists-web/src/main/resources/META-INF/resources/configuration.jsp](https://github.com/liferay/liferay-portal/blob/master/modules/apps/dynamic-data-lists/dynamic-data-lists-web/src/main/resources/META-INF/resources/configuration.jsp)
- [contacts/contacts-web/src/main/resources/META-INF/resources/view_requests.jsp](https://github.com/liferay/liferay-portal/blob/master/modules/apps/contacts/contacts-web/src/main/resources/META-INF/resources/view_requests.jsp)
- [deprecated/social-user-statistics-web/src/main/resources/META-INF/resources/view.jsp](https://github.com/liferay/liferay-portal/blob/master/modules/apps/deprecated/social-user-statistics-web/src/main/resources/META-INF/resources/view.jsp)
- [blogs/blogs-recent-bloggers-web/src/main/resources/META-INF/resources/view.jsp](https://github.com/liferay/liferay-portal/blob/master/modules/apps/blogs/blogs-recent-bloggers-web/src/main/resources/META-INF/resources/view.jsp)
- [tasks/tasks-portlet/docroot/tasks/view_tasks.jsp](https://github.com/liferay/liferay-portal/blob/master/modules/apps/tasks/tasks-portlet/docroot/tasks/view_tasks.jsp)
- [powwow/powwow-portlet/docroot/meetings/view_meeting.jsp](https://github.com/liferay/liferay-portal/blob/master/modules/apps/powwow/powwow-portlet/docroot/meetings/view_meeting.jsp)
- [powwow/powwow-portlet/docroot/meetings/meetings.jspf](https://github.com/liferay/liferay-portal/blob/master/modules/apps/powwow/powwow-portlet/docroot/meetings/meetings.jspf)
- [powwow/powwow-portlet/docroot/admin/view.jsp](https://github.com/liferay/liferay-portal/blob/master/modules/apps/powwow/powwow-portlet/docroot/admin/view.jsp)
- [opensocial/opensocial-portlet/docroot/admin/view.jsp](https://github.com/liferay/liferay-portal/blob/master/modules/apps/opensocial/opensocial-portlet/docroot/admin/view.jsp)

We may need to re-word the description to indicate that it will not take effect everywhere (and will take effect in fewer and fewer places as more search containers use the `lexicon` markup view or other display views besides `list`), but we can't say that it only affects Roles Admin at this stage.

Please let me know if you have any questions about my explanation.  I'm gonna close for now until we can come up with more accurate wording.

**Comment by joshuacords** [comment]
Hi @drewbrokke, thanks for helping find the places where this property still effects results. Is it okay to reference that it only affects search containers using  "list" results or something like that, or how else would we go about defining the places it works versus the places it doesn't?

**Comment by drewbrokke** [comment]
I'm honestly not sure what the best approach is in this case.  It's not all "list" results, it's "list" results in the non-lexicon markup view.  Basically, this property is tied to the fate of the non-lexicon markup view.  So if that view is to be considered deprecated, this property will follow suit.  I'd have to defer to @jbalsas for that kind of decision.

**Comment by jbalsas** [comment]
I will, in turn, defer to @victorValle 😂 

In summary, we used to be able to configure where we wanted to show pagination (top or bottom, and in the case of top, what would be the minimum delta to show it). My guess is that we won't be supporting this option moving forward, but asking the UX team for final confirmation here ;)

**Comment by joshuacords** [comment]
Resubmitted here: https://github.com/drewbrokke/liferay-portal/pull/520

**Comment by victorvalle** [comment]
So, we decide to remove it as the use seems to have disappeared. If in the future we need it back again to solve some use case we will study to include it back again.
Thanks everyone!

**Pull request closed without merging**
