### PR TITLE
LPS-121855

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @drewbrokke,

Attached is an update for http://issues.liferay.com/browse/LPS-121855.

**Test Plan:**

1. Login to Liferay
2. Click on the **Application Menu**
3. Click on **Accounts**
4. Add an account
5. Click on the **Application Menu**
6. Click on **Account Users**
7. Click on the `+` to select an account user
8. Click on **Choose**
9. Create a new user

admin-users-account

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
All tests have been run and have passed at https://github.com/jonmak08/liferay-portal/pull/2124

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@jonmak08 @jbalsas There is now a plus button inside the `select_account_entries.jsp` modal window. This is not being called: https://github.com/liferay/liferay-portal/blob/826c3fe5d4dd126575c7e55a0b09238e5087a61a/modules/apps/account/account-admin-web/src/main/java/com/liferay/account/admin/web/internal/display/context/SelectAccountEntryManagementToolbarDisplayContext.java#L61-L64.

It seems that the handling of `isShowCreationMenu` has changed. Since the setter `setShowCreationMenu` is called during `ManagementToolbarTag#doStartTag`, the value of `_showCreationMenu` will never be null during the check inside `ManagementToolbarTag#isShowCreationMenu` and the `isShowCreationMenu` method will never be called on the ManagementToolbarDisplayContext object.

**Comment by markocikos** [comment]
@drewbrokke  Yeah, we seem to have a bug in tag, in handling of `isShowCreationMenu`.

@jonmak08 See more details below. 

This is the [problematic code](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-taglib/frontend-taglib-clay/src/main/java/com/liferay/frontend/taglib/clay/servlet/taglib/ManagementToolbarTag.java#L73-L74):
```js
setShowCreationMenu(
	ManagementToolbarDefaults.isShowCreationMenu(getCreationMenu()));
```
We did not notice the bug before because we have a rare case here, `creationMenu` exists but we don't want to show it. The wiring in v2 was impossible to directly migrate because it went [over Soy context](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-taglib/frontend-taglib-clay/src/main/java/com/liferay/frontend/taglib/clay/servlet/taglib/soy/ManagementToolbarTag.java#L111-L117).

I believe we should delete the code above and have the same handling as other attributes:
```js
public Boolean isShowCreationMenu() {
	if (_showCreationMenu == null) {
		if (_managementToolbarDisplayContext != null) {
			return _managementToolbarDisplayContext.isShowCreationMenu();
		}

		return ManagementToolbarDefaults.isShowCreationMenu(getCreationMenu());
	}

	return _showCreationMenu;
}
```

Please check if that fixes the issue, adding to this PR if it does.

**Review by markocikos — CHANGES_REQUESTED** [review]
Other than the issue in https://github.com/drewbrokke/liferay-portal/pull/1297#issuecomment-778300124, looks good!

**Comment by jonmak08** [comment]
Thanks @markocikos.  I will take a look and test it today.  I will keep you updated @drewbrokke.  Thanks everyone!

**Comment by jonmak08** [comment]
Pushed up the new changes to the taglib at https://github.com/drewbrokke/liferay-portal/pull/1297/commits/aac03f1b92b3ed320ee544809d756d5b19230903 and it works now.

See below:
account-admin-web

**Comment by jonmak08** [comment]
ci:test:sf

**Comment by jonmak08** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
Hey @jonmak08 , I think you somehow didn't push the `setShowCreationMenu(...)` deletion. In your gif toolbar behavior is correct, but with the PR as it is, the bug is still there:

screen

`setShowCreationMenu` acts to always set the value of `showCreationMenu`. As it is never `null`, we never check display context.

**Comment by markocikos** [comment]
@jonmak08 The changes in this PR are only on `account-admin-web` > ... > `account_users_admin`. There are more management  toolbars in `account_entries_admin` and `account_groups_admin`. Since there is already a decent amount of code in this PR, maybe it makes sense to merge this as it (after fix), and followup with another PR. Or we can update it all on this  PR. I'll leave it up to you and @drewbrokke to do whatever is more convenient. 

I noticed this because that was oddly no conflict with https://github.com/liferay-frontend/liferay-portal/pull/746. There will probably be a conflict at one point, so whenever one PR gets merged, the other will need to be updated. @kresimircoko

**Comment by jonmak08** [comment]
Let me close this PR and just send that bug fix for the taglib first.  I will then add all the changes.  I think I misread the JIRA ticket for the submodule `account_users_admin` instead of the entire module `account-admin-web`.

Sorry about all the confusion!

**Pull request closed without merging**
