### PR TITLE
LPS-88240

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-88240

CC @pei-jung

I believe [the issue described by Pei-jung](https://github.com/drewbrokke/liferay-portal/pull/688#issuecomment-446421269) is resolved by using the setBoolean() method when querying by privateLayout.  This is how existing upgrade processes query as well.

Let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:upgrade

**Comment by pei-jung** [comment]
@ChrisKian your changes look good. I was able to upgrade successfully without any errors.

PR submitted to https://github.com/brianchandotcom/liferay-portal/pull/65867. Thanks!

**Comment by pei-jung** [comment]
ci:close

**Pull request closed without merging**
