### PR TITLE
LPS-103703 Add email validation for Email Sender

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @katienesterovich

Notes from Katie:
> https://issues.liferay.com/browse/LPS-103703
> 
> Added front-end and server email validation.
> 
> Front-End Validation
> image
> 
> Server validation (invalid email resets to previously set email)
> Screen Shot 2019-11-05 at 3 16 22 PM

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
PR sent to https://github.com/brianchandotcom/liferay-portal/pull/81041

**Pull request closed without merging**
