### PR TITLE
LPS 158690 | Add support for es_AR, es_CO and es_MX

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LPS-158690
https://issues.liferay.com/browse/DESIGN-4253

@drewbrokke, Dave had me send this pull to you.  For some context, we have a Latin America UG who was looking to add a general version of Spanish.  But as there's no designated flag for "Latin America", we decided to split the request into the top three used dialects of Spanish (by number of speakers): Mexico (122m), Argentina (50m), Columbia (44m).  For [reference](https://en.wikipedia.org/wiki/Spanish_language), Spain Spanish is next in line, with around 43m speakers.

cc @david-truong

### CODE REVIEW

**Comment by brianwulbern** [comment]
ci:test:sf

**Comment by brianwulbern** [comment]
ci:test:sf

**Comment by brianwulbern** [comment]
Test failures mention "mx" in the URL, which I've added:
```  [exec]     LIFERAY_ERROR: Unable to register portal instance {"mvccVersion": 1, "companyId": 20097, "userId": 0, "userName": "", "createDate": "Wed Sep 14 03:46:30 GMT 2022", "modifiedDate": "Wed Sep 14 03:46:30 GMT 2022", "webId": "liferay.com", "mx": "liferay.com", "homeURL": "", "logoId": 0, "maxUsers": 0, "active": true, "name": "Liferay", "legalName": "", "legalId": "", "legalType": "", "sicCode": "", "tickerSymbol": "", "industry": "", "type": "", "size": ""}
     [exec]     Executing commands: curl -X GET -u 'test@liferay.com:test' -H 'Content-Type: application/json' http://localhost:8080/o/headless-portal-instances/v1.0/portal-instances```

Will retrigger to see if the Auto SF commit fixed the issue.

**Comment by brianwulbern** [comment]
ci:test:relevant

**Comment by brianwulbern** [comment]
Also sent to https://github.com/liferay-usm/liferay-portal/pull/742

**Comment by drewbrokke** [comment]
Closing in favor of https://github.com/liferay-usm/liferay-portal/pull/742

**Pull request closed without merging**
