### PR TITLE
Lps 101701

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @knchau

Notes from Kim:

> https://issues.liferay.com/browse/LPS-101701
> 
> Punctuation is missing in alert message.
> 
> I edited the message to include period and automatically built the languages -- needs to be translated.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
PR sent to https://github.com/brianchandotcom/liferay-portal/pull/79263

**Pull request closed without merging**
