### PR TITLE
LPS-91107 | Remove jQuery from the site modules

### PR DESCRIPTION
**Pull request by markocikos**
Hi Drew, <br><br>Please review the code.<br><br>Thank you!

### CODE REVIEW

**Comment by jbalsas** [comment]
I think Drew is out on paternity leave? @pei-jung, could you please pick this up?

**Comment by markocikos** [comment]
Please apply for https://github.com/drewbrokke/liferay-portal/pull/764 as well. Thank you!

**Comment by pei-jung** [comment]
Hi @jbalsas and @markocikos,

This one should go to @ealonso since they own the site modules. I'll take care of #764. Thanks!

**Comment by markocikos** [comment]
Rebased and resent, see https://github.com/ealonso/liferay-portal/pull/2240

**Pull request closed without merging**
