### PR TITLE
LPS-77366

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-77366

I've compiled and tested @peterpetrekanics changes and found they work smoothly.  Let me know if you have any questions.

### CODE REVIEW

**Comment by ChrisKian** [comment]
Relevant tests look unrelated: https://github.com/ChrisKian/liferay-portal/pull/74#issuecomment-447160050

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
@peterpetrekanics, there were some changes required by your fix, but I took care of them since I didn't catch them earlier.  Please double check and make sure everything makes sense.  I've recompiled and tested and found it works the same as before.

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
Hey @peterpetrekanics overall the fix seems fine, we need to tighten up a couple things:

1. I think that both the configuration and the bean declaration should be kept inside `portlet-configuration-web`.  Since this is the only usage, there's no reason to expose new API and bump the version number unless this configuration will be consumed by multiple modules. Since this is the only usage, we should just make everything internal to the portlet module for now.

2. I think we need to be more specific with name of the configuration method and its description.  Currently, there is no way to know what this configuration will do without looking at the code.  It has a very specific effect and should be clearly explained to the admin in the UI.

Will you please update and resend? Thanks!

cc @ChrisKian

**Comment by drewbrokke** [comment]
@peterpetrekanics checking to see if you saw my previous comment.

https://github.com/drewbrokke/liferay-portal/pull/693#issuecomment-449488519

**Comment by peterpetrekanics** [comment]
@drewbrokke yes thank you, I have received it - I did not forget about this pr, have been working on it over the past few days: just to be on the same page, could you please confirm:
I should just leave the whole roles-admin-api untouched, and I should do all of my changes in portlet-configuration-web, right?
I will send you a pull request soon to show you what I mean.

**Comment by peterpetrekanics** [comment]
@drewbrokke so let me show you what I meant, you can see my new repo here:
https://github.com/liferay/liferay-portal/compare/master...peterpetrekanics:LPS-77366_master_Create_config_admin_option_for_more_strict_permission_checks_on_roles
I have tested the build and it fixes the original issue, plus it is using the portlet-configuration-web just like you asked.
Could you please confirm that this is what you had in mind?
If so, I will create a more detailed explanation about this change and put it in the "Role Visibility" section within the System Settings, and then send you the new PR.
Many thanks!

**Comment by drewbrokke** [comment]
@peterpetrekanics that change looks good - now we don't have to worry about versioning and API changes until it's necessary.  However, I still think we need to make the description of the configuration more robust.

(from my original response):
>I think we need to be more specific with name of the configuration method and its description. Currently, there is no way to know what this configuration will do without looking at the code. It has a very specific effect and should be clearly explained to the admin in the UI.
 
Once we update that I think this will be good to go.  Thanks!

**Comment by peterpetrekanics** [comment]
I did not forget that you asked that the description of the configuration should be more robust.
That is why I wrote in my last comment:

> If so, I will create a more detailed explanation about this change

Thank you for reviewing my fix! I will start working on the text right now, so the admins will know what this change is all about. I will send you my suggestion soon!

**Comment by drewbrokke** [comment]
@peterpetrekanics my apologies, I missed that :) I'll look over the description you just posted and let you know.  Thanks!

**Comment by peterpetrekanics** [comment]
@drewbrokke No problem at all + I really appreciate your help with this issue!
Thank you!  I'll be waiting for your next message then

**Comment by drewbrokke** [comment]
@peterpetrekanics what do you think about this as an abridged description?

`Set this to true to hide roles that a user does not have permission to view while they are updating permissions for a resource via the "Permissions" popup window.`

**Comment by peterpetrekanics** [comment]
@drewbrokke wow that's really short and understandable. I like it!
So I should put it into this file:
modules/apps/portlet-configuration/portlet-configuration-web/src/main/resources/content/   Language.properties
like this, right?:
```
role-visibility-configuration-name=Role Visibility
role-visibility-enabled-description=Set this to true to hide roles that a user does not have permission to view while they are updating permissions for a resource via the "Permissions" popup window.
```

**Comment by drewbrokke** [comment]
Correct, that looks good.

The one other thing I would change is the method name.  In the context of `RoleVisibilityConfiguration`, the name `enabled` doesn't tell you much apart from the description we're providing.  A name like `restrictPermissionSelectorRoleVisibility` gives a concise idea of what's happening, even if you didn't read the description.

Thoughts?

**Comment by peterpetrekanics** [comment]
@drewbrokke I totally agree, I just copied that code part from another solution, so I am all for giving it a better name.
So if I understand correctly, I should change the RoleVisibilityConfiguration.java in my 2nd commit and for the "name" variable I should use "restrictPermissionSelectorRoleVisibility" like this:

```
...
public interface RoleVisibilityConfiguration {

	@Meta.AD(
		deflt = "false", description = "role-visibility-enabled-description",
		name = "restrictPermissionSelectorRoleVisibility", required = false
	)
	public boolean enabled();
}
```
Is this what you had in mind? Do I need to change this somewhere else in my code also?

**Comment by peterpetrekanics** [comment]
@drewbrokke Cool, thank you. I will try to send these changes in a new PR as soon as possible (probably tomorrow).  Do you have any other suggestions? It would be better for me to collect all the suggestions now and then I can send a more or less "final" pull request.

**Comment by drewbrokke** [comment]
I don't see anything else - thanks for being so flexible :)  If I see anything else I'll try to let you know ASAP.

**Comment by peterpetrekanics** [comment]
@drewbrokke I have tried to modify the code based on what we agreed - however, unfortunately the description of the configuration appeared on the page twice.
See: https://issues.liferay.com/secure/attachment/294334/duplicate_config_description_2019-01-11%2014-04-04.png
So I went back to my original idea to display the checkbox the same way we have it in the "Organization Links" section.
I will send you the new pull request soon

**Pull request closed without merging**
