### PR TITLE
LPS-62668 fix condition

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
@juliocamarero Looks like that did it.  Thanks a lot!  Pull request sent to brianchandotcom#35480

**Comment by juliocamarero** [comment]
:tada: :tada:

**Pull request closed without merging**
