### PR TITLE
LPS-196985 Update Webpack vertion to 5.76.0 to avoid vulnerability

### PR DESCRIPTION
**Pull request by Seiphon**

### CODE REVIEW

**Comment by Seiphon** [comment]
ci:test:sf

**Comment by Seiphon** [comment]
ci:test:relevant

**Comment by Seiphon** [comment]
ci:test:sf

**Comment by Seiphon** [comment]
ci:test:relevant

**Comment by Seiphon** [comment]
ci:test:relevant

**Review by drewbrokke — APPROVED** [review]
LGTM 👍

**Comment by drewbrokke** [comment]
ci:forward:force

**Review by drewbrokke — CHANGES_REQUESTED** [review]
@Seiphon I think we may need to regen the lock files for these modules as well. Can you please do that and re-send here? Thanks!

**Comment by Seiphon** [comment]
> @Seiphon I think we may need to regen the lock files for these modules as well. Can you please do that and re-send here? Thanks!

OK, will re-send the pr after regening the lock files

**Comment by Seiphon** [comment]
resent the pr here https://github.com/drewbrokke/liferay-portal/pull/1537

**Pull request closed without merging**
