### PR TITLE
LPS-125544 Add the "emailAddress" field to portal accounts

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-125544](https://issues.liferay.com/browse/LPS-125544).<br/><br/>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:upgrade

**Comment by drewbrokke** [comment]
@pei-jung will you please double-check my work? I want to make sure I didn't miss anything.

**Comment by pei-jung** [comment]
LGTM! 👍

**Comment by Sharryxue** [comment]
No specific issue found.
There are 2 outstanding issues as addressed in [LPS-125642](https://issues.liferay.com/browse/LPS-125642) and [LPS-119128](https://issues.liferay.com/browse/LPS-119128).
Seems the account related upgrade process is blocked by [LPS-125642](https://issues.liferay.com/browse/LPS-125642), refer [console](https://testray.liferay.com/reports/production/logs/test-1-17/1610138873076/test-portal-acceptance-pullrequest(master)/7069/functional-upgrade-tomcat90-mysql57-jdk8/0/22/jenkins-console.txt.gz).

**Comment by drewbrokke** [comment]
@patriciajeanperez would you be willing to forward this to Brian manually?

**Comment by patriciajeanperez** [comment]
Forwarded in https://github.com/brianchandotcom/liferay-portal/pull/97638

ci:close

**Comment by drewbrokke** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/97638

**Pull request closed without merging**
