### PR TITLE
[TS] LPS-92403

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-92403

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/70188.

**Pull request closed without merging**
