### PR TITLE
LPS-122879 Fix NPE

### PR DESCRIPTION
**Pull request by dantewang**
cc @tinatian

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
See https://github.com/drewbrokke/liferay-portal/pull/1221

**Comment by drewbrokke** [comment]
ci:reopen

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
