### PR TITLE
[TS] LPS-98420

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-98420

Hey Drew,

Your changes look good and work properly. The only issue I had was not being able to set any System settings [due to a NPE](https://gist.github.com/ChrisKian/a7c1c49c7ea1f5e3eaef54cad70fd013) which was unrelated to your changes.  However, manually running the _updateDefaultImportInterval() method with a new value works, so I think everything is in order.

I've also removed my initial commit and your reverting commit from this PR.  Let me know if there is anything else I can do.  Thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
PR sent to https://github.com/brianchandotcom/liferay-portal/pull/76205

**Pull request closed without merging**
