### PR TITLE
LPS-175159 Migrate feature flag reads to use the new API and fix SF logic to generate `feature.flag.xyz` in `portal-impl/src/portal.properties`

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
See https://github.com/liferay-usm/liferay-portal/pull/975

**Pull request closed without merging**
