### PR TITLE
[TS] LPS-98420

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-98420

Resent from https://github.com/drewbrokke/liferay-portal/pull/847.  See explanation there.

Differences between current and previous PR:
1. rebased
2. configurationPid added to Component annotation, so the activate() method is called if the configuration is modified.  This is important for the interval to be used instantly, rather than requiring a portal/module restart
3. Uses ConfigurableUtil.createConfigurable to retrieve configuration in activate method only.  This removes the need for a PortalUtil.getDefaultCompanyId() call and ensures the correct interval is used ([before it would use the last saved interval](https://issues.liferay.com/browse/LPP-34482?focusedCommentId=1905449&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1905449))

The biggest functional difference is now the last saved instance's configuration is used for the interval value, rather than the default company's interval.  I believe this is better, and hopefully you agree.  All other changes are definitely better (configuration instantly used, thread-safe, etc).

Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
PR sent to https://github.com/ChrisKian/liferay-portal/pull/148.

**Pull request closed without merging**
