### PR TITLE
LPS-121655 "My Dashboard" and "My Profile" links have no destination when properties *.layouts.power.user.required is true

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-121655](https://issues.liferay.com/browse/LPS-121655).

/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez @JavierMoral

### CODE REVIEW

**Comment by drewbrokke** [comment]
@patriciajeanperez do we have functional test coverage for the Personal Menu component? If so can we update the tests to account for the cases in this ticket?

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
Hi @drewbrokke! We do have test cases for Personal Menu but we need to update them to include this specific use case. I created a [ticket](https://issues.liferay.com/browse/LRQA-62245) for it and added it to our next sprint. Thanks!

**Comment by pei-jung** [comment]
Changes look good! 👍

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
