### PR TITLE
LPS-195564 Inject config path environment variables into all executable process tasks

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-195564](https://issues.liferay.com/browse/LPS-195564).

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
ci:stop

**Comment by drewbrokke** [comment]
ci:test:liferay-sample-workspace

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
ci:reevaluate:1277401_9963

**Comment by drewbrokke** [comment]
ci:stop

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
ci:test:liferay-sample-workspace

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Comment by drewbrokke** [comment]
ci:stop

**Comment by drewbrokke** [comment]
ci:test:gradle-plugins

**Comment by ling-alan-huang** [comment]
@drewbrokke We want to use the fix [here](https://github.com/ling-alan-huang/liferay-portal/pull/2121) instead.

**Comment by drewbrokke** [comment]
Thanks for the heads up @ling-alan-huang

**Pull request closed without merging**
