### PR TITLE
LPS-199149 Remove manual env variable setting from workspace build.gradle files

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-199149](https://issues.liferay.com/browse/LPS-199149).

@gamerson would you be willing to give this one a quick look? Thanks!

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:help

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by gamerson** [comment]
ci:test:liferay-sample-workspace

**Review by gamerson — APPROVED** [review]
Looks good as long as the tests pass.  Looks like one of the sample etc cron tests failed.  so as long as that passes this should be good to go.

**Comment by gamerson** [comment]
hold up, i'm not seeing something that I expected.

**Comment by gamerson** [comment]
See here: https://github.com/drewbrokke/liferay-portal/pull/1526
Go to `liferay-sample-etc-cron` and do `gradlew bootRun`

**Comment by gamerson** [comment]
re-running the tests over here: https://github.com/drewbrokke/liferay-portal/pull/1527

**Pull request closed without merging**
