### PR TITLE
LPS-115019 (dependency) adds xsd definition

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-115019](https://issues.liferay.com/browse/LPS-115019).<br><br>/cc @ngriffin7a @david-truong

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
re: https://github.com/drewbrokke/liferay-portal/pull/1136#issuecomment-670028185

@ngriffin7a @david-truong I believe it's just the one file, correct? Please let me know if I'm missing anything.

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
Semantic version issue is [fixed and merged](https://github.com/brianchandotcom/liferay-portal/commit/fb4429e356a07dbbdcc0edc49c06abdb61ad404b#diff-43a4010a2ee7c6fd2a3cd341afdad68dR988), will retrigger the relevant test.

**Comment by Sharryxue** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
Thanks @Sharryxue !

**Pull request closed without merging**
