### PR TITLE
LPS-67524

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by daledotshan** [comment]
Hey Drew,
Could you help to review this pull request as high priority? it is for a ee customer.

Thanks,
Dale

**Comment by drewbrokke** [comment]
Yes, I will review it tomorrow.

--
Drew Brokke
Software Engineer
Liferay, Inc.

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
Pull request sent to brianchandotcom#42443 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
