### PR TITLE
LPS-171225 Automatically register ConfigurationVisibilityControllers for each Feature Flag defined in the portal.properties

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-171225](https://issues.liferay.com/browse/LPS-171225).

FYI @ethib137

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:stable

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
See https://github.com/liferay-peds/liferay-portal/pull/150

**Pull request closed without merging**
