### PR TITLE
LPS-125698 Bridge CommerceAccountUserRel service to AccountEntryUserRel service

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-125698](https://issues.liferay.com/browse/LPS-125698).

cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez @marco-leo

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:upgrade

**Comment by drewbrokke** [comment]
ci:test:accounts

**Comment by drewbrokke** [comment]
ci:test:commerce

**Comment by drewbrokke** [comment]
@patriciajeanperez are the upgrade and commerce suite failures unique? Or am I good to forward this one?

**Comment by patriciajeanperez** [comment]
Hi @drewbrokke! Yeah, looks like all failures are not related. I can go ahead and forward.

ci:forward

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
