### PR TITLE
[TS]LPS-85170 can't create Virtual Instances when there are legacy portlets that use non-system roles in security-role-ref

### PR DESCRIPTION
**Pull request by NorbertKocsis**
https://issues.liferay.com/browse/LPS-85170

Related PTR: https://issues.liferay.com/browse/PTR-414

### CODE REVIEW

**Comment by NorbertKocsis** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
Test PR sent to https://github.com/drewbrokke/liferay-portal/pull/737.

**Comment by drewbrokke** [comment]
PR sent to https://github.com/brianchandotcom/liferay-portal/pull/67689

**Pull request closed without merging**
