### PR TITLE
LPS-118750 Remove portal accounts from 7.3 CE and DXP bundles

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-118750](https://issues.liferay.com/browse/LPS-118750).

cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez @jpince

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
[RolesAdminPortletDataHandlerTest.testPrepareManifestSummary](https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=3,label_exp=!master/385090//testReport/com.liferay.roles.admin.internal.exportimport.data.handler.test/RolesAdminPortletDataHandlerTest/testPrepareManifestSummary) Seems related, @drewbrokke would you please double check?
Unrelated failure [ModulesStructureTest.testScanBuildScripts](https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/420892//testReport/com.liferay.portal.modules/ModulesStructureTest/testScanBuildScripts) is addressed is unrelated. in LPS-119347, and should be fixed by [commit](https://github.com/brianchandotcom/liferay-portal/pull/92880).

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
