### PR TITLE
LPS-90317 Unable to add Regular Roles to users

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @stsquared99 @ChrisKian @wanderlast

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
PR sent to https://github.com/pei-jung/liferay-portal/pull/343

**Pull request closed without merging**
