### PR TITLE
[TS] LPS-99576

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-99576

This ticket is mostly logging, but it does contain one small fix (not yet encountered by anyone afaik).  It's minimal, so I lumped it in with the current LPS, rather than creating a new one.

I'm sending this to Drew since the logging/configuration side belongs to him.  However, I'll CC @lipusz to let him know we are in the LDAP component and about the [small bug fix](https://github.com/drewbrokke/liferay-portal/commit/6a67f527eeed27df8960c0902556f9d95786e4c4) included.  Unless it's intended for one instance to completely halt LDAP import if it's import interval value is less than 1, this fix should be included.

Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by ChrisKian** [comment]
Test failure is unrelated, see https://github.com/moltam89/liferay-portal/pull/525#issuecomment-520046659 for identical error.

**Comment by drewbrokke** [comment]
PR sent to https://github.com/brianchandotcom/liferay-portal/pull/76826

**Pull request closed without merging**
