### PR TITLE
[TS] LPS-105757

### PR DESCRIPTION
**Pull request by ChrisKian**
CC @jesseyeh-liferay 

Hey Drew, the changes look good to me, so I've squashed the commits.  Let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
PR sent to https://github.com/brianchandotcom/liferay-portal/pull/83024

**Pull request closed without merging**
