### PR TITLE
LPS-107151 As a site admin, I want to assign site roles to site-level segments

### PR DESCRIPTION
**Pull request by darquesdev**
Hi @drewbrokke ,I've added some changes. Normally we prefer to make the assertions explicit within each test. Apart from this, everything seems to be correct. Go ahead and and forward it to Brian if you consider It's ok. Thank you!

@cgoncas

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
@patriciajeanperez is the functional test failure unique to this pull?

**Comment by drewbrokke** [comment]
Forward candidate pull: https://github.com/drewbrokke/liferay-portal/pull/1013

**Comment by drewbrokke** [comment]
@patriciajeanperez I ran the failing functional test locally and it passed, so I'm gonna try forwarding the pull in the comment in case it is just flaky.

**Comment by patriciajeanperez** [comment]
Sorry for the delay, @drewbrokke! You're right, it's a flaky test. It's ignored as of now. Thanks!

**Comment by drewbrokke** [comment]
Thanks @patriciajeanperez !

**Pull request closed without merging**
