### PR TITLE
LPS-61779

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by lipusz** [comment]
Hi @drewbrokke 

I'd like to ask you to proceed with the review once you have the time.

Thx,
Tibor

**Comment by drewbrokke** [comment]
Hey Tibor, thanks for the prompt.  I'll go ahead and take care of it today.

--
Drew Brokke
Software Engineer
Liferay, Inc.

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by lipusz** [comment]
https://github.com/JorgeFerrer/liferay-portalpull/631

**Pull request closed without merging**
