### PR TITLE
[TECHNICAL-SUPPORT] LPS-76667

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @wanderlast

Notes from Lianne:

> LPP: https://issues.liferay.com/browse/LPP-28076
> LPS: https://issues.liferay.com/browse/LPS-76667
> 
> Summary:
> This is a regression bug caused by [LPS-64261](https://issues.liferay.com/browse/LPS-64261) where manually adding membership of another organization to an organization site does not properly grant view/access permissions to the users in that organization. User groups are found in "populateUnionParams" where params3 corresponds with "groupsOrgs" or groups linked to organizations. Therefore the fix is to have it check both the groupClassNameId and OrganizationClassNameId to not miss groups granted to the user by any organizations they are members of.
> 
> If you have any questions, please let me know. Thanks!

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test

**Comment by SamZiemer** [comment]
ci:test

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
PR sent to https://github.com/brianchandotcom/liferay-portal/pull/54082. Thanks!

**Pull request closed without merging**
