### PR TITLE
LPS-121998 Add new service Impl methods to account for the new fields

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-121998](https://issues.liferay.com/browse/LPS-121998).

@brianchandotcom this is the follow-up pull you requested here: https://github.com/brianchandotcom/liferay-portal/pull/96786#issuecomment-742259143

/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:upgrade

**Comment by drewbrokke** [comment]
ci:help

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:upgrade

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:help

**Comment by drewbrokke** [comment]
ci:help

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
Re-trigger the relavent test since the previous seems hang up.

**Comment by Sharryxue** [comment]
ci:test:upgrade

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:upgrade

**Comment by drewbrokke** [comment]
ci:stop

**Comment by drewbrokke** [comment]
ci:close

**Comment by drewbrokke** [comment]
Closing to include the fix for https://issues.liferay.com/browse/LPS-124842

**Comment by drewbrokke** [comment]
See https://github.com/drewbrokke/liferay-portal/pull/1271

**Pull request closed without merging**
