### PR TITLE
LPS-95705 Allow non admin user to use Analytics Cloud in DXP

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-95705](https://issues.liferay.com/browse/LPS-95705).

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Hey @jpince, can you help me identify the reason for this failure? It [happened on my last pull](https://github.com/drewbrokke/liferay-portal/pull/835#issuecomment-499730485) as well, but I don't have enough info to see what aspect of my changes causes this failure.

**Comment by jpince** [comment]
@drewbrokke there are all kinds of startup errors. They're probably overfilling the logs in such a way that CI can't handle, which is why you're seeing the weird output. I'll ask them to investigate.

Here are some errors I gleaned from the log that are probably yours, there are others that aren't in upstream (to my knowledge)
```
     [exec] 22:04:44,692 ERROR [main][PortalInstances:264] com.liferay.portal.kernel.exception.NoSuchRoleException: No Role exists with the key {companyId=20101, name=Guest}
     [exec] com.liferay.portal.kernel.exception.NoSuchRoleException: No Role exists with the key {companyId=20101, name=Guest}
     [exec] 	at com.liferay.portal.service.persistence.impl.RolePersistenceImpl.findByC_N(RolePersistenceImpl.java:5741)
     [exec] 	at com.liferay.portal.service.impl.RoleLocalServiceImpl.loadGetRole(RoleLocalServiceImpl.java:1247)
```
```
     [exec] 10-Jun-2019 22:05:57.178 SEVERE [http-nio-8080-exec-1] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [Friendly URL Servlet - Public] in context with path [] threw exception [com.liferay.portal.kernel.exception.NoSuchGroupException: No Group exists with the key {companyId=0, groupKey=Guest}] with root cause
     [exec]  com.liferay.portal.kernel.exception.NoSuchGroupException: No Group exists with the key {companyId=0, groupKey=Guest}
     [exec] 	at com.liferay.portal.service.persistence.impl.GroupPersistenceImpl.findByC_GK(GroupPersistenceImpl.java:3320)
     [exec] 	at com.liferay.portal.service.impl.GroupLocalServiceImpl.loadGetGroup(GroupLocalServiceImpl.java:2488)
```
It also looks like there's a NPE, not sure if it's unique from the other two:
```
     [exec] 22:05:58,221 ERROR [http-nio-8080-exec-1][TextHTMLPortalErrorCodeJSPDynamicInclude:47] Unable to include JSP /dynamic_include/text_html.jsp
     [exec] org.apache.jasper.JasperException: java.lang.NullPointerException
...
     [exec] Caused by: java.lang.NullPointerException
     [exec] 	at com.liferay.portal.util.PortalImpl.getRelativeHomeURL(PortalImpl.java:4809)
     [exec] 	at com.liferay.portal.kernel.util.PortalUtil.getRelativeHomeURL(PortalUtil.java:1636)
```

The log is huge, will probably take a long time to load remotely. I tried putting it in a gist for you, but github yelled at me :flushed: You can also ci:test:bundle and CI will make one for you in about 30-40 min. 
https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/301159/consoleFull

Loop reference for ci:test:bundle as an fyi. There's more documentation somewhere, lmk if you need it. https://loop.liferay.com/home/-/loop/feed/17973576

**Pull request closed without merging**
