### PR TITLE
LPS-74152 proposal for improved configuration scope supports

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
Hi Drew. I started looking at [LPS-72142](https://issues.liferay.com/browse/LPS-72142) which Jorge suggested we should collaborate on, and concluded that there is an underlying issue here which is that we are requiring the use of factory configurations in order to support configuration at different scopes. It would be nice if factory configurations were reserved for when the client needs to retrieve multiple instances of configuration.

So I've been exploring an alternative approach for your consideration. The approach is to support a series of derived & unique PID formats (representing scopes) for PIDs referenced in any metatype visible to the Settings Framework.

I didn't get as far as extending the System Settings UI but it is possible to deploy configurations via config files using a pre-determined filename. This is unlike our current approach where the filename does not incorporate a scope instance identifier, and consequently there could be multiple configuration instances for companyId=12345, for example.

Try deploying configuration files named:

- {pid}\_COMPANY_{companyId}.config
- {pid}\_GROUP_{groupId}.config
- {pid}\_PORTLET_INSTANCE_{portletId}.config

The portlet instance scope works, however I am unsure if it should be supported as PortletPreferences already provides sufficient/better support, maybe.

Shortcomings:

- Scoping support for factory configurations are not implemented yet
- Configurations take precedence over PortletPreferences at all scopes, which means when making configuration changes via Portlet configuration (etc.) those do not take effect when there is also a configuration. Essentially the relationship between PortletPreferences and Configuration beans needs to be better defined.
- Need to pre-load all current configurations upon component activation since the ConfigurationListener only receives change events

/cc @jorgeferrer

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:reopen

**Comment by JorgeFerrer** [comment]
Thanks for working on this Stian!

I'm going to try to take a look at it during next week, although I'm on vacation so I can't promise it 100% ;)

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by stian-sigvartsen** [comment]
No problem, I hope it will be useful.
@mhan810 is looking for something like this to apply for the SSO configurations, so we could test it using one of those maybe.

Enjoy your holiday :)

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
@stian-sigvartsen @JorgeFerrer Forgive me for my ignorance on this issue, but what are the limitations that prevent us from using ConfigurationAdmin factory instances for this purpose?  Can we not build a framework around this feature that would accomplish the same thing?

**Comment by drewbrokke** [comment]
To be clear, I'm not against this approach (I like the solution, actually), but I just want to understand more clearly why leveraging the built-in APIs is not an option.

**Comment by stian-sigvartsen** [comment]
Hi @drewbrokke , thanks for reviewing the code!

> what are the limitations that prevent us from using ConfigurationAdmin factory instances for this purpose?

Wrapping the ConfigAdmin API for our scoping needs might also be a viable approach. But I think this then would mean that **all** our configurations would need to be factories so that **any** configuration can be scoped (I think this is desirable).

This then means factory=true would need to be set on all metatypes, or added dynamically at runtime somehow. The key objective for me was to avoid the former. Meaning an app can be developed without thought to the target portal environment (single instance / multi instance installation). More generally, scoping configuration is an admin's concern, not a developer's concern.

Another key benefit of my approach was that the derived PIDs encode the company ID (etc.) into them (unlike factory PIDs). So it is literally impossible to create two configurations for the same PID for the same scope. Though maybe the same can be achieved if we modify/replace the Felix fileInstaller?

> What would prevent us from wrapping this functionality specifically for our scoping needs in order to prevent misuse?
> Why would it preclude customers from also using factories how they would like to?

It's difficult to define "how they would like to", but I believe that we are trying to expose/encourage use core OSGi APIs as much as possible, and allow these to function as the specs intended.

For example, sometimes developers might want to create a @Component referencing a factory configuration, causing the OSGi runtime to instantiate a service per factory configuration instance. i.e. just core DS / OSGi stuff, where the only scope is "system". With the wrapping approach you would get all configuration instances for all scopes reflected as services. Meaning the complexity handling shifts to other components making @Reference to them since they will need to filter the services by companyId, groupId etc. At that stage it feels like our platform is interfering with this standard OSGi mechanisms.

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
Hey @stian-sigvartsen, we have written up some thoughts regarding this proposal, and would like your feedback.  I have written a gist here: https://gist.github.com/drewbrokke/20f305b7eb25b7ae84a22071680b9686

**Comment by drewbrokke** [comment]
Hey @stian-sigvartsen, is the goal for this to simply provide support for scoped configuration files, or do we want to support an entire developer API built around this?  So far I've been thinking about this as a developer API, but as I re-read your comment:

> scoping configuration is an admin's concern, not a developer's concern

I realized I might be over-thinking it.  In your mind, what would the scope of the API for this be?

**Comment by stian-sigvartsen** [comment]
Hey @drewbrokke . What I would prefer is if the company scope did not manifest in any developer API and was instead "injected" (ThreadLocal?) such that when a developer makes a call for configuration it will return either the system one or company scope if configured. The client code should not be able to tell which. This then means all apps work in a multi-tenenacy environment, by default.

There might be some cases when you want to retrieve configuration for other company instances but these are admin / edge cases and might justify a dedicated API.

Other finer grain scopes I think makes sense to feature in the main developer API.

p.s. Sorry I haven't been able to review your other feedback yet, hope to do it before week end.

**Comment by drewbrokke** [comment]
Thanks for getting back to me, @stian-sigvartsen.  @pei-jung and I are trying to grasp the use-case you have in mind.  It seems counter-intuitive to us that the developer should not be concerned about scope.  Maybe it would help us to understand how the developer has asked for the configuration.  

If they are using the ConfigurationProviderUtil, they are using any one of a number of methods that are explicitly asking for configurations at a given scope.  On the other hand, configurations are also obtained directly through the ConfigurableUtil inside of @Activate and @Modified methods. In those cases, it's always going to be System Scoped since it's dependent on matching a pid from the framework.

In either case, I don't see the opportunity to automatically inject a scoping.  Sorry if I'm missing it, I just want to make sure that I understand what the big picture is.  Perhaps a specific use-case could help?

cc @jorgeferrer

**Comment by stian-sigvartsen** [comment]
>  It seems counter-intuitive to us that the developer should not be concerned about scope.

I guess to me asking for the configuration of a specific company, or system, is a bit like asking for the state of a particular node in a Liferay cluster. Clustering is a platform feature that does not add complexity for the developer (except highlighting unavoidable behaviours like CAP theorem).

The approach with ThreadLocal is already implemented for the SAML plugin:
https://github.com/liferay/liferay-portal-ee/blob/7.0.x-private/modules/private/apps/saml/saml-impl/src/main/java/com/liferay/saml/runtime/internal/configuration/SamlProviderConfigurationHelperImpl.java#L86

I'm not advocating this implementation approach necessarily, I just like the API where you don't specify companyId.

> On the other hand, configurations are also obtained directly through the ConfigurableUtil inside of @Activate and @Modified methods. In those cases, it's always going to be System Scoped since it's dependent on matching a pid from the framework.

Yes we can't do much about this and in a way I like that it is system scoped always. This is according to OSGi and will be expected. I say that because I find numerous times (including above linked example) when a component is interacting with multiple configurations via ConfigurationProvider, and these are different configurations to the one referenced by the Pid of the component.

To me it's a bit like the MVC paradigm, the component with its system scoped configuration is the View, and the ConfigurationProvider is the various Models it interacts with.

**Comment by drewbrokke** [comment]
Pull request sent to https://github.com/pei-jung/liferay-portal/pull/220. Thanks! <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
