### PR TITLE
[TS] LPS-117307

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-117307

Hey Drew,
This issue stems off from [PTR-1838](https://issues.liferay.com/browse/PTR-1838), which I determined may make the portal more secure if fixed.  See [my comment](https://issues.liferay.com/browse/PTR-1838?focusedCommentId=2202257&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2202257) for context.

Please let me know if you have any questions, thanks!

CCing @lipusz since this issue deals with permissioning.

CC @hudakl

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
Seems the CI is hang up, will retrigger the test.

**Comment by Sharryxue** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
The failed job not related the commits here, issue is addressed in [LRCI-1431](https://issues.liferay.com/browse/LRCI-1431).

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
@ChrisKian this seems fine to me. If @lipusz signs off as well then we can forward.

**Comment by lipusz** [comment]
Hello @drewbrokke  @hudakl ,

I was not sure so I spoke to Tomas and Carlos about this. Here are Tomas' thoughts:

> I believe the logic there is sufficient to fix the reported issue.

> Thinking about the logic in general, I believe the code is wrong.

> Right now it's not possible to assign/remove these permissions on USER and GUEST roles:
```
resourceActions.remove(ActionKeys.ASSIGN_MEMBERS);
resourceActions.remove(ActionKeys.DEFINE_PERMISSIONS);
resourceActions.remove(ActionKeys.DELETE);
resourceActions.remove(ActionKeys.PERMISSIONS);
resourceActions.remove(ActionKeys.UPDATE);
resourceActions.remove(ActionKeys.VIEW);
```

> I believe only those permission don't make sense for USER and GUEST and should be removed:
```
resourceActions.remove(ActionKeys.ASSIGN_MEMBERS);
resourceActions.remove(ActionKeys.DELETE);
resourceActions.remove(ActionKeys.UPDATE);
```

> These do make sense to assign/change:
```
ActionKeys.DEFINE_PERMISSIONS ... who can define permissions for USER/GUEST role
ActionKeys.PERMISSIONS ... who can change permissions of USER/GUEST role
ActionKeys.VIEW ... who can see USER/GUEST role
```

Regards,
Tibor

**Comment by drewbrokke** [comment]
@ChrisKian see Tibor's summary above. I'm ok with also allowing the other two actions as well (DEFINE_PERMISSIONS and PERMISSIONS) if it is seems good to you. If so, go ahead and add that in a new commit and force-push so we can retest.

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
