### PR TITLE
LPS-72585

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@drewbrokke please review this pull, it came to me from https://github.com/brianchandotcom/liferay-portal/pull/61444

**Comment by drewbrokke** [comment]
@brianchandotcom got it, will do.

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
@stian-sigvartsen @martamedio I'm not sure this is the correct approach.  From what I can tell this is not a bug, and this UI pattern of multiple errors will be visible anywhere that both backend errors are displayed along with JS form validation.  We would have to make this change in many more places.

Closing for now so we can verify with design what changes are necessary.

**Pull request closed without merging**
