### PR TITLE
LPS-70258 There's no policy for displaying organization's logo

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-70258](https://issues.liferay.com/browse/LPS-70258).

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@topolik this is the change we discussed in our DM

**Comment by Sharryxue** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
ci:test:relevant

**Pull request closed without merging**
