### PR TITLE
LPS-112687 Search accounts by organizations

### PR DESCRIPTION
**Pull request by pei-jung**
Hey Drew,

Can you review my work? If everything looks good please forward to Brian. Thanks\!

/cc @alee88888

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
LGTM 👍

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
