### PR TITLE
[TS] LPS-130653

### PR DESCRIPTION
**Pull request by jonathanmccann**
The issue is that the ID for the menu is generated by the tag here - https://github.com/liferay/liferay-portal/blob/master/util-taglib/src/com/liferay/taglib/ui/IconMenuTag.java#L134-L135

This results in two IDs being the same due to special characters. The change utilizes the `userId` instead of the `screenName` to guarantee uniqueness.

Other places use rowIdProperty="screenName" but as far as I can tell they do not lead into a `liferay-ui:icon-menu` so they do not seem to be affected by this issue. If you'd like to change all of them though I have no issues with that either.

Please let me know if there are any questions or concerns.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:help

**Comment by drewbrokke** [comment]
ci:test:usrm

**Comment by drewbrokke** [comment]
ci:test:usm

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
ci:stop

**Comment by Sharryxue** [comment]
The semantic-versioning issue seems resolved at upstream, the rest failure more like related the semantic-versioning issue, will retry the relevant test.

**Comment by Sharryxue** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
