### PR TITLE
LPS-196998 Upgrade Maven version to 3.8.1 to avoid vulnerability

### PR DESCRIPTION
**Pull request by Seiphon**

### CODE REVIEW

**Comment by Seiphon** [comment]
ci:test:sf

**Comment by Seiphon** [comment]
ci:test:relevant

**Comment by Seiphon** [comment]
ci:test:relevant

**Comment by Seiphon** [comment]
ci:test:sf

**Comment by Seiphon** [comment]
ci:test:relevant

**Review by drewbrokke — APPROVED** [review]
LGTM 👍 Thanks @Seiphon!

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
@Seiphon looks like a merge conflict. Can you please rebase and re-send? Thanks!

**Comment by drewbrokke** [comment]
@Seiphon any update on the re-send of this pull request?

**Pull request closed without merging**
