### PR TITLE
LPS-197106 Add baseDirName for git when get top level

### PR DESCRIPTION
**Pull request by Seiphon**
Hi @drewbrokke ,  when I debug SF code and give a specific BaseDirName, I always get a wrong git top level dir. I found if I give the 'baseDirName' value to git method, it can be fixed. is that  a bug?

### CODE REVIEW

**Review by drewbrokke — COMMENTED** [review]
Hey @Seiphon, can you give some details (here or on the ticket) about the expected behavior vs. actual behavior and the steps you used to reproduce the issue?

**Review by drewbrokke — APPROVED** [review]
LGTM 👍 Thanks for your patience @Seiphon!

**Comment by drewbrokke** [comment]
ci:forward

**Comment by Seiphon** [comment]
There are some SF issues, let me rebase it to master, the issues should be fixed on master

**Comment by Seiphon** [comment]
ci:foward

**Comment by Seiphon** [comment]
ci:forward

**Comment by drewbrokke** [comment]
ci:forward:force

**Pull request closed without merging**
