### PR TITLE
[TS] LPS-130220

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-130220

From @ericyanLr 

> **Context**
> The main issue has to do with the Permission Filter that was introduced by [LPS-107527](https://issues.liferay.com/browse/LPS-107527).
> 
> From my understanding, the main goal of that fix was to make sure Site Administrators would be able to view all users, which is needed for a Site Administrator to assign a user to a site.
> 
> However, the Permission Filter is quite broad and is being applied to many search scenarios. And for our particular ticket, it's being applied to the Users and Organizations page, which is being viewed by a non group admin.
> 
> **Proposed Fix**
> The proposed fix simplifies the Permission Filter and limits it to only be applied for:
> - User models
> - When the requesting user is group admin
> 
> To determine whether the user is group admin, I used ServiceContextThreadLocal to provide the group id.
> 
> From my testing, when navigating to:
> - People > Memberships > Assign Users
> - Users and Organizations
> 
> The ServiceContextThreadLocal provided the expected groupId from the requested pages.
> - Executes logic when navigating to **People > Memberships > Assign Users** as a Site Administrator
> - Does not execute logic when navigating to **Users and organizations** (user does not have group Admin privileges for this page as just a Site Administrator - different groupId)
> 
> If you have any questions, feel free to let me know.
> Thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
The semantic-versioning-jdk8/0 probably fixed by [commit](https://github.com/brianchandotcom/liferay-portal/commit/e8f70891e1722ab70571de3424daf1f80ede0937), retriger the relevant test.

**Review by drewbrokke — APPROVED** [review]
LGTM 👍

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
