### PR TITLE
[Bug] LPS-124277

### PR DESCRIPTION
**Pull request by yuhai**
Hi @drewbrokke, 

I am working on LPS-83768 and it is blocked by LPS-124277. Could you please help check this when you have free time?

cc @dantewang

Thanks,
Hai

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:upgrade

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:upgrade

**Comment by patriciajeanperez** [comment]
Hi @yuhai, still seeing the following errors in PostgreSQL 11: 

`20:17:40,827 ERROR [main][MainServlet:299] java.lang.RuntimeException: You must first upgrade the portal to the required schema version 10.0.0
java.lang.RuntimeException: You must first upgrade the portal to the required schema version 10.0.0`

**Comment by yuhai** [comment]
Hi @patriciajeanperez, the error should be unrelated with the fix. I will rerun ci:test:upgrade.

**Comment by yuhai** [comment]
ci:test:upgrade

**Comment by patriciajeanperez** [comment]
hi @yuhai, some of the upgrades tests didn't run because the same errors LPS-124277 are still present in PostgreSQL:

{code}
20:17:40,827 ERROR [main][MainServlet:299] java.lang.RuntimeException: You must first upgrade the portal to the required schema version 10.0.0 java.lang.RuntimeException: You must first upgrade the portal to the required schema version 10.0.0
{code}

Please see [liferay log](https://testray.liferay.com/reports/production/logs/test-1-5/1607008300328/test-portal-acceptance-pullrequest%28master%29/7432/functional-upgrade-tomcat90-postgresql11-jdk8/0/0/liferay-log.txt.gz)

**Comment by yuhai** [comment]
ci:test:upgrade

**Comment by yuhai** [comment]
Hi @patriciajeanperez, thanks for the info. For the error log, I think if the upgrade failed, and then start portal, it may cause the error "You must first upgrade the portal to the required schema version 10.0.0". If not, they also should belong to the different issues.

**Comment by Sharryxue** [comment]
Hello @yuhai,
The _v7_4_x.UpgradeRegion_ process still fails while upgrading, but with a new error message as below. Would you please take a look into the issue again? Thanks in advance. The new issue only reproducible on tests running with PostgreSQL 11, refer [full logs](https://testray.liferay.com/reports/production/logs/test-1-12/1607401027508/test-portal-acceptance-pullrequest(master)/3935/functional-upgrade-tomcat90-postgresql11-jdk8/3/14/jenkins-console.txt.gz).
```
     [java] com.liferay.portal.kernel.upgrade.UpgradeException: com.liferay.portal.kernel.upgrade.UpgradeException: org.postgresql.util.PSQLException: ERROR: operator does not exist: boolean = integer
     [java]   Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
```
/cc @patriciajeanperez @drewbrokke

**Comment by drewbrokke** [comment]
@yuhai we should be using the `SQLTransformer.transform` method for the upgrade processes. This was my mistake originally. Search for usages of `SQLTransformer.transform` in `*Upgrade*.java` classes, there should be plenty of examples.

**Comment by drewbrokke** [comment]
See https://github.com/drewbrokke/liferay-portal/pull/1253

**Comment by drewbrokke** [comment]
@yuhai I went ahead and made the changes since this is a blocker for you.

**Comment by yuhai** [comment]
@drewbrokke, thanks.

**Pull request closed without merging**
