### PR TITLE
LPS-69521

### PR DESCRIPTION
**Pull request by jonathanmccann**
Hey @drewbrokke,

This issue stems from two different beliefs between Felix and Liferay:

Felix thinks that if there is a PID attached to a configuration, then it must have a filename associated with it. Otherwise, it will create a new configuration using the filename and a random PID.

Liferay allows the user to modify configurations via the UI, creating a configuration with a specific PID. When exported, the configuration file contains this PID and we expect it to overwrite the configuration already in the database. Since Felix does not match up with this belief, it creates a new configuration in the database, which causes a number of problems.

This fix patches Felix to first check the database to see if a configuration already exists using the PID. If it's found, it's simply returned and a new configuration is not made. If it cannot find any configuration then a new one is added.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
Hey @jonathanmccann, it looks like there are some build errors for this pull.  I wasn't able to compile locally either.  Can you see if you can find a fix?

**Comment by jonathanmccann** [comment]
Seems like there is an issue with finding the new Fileinstall JAR. I'll look into how to force that to work without having to manually pull it down.

**Comment by jonathanmccann** [comment]
https://github.com/drewbrokke/liferay-portal/pull/260

**Pull request closed without merging**
