### PR TITLE
LPS-186113 Fix panel-app template to be compatible with U77+

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-186113](https://issues.liferay.com/browse/LPS-186113).

@simonjhy will you please look this one over? I spoke with Greg, and he mentioned that it is probably not necessary to check more than just the minor version of Liferay.

/cc @gamerson

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:project-templates

**Comment by simonjhy** [comment]
@drewbrokke  I checked the source code BasePanelApp for portal-7.4-ga72 and portal-7.4-ga77+, this solution is ok for 7.4 product. The changes of BasePanelApp is that Core team remove setPortlet method from U75+.

**Comment by drewbrokke** [comment]
Ok thanks @simonjhy! Are you ok if I forward this to Brian?

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
@simonjhy I'm gonna forward this one, but we can send follow-ups if you see any more issues. Thanks!

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
ci:stop

**Pull request closed without merging**
