### PR TITLE
LPS-82611 | master

### PR DESCRIPTION
**Pull request by Sharryxue**
https://issues.liferay.com/browse/LPS-82611

Hello @drewbrokke,
I made a mini change in this issue to fix the missing asterisk next to Email address in Contacts Center portlet, not sure if you can help with reviewing the issue? Thanks in advance.
What's more, it seems the validator will not work when adding it in both aui and hints file, like here, we have _<validator name="required" />_ in file portlet-model-hints.xml and _type="email"_ in file edit_entry.jsp.

### CODE REVIEW

**Comment by Sharryxue** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
PR sent to https://github.com/brianchandotcom/liferay-portal/pull/81315

**Pull request closed without merging**
