### PR TITLE
[TS] LPS-116317

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-116317

From @kevhlee:
 
> The issue is that when the save button is pressed, the POST request is made without redirect URL parameter, which results in the back arrow and cancel buttons lacking back URLs and no longer functioning. To resolve this issue, I first pass the redirect URL as input to the edit page's form. After that, I make sure that default redirect and back URLs are created when the input redirect and back URLs are null/blank. I also modify the redirect URL so that the portal would redirect the user back to the organization's edit page rather than the "view organizations" page.
> 
> With regards,
> Kevin

CC @wanderlast

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
Hello @ChrisKian, The failed tests is unique failures to this pull. Would you please take a look into the changes when available? Thanks.
**Steps to reproduce the failure**: 
1. Add an Organization,
2. after save, 
3. the page returns to the Organization list, instead of the Organization Information page. 

If this is an expected result, we will update our POSHI tests after this is merged.
/cc @drewbrokke

**Comment by kevhlee** [comment]
Hi @ChrisKian , @drewbrokke , @Sharryxue ,

I worked on these changes. This PR can be closed as I have made revisions to these changes and plan on sending a new PR.

**Pull request closed without merging**
