### PR TITLE
LPS-76223 As a developer I would like to have an API to save/delete scoped configuration

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test

**Comment by pei-jung** [comment]
ci:reopen

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
Test PR sent to https://github.com/drewbrokke/liferay-portal/pull/438 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
