### PR TITLE
LPS-179576 Feature flag test rule

### PR DESCRIPTION
**Pull request by 4lejandrito**
Adds `FeatureFlags` test annotation to simplify feature flags management. Works at class and method level.

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:stop

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
See https://github.com/drewbrokke/liferay-portal/pull/1407

**Pull request closed without merging**
