### PR TITLE
[TECHNICAL-SUPPORT] LPS-73348 Resource Block warning

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Preston-Crary** [comment]
Looks like this breaks some QA functional tests.  It looks like it's not expecting the new popup confirmation.

@michaelhashimoto who would be a good person to send this through to update the QA tests?

**Comment by drewbrokke** [comment]
I would send to Albert Lee or Brian Lee
  

  
  

  
  
>

**Comment by joshuacords** [comment]
@Preston-Crary the changes to ResourceBlocks shouldn't affect the functionality of Blogs, Webcontent, or Documents&Media. Earlier in review process some of these tests failed, but it was because I wasn't handling empty arrays properly in the edit_role_permssions.updateActions() method. After I fixed that the tests passed.

**Comment by Preston-Crary** [comment]
@joshuacords we're not saying your code is broken, just the functional tests need to be updated.  Unless you look through the entire test case you can't know what needs to be updated or not.

**Comment by michaelhashimoto** [comment]
@drewbrokke @Preston-Crary - Albert said you guys can send him a pull request with these changes and his team can look into updating the tests accordingly.

cc' @alee8888

**Comment by ksuetani** [comment]
After reviewing the failing functional tests, the cause is the small popup with the message "Changing these permissions will overwrite all permissions of that type previously configured on this entity." Any amount of permissions on a page can be added or removed without the popup appearing, unless all permissions in a section are selected or deselected. Is there any way to make the behavior more consistent?

**Comment by ksuetani** [comment]
@joshuacords 
**Steps to reproduce**
1. Navigate to Roles
2. Select Power User (or create a new user- just needs access to Define Permissions)
3. Select the Define Permissions tab
4. Select General Permissions
5. Click checkbox next to Action to select all permissions
6. Save
7. Select General Permissions
8. Click checkbox next to Action to deselect all permissions
9. Save
10. Select General Permissions
11. Select any permission
12. Save

**Comment by joshuacords** [comment]
@ksuetani The popup warning is designed to consistently appear if a Resource being modified is a ResourceBlockPermission type. These include Bookmark Entry, Bookmark Folder as well as some Calendar entities. When I get in on Monday I will test your specific steps to see if some weird behavior is happening with that specific case.

**Comment by ksuetani** [comment]
@joshuacords cool, thanks!

**Comment by joshuacords** [comment]
@ksuetani I found the root of the problem and updated the code in the review Drew's going through here https://github.com/drewbrokke/liferay-portal/pull/312

**Pull request closed without merging**
