### PR TITLE
[TS]LPS-98301 Internal Server Error thrown due to orphan portlet

### PR DESCRIPTION
**Pull request by NorbertKocsis**
https://issues.liferay.com/browse/LPS-98301

### CODE REVIEW

**Comment by drewbrokke** [comment]
@NorbertKocsis Overall this change looks fine, but I'm a bit concerned now that there is too much ambiguity in the titles of each "Clean Up Portlet Preferences...." option. The title for the action added by this pull is descriptive and helpful, but the title of the option that @holatuwol asked about [here](https://issues.liferay.com/browse/PTR-1157?focusedCommentId=1937535&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1937535) is left to be ambiguous, even though the action it performs is also very specific to a particular use-case.

We should think of a way to re-phrase the existing option to clearly distinguish it from the one in this PR (without requiring the admin to read the tooltip).

**Comment by NorbertKocsis** [comment]
Hi,

I'll think a more descriptive name.

Br,
Norbert

**Comment by NorbertKocsis** [comment]
Hi,

Does it look good now?

Br,
Norbert

**Comment by drewbrokke** [comment]
@NorbertKocsis Looks great, thank you!

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
PR sent to https://github.com/brianchandotcom/liferay-portal/pull/80276

**Pull request closed without merging**
