### PR TITLE
Lps 145073

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:test:tck

**Comment by ngriffin7a** [comment]
@drewbrokke The Jenkins report has:
```
test-portal-acceptance-pullrequest(master)	Console	Test Report	Jan 10, 2022 2:42:14 PM PST	35 minutes	COMPLETED	SUCCESS
```
So I'm not sure why CI reported a failure? Looks like all is well for you to review the PR?

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:tck

**Comment by drewbrokke** [comment]
@ngriffin7a looks good to me. Not sure what to say about the CI failures just yet - let's see what this next run produces.

**Comment by ngriffin7a** [comment]
Hi @drewbrokke -- The Jenkins results indicate success again.

Perhaps there is a big in CI such that when you run 'ci:test:tck' standalone, it reports a failure even if a failure has not occurred?

I suppose it is time for a full `ci:test` instead. I'll leave that up to you.

**Comment by ngriffin7a** [comment]
@drewbrokke Are things in good enough shape to send to Shuyang or BChan?

**Comment by drewbrokke** [comment]
@ngriffin7a yes IMO I think this is good to send to Shuyang. Thanks!

**Comment by ngriffin7a** [comment]
@drewbrokke Thanks, I'll send it to Shuyang.

**Pull request closed without merging**
