### PR TITLE
LPS-108140 Add tests.

### PR DESCRIPTION
**Pull request by cgoncas**
Hey @drewbrokke !!

Could you take a look at this pull? We need to extract the RoleTypeContributor to the API, so we can use it from another module.

What do you think?

Thanks in advance!

/cc @adolfopa

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
Hi @cgoncas, thanks for sending this my way. Overall I like the direction this is going, but I've noticed a couple of issues when trying to hit the page to view Depot Roles in Roles Admin:

1. The tab title for 'repository-roles' is not translated. Since this is being contributed from an external module, you'll need to provide your own translated value in `getTabTitle` (Roles Admin will not have the language key you need). The same goes for the `getTitle` method, which sets the label for the creation menu for adding a new depot role.
2. There is an exception thrown. This stems from the default depot roles not having a corresponding resource in the ResourcePermissions table. We do a permission check on each role here: https://github.com/liferay/liferay-portal/blob/0d4191d835ebf981876c6e68a27749fcc6ea8cd7/modules/apps/roles/roles-admin-web/src/main/resources/META-INF/resources/view.jsp#L82.

The first issue should be an easy fix, but the solution to the second issue is not as obvious to me. Is it critical that the default depot roles do not have resources?

**Comment by cgoncas** [comment]
Hey @drewbrokke !!

Thanks a lot for the review :).

I have added some changes to include all your observations!!

For the first point: we have translated the keys, as you suggested.
For the second point: we have added the right resources.

Thanks in advance!!

/cc @adolfopa

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
PR sent to https://github.com/brianchandotcom/liferay-portal/pull/84517

**Pull request closed without merging**
