### PR TITLE
[TS] LPS-123874

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-123874

Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
Retrigger the relavent test since the previous failure are commen with upstream, and there is are no issues on upstream now. If it still fails for a same reason, maybe a rebase requires.

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
