### PR TITLE
LPS-109676 Asset Library permissions configuration should be scoped to Asset Library roles

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @alee8888

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Pull request closed without merging**
