### PR TITLE
LPS-183263 Clean workspace dependencies

### PR DESCRIPTION
**Pull request by Seiphon**
Hi @drewbrokke , the tests can passed here https://github.com/Seiphon/liferay-portal/pull/126

### CODE REVIEW

**Comment by Seiphon** [comment]
ci:test:sf

**Comment by Seiphon** [comment]
ci:test:projectp-templates

**Review by drewbrokke — APPROVED** [review]

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
See https://github.com/drewbrokke/liferay-portal/pull/1485

**Pull request closed without merging**
