### PR TITLE
LPS-123864 Add localization to the Country name

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-123864](https://issues.liferay.com/browse/LPS-123864).<br/><br/>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:forward

**Comment by yichenroy** [comment]
ci:help

**Comment by yichenroy** [comment]
ci:forward

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:close

**Pull request closed without merging**
