### PR TITLE
LPS-110656 Semver

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @drewbrokke 

We need some of the Depot roles to be treated in the same way as the ones for sites, orgs, etc. In particular, we need Administrator, Member and Owner to have the same kind of restrictions (Member should be assigned automatically, it should not show up in some role listings, etc.)

In various places some decisions are taken based on the kind of role. Up til now, these kinds were implicit, and where expressed through hardcoded conditionals. Here I've tried to make this "kinds" part of the contributor API.

I've detected 4 kinds of roles: Administrative, Member, Implied, and System (non editable). For each one, I've added a method to the RoleTypeContributor API, so that each contributor is able to declare how its contributed roles should behave.

There's one big problem here, and that is that the RoleTypeContributor interface is in a module, but some logic that depends on the kind of role is in the core. There are (at least) two places where this happens:
- PortalImpl#isSystemRole(); I've chosen not to do anything about this here. The default system roles are referenced very early in the boot process, so I think it is a bit risky to touch that part.
- UserAdminImpl; I've moved some of the logic (filtering) into a new interface in a module, so that I can make use of the contributors to change behaviour based on the kind of role.

Here I've tried to to the minimum amount of work necessary, but I'm not really happy about how it looks. I think there's more work to do to make contributing roles more general, so take this PR as a way to start that discussion :-)

Issues we may need to discuss:
- Role "kind" naming. In particular, the System category is not very clear to me.
- Should we try to extract more logic out of the core? The UserAdminImpl class has a ton of logic, some of it used only from modules, other from the core as well.
- Any other issue you see.

Let me know what do you think about this.

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
@adolfopa closing based on our conversation.

**Comment by adolfopa** [comment]
See https://github.com/drewbrokke/liferay-portal/pull/1026

**Pull request closed without merging**
