### PR TITLE
LPS-181508 fix remained project template issues

### PR DESCRIPTION
**Pull request by simonjhy**

### CODE REVIEW

**Comment by simonjhy** [comment]
@drewbrokke Because the gradle default plugin gadleTest failure, this pull can not pass ci gradle plugin test now.

**Comment by simonjhy** [comment]
@drewbrokke I have finished upgrade blade project to support Gradle 7(https://liferay.atlassian.net/browse/BLADE-728), It now need to wait this pull can be merged and publish new version project template. Then we can publish new version Blade to support  completely gradle 7(gradle plugins and project template).

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
See https://github.com/drewbrokke/liferay-portal/pull/1479

**Pull request closed without merging**
