### PR TITLE
LPS-127386 Commerce modules do not resolve on DXP using release packaging

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-127386](https://issues.liferay.com/browse/LPS-127386).<br/><br/>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez @vicnate5

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:license

**Comment by drewbrokke** [comment]
ci:stop

**Comment by drewbrokke** [comment]
ci:test:license

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:lpkg

**Comment by drewbrokke** [comment]
@vicnate5 I'll work to resolve this today

**Comment by drewbrokke** [comment]
See https://github.com/drewbrokke/liferay-portal/pull/1295

**Pull request closed without merging**
