### PR TITLE
LPS-122443 Failed upgrade process for module com.liferay.account.service when upgrading from 7.3.0 in PostgreSQL

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @alee8888

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
@patriciajeanperez what's the test suite for the upgrade tests?

**Comment by drewbrokke** [comment]
LGTM 👍  Once the upgrade tests pass we can forward.

**Comment by patriciajeanperez** [comment]
ci:test:upgrade

**Comment by patriciajeanperez** [comment]
^ this will run all the upgrade related tests @pei-jung

**Comment by pei-jung** [comment]
thanks @patriciajeanperez!

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
