### PR TITLE
LPS-125701 Bridge CommerceAccount service to AccountEntry service

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-125701](https://issues.liferay.com/browse/LPS-125701).

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:upgrade

**Comment by drewbrokke** [comment]
ci:test:commerce

**Comment by drewbrokke** [comment]
@pei-jung FYI

**Comment by drewbrokke** [comment]
ci:stop

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:upgrade

**Comment by drewbrokke** [comment]
ci:test:commerce

**Comment by drewbrokke** [comment]
@pei-jung this is the better pull.

**Comment by patriciajeanperez** [comment]
Upgrade failures are not related.

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
