### PR TITLE
LPS-195170 fix gradle eclipse plugin can not use compileOnly error

### PR DESCRIPTION
**Pull request by simonjhy**
@drewbrokke Only the test-relvant test still got failure, the other have been passed.

### CODE REVIEW

**Comment by simonjhy** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
@simonjhy  this looks good. Feel free to forward it.

**Comment by simonjhy** [comment]
ci:forward

**Comment by simonjhy** [comment]
@drewbrokke  thanks

**Comment by simonjhy** [comment]
ci:forward

**Comment by simonjhy** [comment]
ci:test:stable

**Comment by drewbrokke** [comment]
ci:forward:force

**Comment by drewbrokke** [comment]
ci:forward:force

**Pull request closed without merging**
