### PR TITLE
LPS-104263 Use the new ItemSelectorDialog

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Hey @drewbrokke, 

we are removing uses of the old AUI _liferay-item-selector-dailog_ component. I am sending this to you so you can verify if everything works as before (internal interactions inside the Item Selector has been changed a little bit but the final result must be the same).

Thank you in advance!

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:test:stable

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
PR sent to https://github.com/brianchandotcom/liferay-portal/pull/81084

**Pull request closed without merging**
