### PR TITLE
LPS-124277 SQLSyntaxErrorException when upgrading from 7.2.10 to master

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-124277](https://issues.liferay.com/browse/LPS-124277).<br/><br/>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez @yuhai

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:upgrade

**Comment by Sharryxue** [comment]
ci:test:upgrade

**Comment by drewbrokke** [comment]
@Sharryxue @patriciajeanperez should I re-run the upgrade suite, or are we good to forward?

**Comment by drewbrokke** [comment]
ci:test:upgrade

**Comment by drewbrokke** [comment]
I went ahead and re-triggered the suite, just in case :)

**Comment by patriciajeanperez** [comment]
Checked the results from the first run and the pull looks good to forward @drewbrokke

**Comment by patriciajeanperez** [comment]
ci:forward

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:upgrade

**Comment by drewbrokke** [comment]
ci:test:commerce

**Comment by drewbrokke** [comment]
ci:stop

**Comment by Sharryxue** [comment]
The upgrade failure not related.

**Pull request closed without merging**
