### PR TITLE
LPS-121907

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @drewbrokke,

Attached is an update for http://issues.liferay.com/browse/LPS-121907.

**Test Plan:**

1. Login to Liferay
2. Click on the **Application Menu**
3. Go to **Control Panel** -> **System** -> **Server Administration**
4. Click on **Log Levels** and **Properties** to access the management toolbar

server-admin

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
ci:test:sf

**Comment by jonmak08** [comment]
ci:test:relevant

**Review by julien — APPROVED** [review]

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
