### PR TITLE
[TS] LPS-117666

### PR DESCRIPTION
**Pull request by ChrisKian**
[LPS-117666](https://issues.liferay.com/browse/LPS-117666)

From @istvansajtos:

> I hope you can review my changes. You are already familiar with the issue due to [PTR-1819](https://issues.liferay.com/browse/PTR-1819).
> 
> To solve this, I used the same approach as Account Settings page to collect the user's inherited regular roles. Basically, I mirrored the __getAllGroups(User)_ method and its dependencies from _UserDisplayContext_. The group filtering rules (originally determined as _InitDisplayContext._filterManageable*_ values) became a bit more simple in the mirrored methods, because in _UserAccountResourceImpl_ we don't have the [portlet contextual data](https://github.com/liferay/liferay-portal/blob/master/modules/apps/users-admin/users-admin-web/src/main/java/com/liferay/users/admin/web/internal/display/context/InitDisplayContext.java#L43-L53) as in the original case.

I've tested the changes and see no problems.

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@ChrisKian @istvansajtos looks like some relevant test failures. Do these happen locally as well?

**Comment by istvansajtos** [comment]
Hi @drewbrokke ,

I will be on PTO next week, afterwards I can test the failures in local. Until then please feel free to close the PR.

Thanks.

**Comment by drewbrokke** [comment]
@istvansajtos sounds good. Also, if there is a way to abstract the common logic I'd prefer that. I realize it may end up being more work than is reasonable at this stage, but I'd like to at least explore the option. Closing for now.

**Pull request closed without merging**
