### PR TITLE
LPS-120825 Changes to own email address or screen name not saved

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-120825](https://issues.liferay.com/browse/LPS-120825).<br><br>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
ci:forward

**Comment by jpince** [comment]
@patriciajeanperez fyi, commenting `ci:forward` before `ci:test:relevant` completes will trigger another `ci:test:relevant`.

CI is backed up right now (I think due to the release tester for the DXP prelim build), so test results will be slow.

**Comment by jpince** [comment]
Looks like semver will fail due to BChan publishing. This PR will likely need to be manually forwarded.

**Comment by brianchandotcom** [comment]
@drewbrokke I manually merged this.

**Pull request closed without merging**
