### PR TITLE
LPS-121481 Use highcharts 11.1.0 to avoid vulnerability

### PR DESCRIPTION
**Pull request by Seiphon**

### CODE REVIEW

**Comment by Seiphon** [comment]
ci:test:sf

**Comment by Seiphon** [comment]
ci:test:relevant

**Comment by Seiphon** [comment]
ci:test:gradle-plugins

**Comment by Seiphon** [comment]
all the tests are passed here https://github.com/Seiphon/liferay-portal/pull/143

**Review by drewbrokke — APPROVED** [review]
LGTM, thanks @Seiphon!

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
