### PR TITLE
LPS-55993

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by zxdgoal** [comment]
Hey @drewbrokke

This pr actually cannot address the password issue in FF 38 completely.

I cannot figure out a way to stop FF38 to fill password field.

Please follow it up in https://issues.liferay.com/browse/LPP-16719

Thanks
John.

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
Pull request submitted to https://github.com/JorgeFerrer/liferay-portal/pull/546. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
