### PR TITLE
LPS-83662 Adjust confirmation question in test macro

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @drewbrokke 

A failed test raised my attention that a confirmation question for deleting Roles needs to be adjusted to the changes made in [LPS-83662](https://issues.liferay.com/browse/LPS-83662).

Could you please review these?

Thank you and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test

**Comment by drewbrokke** [comment]
@jpince the functional test failures here are because the tests are still looking for the old text (as if the changes in this pull did not happen).  Can you clarify what's going on or missing?  I'm not familiar enough with how we run our functional tests to make the call.

**Comment by jpince** [comment]
@IstvanD @drewbrokke your change is in the [tearDown section of the test](https://github.com/drewbrokke/liferay-portal/blob/dfbc87f3dd779db9bd9a0108dbe21641386e8479/portal-web/test/functional/com/liferay/portalweb/macros/Role.macro#L1035-L1058). The test will still pass, even if it fails tearDown.

Looking at the POSHI report, the test is calling `LexiconEntry#delete"`, 
The file is located here: https://github.com/liferay/liferay-portal/blob/master/portal-web/test/functional/com/liferay/portalweb/macros/LexiconEntry.macro#L24. However, this is a red flag for me, because it tells me that you are potentially deviating from Lexicon standards.  Please do not modify LexiconEntry.macro, as tests for other modules use this text.

So it seems to me you have two options:
1. Revert the change(s) you made at head so the message conforms to Lexicon standards
1. Change the test to fit your new text. You could replace https://github.com/drewbrokke/liferay-portal/blob/dfbc87f3dd779db9bd9a0108dbe21641386e8479/portal-web/test/functional/com/liferay/portalweb/macros/Role.macro#L364-L366 with the code from tearDown
https://github.com/drewbrokke/liferay-portal/blob/dfbc87f3dd779db9bd9a0108dbe21641386e8479/portal-web/test/functional/com/liferay/portalweb/macros/Role.macro#L1047-L1055 but we'd probably like to have more context on why we're making the deviation, and need another Test Engineer who works in POSHI more than me to suggest a more elegant solution.

Please know my comments above are not trying to evaluate the change, as I understand that you guys may have good reasons for making this change :) Just trying to help as much as I can.

cc/ @john-co

**Comment by drewbrokke** [comment]
I'm gonna rope in @alee8888 to weigh in on this.  I think that it makes sense to make room for more informative confirmation messages, so perhaps we could consider the option of updating the test.

**Comment by joshchong** [comment]
FYI, a test fix for this was merged:
https://github.com/liferay/liferay-portal/commit/8007e201c85b0a94cd343b70ba81d11e5450700c
Context:
https://issues.liferay.com/browse/LRQA-43551

**Comment by IstvanD** [comment]
Hi @joshchong 

Thank you for the input.
@jpince @alee8888 @drewbrokke does this mean that after this changes, LPS-83662 will not cause those test failures?

Sorry, I'm not that well-versed with the test mechanism.

Thank you!
István

**Comment by drewbrokke** [comment]
@IstvanD that's correct, the functional tests will no longer assert for specific text in a confirmation dialogue.  It will allow us more flexibility going forward.

**Comment by drewbrokke** [comment]
Closing since the test failures will no longer occur in upstream.

**Comment by IstvanD** [comment]
Hello,

Thank you for dealing with this!

Best regards,
István

**Pull request closed without merging**
