### PR TITLE
LPS-59844 TypeError when installing Xuggler.

### PR DESCRIPTION
**Pull request by carloslancha**

### CODE REVIEW

**Comment by carloslancha** [comment]
Hi @drewbrokke!

We have [LPS-59436](https://issues.liferay.com/browse/LPS-59436) blocked because of this issue. We need Xuggler install option to work in order to test our feature.

[Your pull](https://github.com/natecavanaugh/liferay-portal/pull/3637) it's taking too long to be reviewed and pushed to master, I suppose because all other stuff you're doing (removing progressbar, etc), and we've been blocked for two weeks.

If you don't mind send this pull to @brianchandotcom just to fix Xuggler installation, and then all other changes can be added on top of it.

Thanks so much!

**Comment by drewbrokke** [comment]
Pull request forwarded to https://github.com/jonmak08/liferay-portal/pull/1371. [See changes here.](https://github.com/drewbrokke/liferay-portal/compare/36d6012~1...36d6012) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jonmak08** [comment]
Hey @carloslancha,

This issue is in @natecavanaugh's review queue at https://github.com/natecavanaugh/liferay-portal/pull/3637.  We just had the NAS so he has been unable to review all the pulls in his queue before he left.

@natecavanaugh will be back in the office tomorrow, but in the meantime @drewbrokke is going to review and send me this pull.  I will review and send it to @brianchandotcom. Then when @natecavanaugh review's https://github.com/natecavanaugh/liferay-portal/pull/3637 everything will already be in upstream and everything should rebase cleanly.

Please let me know if you have any questions.  Sorry for the delay.  Thanks!

**Comment by carloslancha** [comment]
@jonmak08 hey! Sounds great, thanks so much!

**Pull request closed without merging**
