### PR TITLE
portal-kernel: require opt-in for checking site-level permissions

### PR DESCRIPTION
**Pull request by drewbrokke**
@david-truong

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test: publications

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:echo

**Comment by david-truong** [comment]
ci:test:commerce

**Comment by david-truong** [comment]
ci:test:echo

**Comment by david-truong** [comment]
ci:test:commerce

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:relevant

**Comment by david-truong** [comment]
ci:test:publications

**Comment by david-truong** [comment]
ci:test:echo

**Comment by david-truong** [comment]
ci:test:commerce

**Pull request closed without merging**
