### PR TITLE
[TS] LPS-95837

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-95837

Hey Drew,
Since the children types are stored as a configuration, I don't think it's possible to "save" an empty string array rather than the blank value which currently happens.  There are also situations where a config file is used, and a blank string is used anyways.

Let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
PR sent to https://github.com/brianchandotcom/liferay-portal/pull/73503

**Pull request closed without merging**
