### PR TITLE
LPS-69383 Extract Captcha to OSGi module

### PR DESCRIPTION
**Pull request by pei-jung**
https://issues.liferay.com/browse/LPS-69383

This pull is a prerequisite to move captcha configuration out of server-admin to system settings. I break up the changes into 2 parts so it's easier to review.

/cc @jorgeferrer

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:stop

**Comment by pei-jung** [comment]
ci:retest

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
Pull request sent to https://github.com/brianchandotcom/liferay-portal/pull/45200.  Thanks!

**Pull request closed without merging**
