### PR TITLE
LPS-121587 As an instance Administrator, I want to export Instance Settings Configuration Files

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-121587](https://issues.liferay.com/browse/LPS-121587).

Hey @pei-jung, I added one commit that also enables exporting factory configurations and exporting all configurations in Instance Settings. Please let me know if you see anything you think needs to change.

/cc @alee8888 @ChrisKian @dejuknow @patriciajeanperez

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
The upgrade failure like this `classic-theme.war does not support this version of Liferay` is due to Brian merged the master-private divergence without the master pull, refer [slack](https://liferay.slack.com/archives/CLCD3DQLF/p1602256531025100?thread_ts=1602235119.025000&cid=CLCD3DQLF), this probably can be resolved via rebase.
Semantic versioning issue should be fixed by [commit](https://github.com/liferay/liferay-portal/commit/7250eb35f61b5d64c723dbf0a5be6ef076f9fcc9).
Issue in modules-unit-project-templates-jdk8/1 not specific to this pr, addressed the issue in [LPS-122083](https://issues.liferay.com/browse/LPS-122083).

**Comment by patriciajeanperez** [comment]
Hey @drewbrokke, as Sharry mentioned, a rebase will be needed to fix the semver issues as well as the upgrade failures.

**Comment by patriciajeanperez** [comment]
ci:forward

**Comment by patriciajeanperez** [comment]
@drewbrokke There was a cache branch that got deleted by another Jenkins slave node, hence the `modules-unit-project-templates-jdk8` errors. The upgrades test is still being looked into, but the quarantine was sent. Will re-run once the upgrades tests are quarantined at head.

**Comment by drewbrokke** [comment]
Thanks for the update @patriciajeanperez!

**Comment by patriciajeanperez** [comment]
ci:forward

**Comment by Sharryxue** [comment]
ci:forward

**Comment by Sharryxue** [comment]
Rerun the forward command since the issue in stable job not specific and it begain pass on some other prs.
/cc @drewbrokke @patriciajeanperez

**Pull request closed without merging**
