### PR TITLE
LPS-122289 Buffer the results so the toolbar can fetch the total.

### PR DESCRIPTION
**Pull request by SamZiemer**
Notes from @brianikim

> https://issues.liferay.com/browse/LPS-122289
> 
> Issue is straightforward. The management toolbar is governing the total in view.jsp and the search results are being determined within the include .jsps.
> 
> Solution is to buffer the included implementations so that the request retains the searchContainer which we use to fetch the total.
> 
> Sincerely,
> Brian

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
LGTM 👍

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
@pyoo47 is this something I can try to re-forward?

**Comment by pyoo47** [comment]
@drewbrokke Yes, we've been seeing this problem from time to time. Re-triggering the forward using `ci:forward` should correct it.

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
