### PR TITLE
LPS-124582 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-124582

### CODE REVIEW

**Comment by kyle-miho** [comment]
Hey @drewbrokke i sent this over to you since you probably have more context on this with Users/Organizations knowledge than the people I can send it over to in Core. No rush for this, I can also send it over to them if its more convenient, I just figure you would be able to review this with the most knowledge

**Comment by Sharryxue** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Nice work @kyle-miho. See https://github.com/drewbrokke/liferay-portal/pull/1311.

**Pull request closed without merging**
