### PR TITLE
[TS] LPS-102185

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-90191
https://issues.liferay.com/browse/LPS-102185

Hey Drew, this PR is a bit different than the earlier ones I has sent.  Essentially, instead of trying to convert the portalPreferences into portletPreferences then into OSGI configs (then back into portletPreferences for the changes made by LPS-102185), I just leave them as portletPreferences.  Please let me know if you have any questions, thanks

Original Message:

> Background: Both LPS-90919 and LPS-102185 deal with a similar issue, so I have bundled them together.  LPS-102185 deals with not being able to configure Token SSO at the instance level, and LPS-90191 covers the same, as well as not being able to configure it from 62x to DXP.
> 
> I have used the branch https://github.com/stian-sigvartsen/liferay-portal/pull/201 along with 2 additional commits for LPS-90919 to cover both tickets.
> 
> The changes for LPS-102185 have already been reviewed a few times and I have made no changes; simply put they allow for token based SSO to be configured at the instance level.
> 
> The [comment left by BChan](https://github.com/brianchandotcom/liferay-portal/pull/79585#issuecomment-545578952) regarding a rename being needed I believe isn't actually needed.  For the first file he mentions, "PortalSettingsTokenConstants", we can see some examples [[1]](https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-settings/portal-settings-authentication-opensso-web/src/main/java/com/liferay/portal/settings/authentication/opensso/web/internal/constants/PortalSettingsOpenSSOConstants.java) [[2]](https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-settings/portal-settings-authentication-facebook-connect-web/src/main/java/com/liferay/portal/settings/authentication/facebook/connect/web/internal/constants/PortalSettingsFacebookConnectConstants.java) of the same naming convention.  This is also true for the second file "TokenPortalSettingsFormContributor" [[1]](https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-settings/portal-settings-authentication-facebook-connect-web/src/main/java/com/liferay/portal/settings/authentication/facebook/connect/web/internal/portlet/action/FacebookConnectPortalSettingsFormContributor.java) [[2]](https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-settings/portal-settings-authentication-openid-connect-web/src/main/java/com/liferay/portal/settings/authentication/openid/connect/web/internal/portlet/action/OpenIdConnectPortalSettingsFormContributor.java).
> 
> As for the changes for LPS-90191, they are required for users with Shiboleth/Siteminder configured in 62x and below who are now upgrading to DXP.  Before, we had verify processes to modify these configurations, but now we would like this portalProperties to be converted into ~~OSGI configurations~~ portletPreferences.
> ~~The second half of the changes are to allow the PrefsPropsToConfigurationUpgradeHelper class to read in instance-scoped portalProperties as well.  This allows us to read/write configurations per instance.~~
> The change now simply upgrades the existing portalPreferences into portletPrefences, which work properly at the instance-level with the inclusion of LPS-102185.
> 
> These changes cover many different areas/teams, so I will CC everyone I believe might need to know.  I will send this PR to Drew first to look through the ~~PrefsPropsToConfigurationUpgradeHelper~~ configuration upgrade changes.

Please let me know if you have any questions, thanks!

CC @achaparro
CC @lipusz 
CC @stian-sigvartsen

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Hey @ChrisKian @stian-sigvartsen, overall this looks like it will work. I didn't see anything outstanding that would be an issue (though I have not personally tested the code). It doesn't look like there are significant changes to our components since this pull no longer touches the prefsProps to configuration upgrade helper.

That being said, IMO this pull is re-doing a lot of work that is already done by our configuration framework. In theory, you shouldn't need to add any of these: 
1. `TokenPortalSettingsConfigurationScreenContributor`
2. `TokenPortalSettingsFormContributor`
3. any of the JSPs.  
4. Any of the other files required by 1-3

All that's required is to: 
1. add the upgrade process that moves the config `pid` (already done in this pull)
2. add the upgrade process that translates company-level PortletPreferences to company-scoped configurations (@ChrisKian already accomplished this in an earlier pull)
3. change all read calls for `TokenConfiguration` to something like this:

```java
_configurationProvider.getCompanyConfiguration(TokenConfiguration.class, companyId);
```

And after that it _should_ work. You can leave the `TokenConfiguration` scope as `company` so that the auto-generated UI shows up in Instance Settings.

Please let me know if there's something I missed. This is my opinion on the approach that should be taken, but like I said earlier, the current code in the pull will also work.  If you want to try my approach, let me know and I'll be happy to assist however I can. 

Thanks all!

**Comment by stian-sigvartsen** [comment]
Hi @drewbrokke . The reason why I think all that "re-doing" is necessary is because the company-scoped configuration for Token SSO should be stored into the PortletPreferences table rather than as a scoped OSGi configuration. Also it is stored under a different SERVICE_NAME rather than the PID from the metatype.

This is so that it is consistent with all the other SSOs. I agree we should move towards using scoped OSGi configuration for this, but I feel we should apply that to all the SSOs together.

/cc @ChrisKian

**Comment by drewbrokke** [comment]
@stian-sigvartsen thank you for the clarification. If it is currently a requirement for Token SSO to be stored in the `PortletPreferences` table, then this look like the way to do it 👍 

For my education, why is it necessary that Token SSO be stored in `PortletPrerferences`?

**Comment by stian-sigvartsen** [comment]
@drewbrokke it's just a legacy approach for consistency. It's not so important really except for the easier maintenance if things are consistent (especially if we backport) and the TokenContants.SERVICE_NAME was there already and not used consistently IIRC.

I suggest we raise a ticket that's not for backporting for all the SSOs.

**Comment by drewbrokke** [comment]
Understood, thank you! From my perspective, we're good to move forward with this pull. Thanks all!

**Comment by ChrisKian** [comment]
Thanks guys, sent to https://github.com/brianchandotcom/liferay-portal/pull/80691

**Pull request closed without merging**
