### PR TITLE
LPS-121904 Migrate v2 usages in roles/roles-item-selector-web

### PR DESCRIPTION
**Pull request by julien**
The <clay:management-toolbar-v2 /> tag has been replaced with the
<clay:management-toolbar /> tag (which uses clay v3).

**Test plan**:
- Navigate to **People** > **Segments**
- Create a new **Segment**
- In the dropdown menu to the right, click on **Assign Site Roles**
- Assert that you can assign, search and filter Site Roles

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by julien** [comment]
cc @ambrinchaudhary @markocikos @jonmak08

**Review by ambrinchaudhary — APPROVED** [review]

**Review by markocikos — APPROVED** [review]
LGTM!

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
