### PR TITLE
LPS-115707 organizations-test: use name as the sorting field to compa…

### PR DESCRIPTION
**Pull request by joshuacords**
…re results which is a sortable field instead of organizationId which the search engine will not sort

https://issues.liferay.com/browse/LPS-115707

The source of the issue is this Field [method](https://github.com/liferay/liferay-portal/blob/5502e308b4246404f9e102ce208f61504d4ad6c9/portal-kernel/src/com/liferay/portal/kernel/search/Field.java#L211-L215) will return "_score" as the sort if the field name, in this case "organizationId", is not identifiable as a sortable field.

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
LGTM

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
