### PR TITLE
[TS] LPS-108058

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-108058

Confirmed to not be a security vulnerability by @topolik.  See [this comment](https://issues.liferay.com/browse/LPS-108058?focusedCommentId=2073957&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2073957).

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
PR submitted to https://github.com/brianchandotcom/liferay-portal/pull/84422

**Pull request closed without merging**
