### PR TITLE
LPS-90257 - Use putHTMLValue

### PR DESCRIPTION
**Pull request by carloslancha**

### CODE REVIEW

**Comment by drewbrokke** [comment]
@carloslancha I'm glad it was that simple :) Thanks for the help!

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by carloslancha** [comment]
@drewbrokke @pei-jung we need to invest more time on this, html value is not being passed to the templates correctly on client side (after fixing server side). Just go ahead with your code and please, open us a ticket to fix this. Thx!

**Comment by pei-jung** [comment]
@carloslancha thanks for working on the fix. I have created a ticket for the issue and assigned it to you. Please see https://issues.liferay.com/browse/LPS-91173. Thanks!

**Pull request closed without merging**
