### PR TITLE
LPS-121922

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @drewbrokke,

Attached is an update for http://issues.liferay.com/browse/LPS-121922.

**Test Plan:**
1. Login to Liferay
2. Click on the **Applications Menu**
3. Go to **Control Panel** -> **Users and Organizations**
4. Click the `+`
5. Add a **User**
6. Click on the **Applications Menu**
7. Go to **Control Panel** -> **User Groups**
8. Click the `+`
9. Add a **User Group**
10. Click the **ellipsis** for the newly created **User Group**
11. Click **Assign Members**
12. Click the `+`
13. Add a new **User** to the **User Group**
admin-users-group

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
ci:test:sf

**Comment by jonmak08** [comment]
ci:test:relevant

**Comment by jonmak08** [comment]
A note about this pull request we did not migrate the management toolbar functions into the `PropsTransformer.js` file because of the inline JSP code that we would have to migrate as well.  In order to fully migrate everything correctly, we would need to refactor the JS code in https://github.com/drewbrokke/liferay-portal/blob/fe7d5c58e19232e8fdf83b152e0dd318b6a1aad8/modules/apps/user-groups-admin/user-groups-admin-web/src/main/resources/META-INF/resources/view.jsp.  Because of this we are going to migrate the management toolbar in the least intrusive manner and allow your team to refactor the code first.

Please let me know if you have any questions. Thanks!

**Comment by jbalsas** [comment]
Hey @jonmak08, `LocalFile.CPUsergroups#RemoveMember` looks suspicious since we did something with it here, I think... could you double check to see if it's a related issue and retrigger `ci:test:relevant` if not?

**Comment by Sharryxue** [comment]
Hello @jonmak08,
The failed test seems related to changes made in [commit](https://github.com/drewbrokke/liferay-portal/pull/1325/files#diff-cdba0261d4f1fc795133fcd60027283601a7767f6515e2e02194feb8dda42308L34-R34), I can send a follow up test fix if this is an intended change.

**Comment by Sharryxue** [comment]
ci:test:bundle

**Comment by jonmak08** [comment]
Hey @Sharryxue,

That change is dependent on @drewbrokke approving it.  I am waiting on his review for this pull request to sign off on the changes.

@drewbrokke, can you please let us know if you approve or deny these changes of the icon?  See https://github.com/drewbrokke/liferay-portal/pull/1325/files#diff-cdba0261d4f1fc795133fcd60027283601a7767f6515e2e02194feb8dda42308L34-R34

**Comment by pei-jung** [comment]
Changes look good to me.

@patriciajeanperez @Sharryxue please update the functional tests and forward. Thank you!

**Comment by Sharryxue** [comment]
Send with TF [Sharryxue/liferay-portal#255](https://github.com/Sharryxue/liferay-portal/pull/255)
NOTE:
There is an issue related select all checkbox, and it can be ignored for now based on [comment](https://github.com/liferay-echo/liferay-portal/pull/3910#issuecomment-793734570).

**Comment by jonmak08** [comment]
Thanks @Sharryxue! Closing pull request as changes have been forwarded with https://github.com/Sharryxue/liferay-portal/pull/255

**Pull request closed without merging**
