### PR TITLE
LPS-120675 Upgrade Hibernate Validator version to avoid vulnerability

### PR DESCRIPTION
**Pull request by Seiphon**

### CODE REVIEW

**Comment by Seiphon** [comment]
ci:test:sf

**Comment by Seiphon** [comment]
ci:test:relevant

**Comment by Seiphon** [comment]
ci:test:project-templates

**Review by drewbrokke — CHANGES_REQUESTED** [review]
Thanks @Seiphon! I found one more spot [here](https://github.com/liferay/liferay-portal/blob/master/lib/versions-complete.xml?plain=1#L4212) that may need changing. Can you double-check that one? Not sure if it's auto-generated or not.

**Comment by Seiphon** [comment]
ci:test:sf

**Comment by Seiphon** [comment]
ci:test:relevant

**Comment by Seiphon** [comment]
ci:test:project-templates

**Comment by Seiphon** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@Seiphon merge conflicts on this one too. Please update the versions and resend. Sorry about the delay.

**Comment by Seiphon** [comment]
Hey @drewbrokke  I resent the pr here https://github.com/drewbrokke/liferay-portal/pull/1572

**Pull request closed without merging**
