### PR TITLE
LPS-120300 Only grant the View permission to the User role upon creation of the system roles

### PR DESCRIPTION
**Pull request by hudakl**
Hi Drew,

Followup of drewbrokke#1186

I've added the try-finally block.

Thanks,
Laci

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Review by drewbrokke — CHANGES_REQUESTED** [review]
Hey @hudakl thanks for updating the test, it looks good now. Unfortunately, it looks like SF is still failing on this pull. If you'd like you can just fix SF and force-push the fix to this branch. Then we can re-run the tests. I'll leave the pull open for now. Thanks!

**Comment by drewbrokke** [comment]
@hudakl just making sure you saw my previous comment. It should be just a local auto SF, then you can force-push the change to this branch.

**Comment by hudakl** [comment]
Hi Drew,

I fixed the SF problem.

Thanks
Laci

**Comment by hudakl** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
@patriciajeanperez is this a similar issue?

**Comment by patriciajeanperez** [comment]
This one was a race condition with one of the upgrades tests. I'm rerunning ci:forward. I might have to test and send this manually tomorrow if it still fails. @drewbrokke

**Comment by patriciajeanperez** [comment]
ci:forward

**Comment by patriciajeanperez** [comment]
ci:test:roles

**Comment by patriciajeanperez** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/94982

**Comment by patriciajeanperez** [comment]
ci:close

**Pull request closed without merging**
