### PR TITLE
LPS-122356 Use RestrictionFactory to create an 'in' criterion to avoid ORA-01795

### PR DESCRIPTION
**Pull request by hudakl**
Hi Drew,

Could you please review my solution suggestion for LPS-122356?

Thank you,
Laci

### CODE REVIEW

**Comment by drewbrokke** [comment]
@hudakl thank you for sending this. The fix looks good to me. However, I'm going to close for now because we also need a test case to guard against regressions going forward. Please add that and resend, and I'll send it on.  Thanks!

@cc ChrisKian

**Comment by MarcellGyopos** [comment]
Hi @drewbrokke ,
I took over the LPS from Laci so I continued testing. I have found **testAddUsersThenReindex()** in com.liferay.users.admin.search.test**.UserReindexerPerformanceOfLargeUserGroupInManySitesTest** what already check the behaviour of the reindexing, just with 100 users. I run the tests before I merged Laci's new fix and as I excepted, it failed, cost 15 minutes. Then I merged the new code and run again the tests, after 15-30 minutes it failed with Caused by: java.io.IOException: Operation timed out AND java.sql.SQLException: Connection is closed. Could you help me how we can test this? The current solution is too hevy for the CI tests.

Best regards,
Marcell

**Comment by ChrisKian** [comment]
I'm currently testing some other methods to use in order to reindex a large amount of users.  Here's my latest PR, however it has some failing tests (likely unrelated).  https://github.com/ChrisKian/liferay-portal/pull/279

**Comment by ChrisKian** [comment]
Hi @MarcellGyopos,
I've been trying to rework the tests a bit in order to allow them to fully run, however I'm receiving the same unrelated errors regardless of my changes.

Could you link me to the errors you've been seeing, or explain how you are testing the changes?  Thanks

**Comment by MarcellGyopos** [comment]
Hi @drewbrokke ,
If you are thinking of running a local test, this is how I run the tests for example:` blade gw testIntegration --tests com.liferay.user.groups.admin.modellistener.test.UserGroupModelListenerTest` . Could explain what errors do you get?

**Comment by drewbrokke** [comment]
cc @ChrisKian

**Comment by ChrisKian** [comment]
Hi all,
Sorry for the late review, I'll get back to this issue tomorrow.  Thanks for the patience!

**Comment by ChrisKian** [comment]
Hi @MarcellGyopos,
When I run the tests locally, they take about 6-7 minutes to complete.  This is with 1100 users, and only running the UserReindexerPerformanceOfLargeUserGroupInManySitesTest class.  I have a few questions about your experience:
1. Are you experiencing these issues while running tests locally, or using CI?  You mention CI earlier, so I just want to clarify.
2. If locally, have you tried increasing jvm arguments to allow for more memory use?
3. If through CI/Github, have you reached out to the team which handles CI?

I've tried refactoring the test changes a bit to improve performance, but I haven't been able to do so.  Reindexing 1000+ users just takes a lot of time!

**Comment by MarcellGyopos** [comment]
HI @ChrisKian ,
Sorry fo the late response, I was on sick leave. 
_Are you experiencing these issues while running tests locally, or using CI?_ 
On my Local env.
_If locally, have you tried increasing jvm arguments to allow for more memory use?_
No, I have not. But after your comment I added 4Gb to the JVM. 
If through CI/Github, have you reached out to the team which handles CI?
I talked with Tibor Lipusz who said this test would be too heavy for the CI.

But in this case, is it okay to send the code to the master branch without the test?

**Comment by ChrisKian** [comment]
Hi @MarcellGyopos,
For a case like this, where it's not possible to include a CI test for the given scenario, I think we are fine to exclude the test.

The change is pretty minimal, and self-explanatory.  Also, when used for a smaller user count (test defaults to 100), the changes are still being used and working as intended.  The only aspect we are missing is 1000+ users on Oracle, but similar issues have been fixed the same way, so I think we are safe.

@drewbrokke, given the circumstances, are we able to forward these changes without a test?  Thanks!

**Comment by ChrisKian** [comment]
Forwarded to https://github.com/pei-jung/liferay-portal/pull/812

**Pull request closed without merging**
