### PR TITLE
LPS-55719

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-55719](https://issues.liferay.com/browse/LPS-55719).<br><br>

### CODE REVIEW

**Comment by alee8888** [comment]
ci:retest

**Comment by drewbrokke** [comment]
ci:retest

**Comment by drewbrokke** [comment]
ci:retest

**Comment by drewbrokke** [comment]
ci:retest

**Comment by drewbrokke** [comment]
I can look into the source of these failed tests.

**Comment by drewbrokke** [comment]
ci:retest

**Comment by drewbrokke** [comment]
ci:retest

**Pull request closed without merging**
