### PR TITLE
[TS] LPS-113096

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-113096

From @wanderlast:

> This PR technically is fixed by the second commit alone, but I felt like the first commit seemed to be a logical oversight and therefore included it. The issue is that, currently, LocalUtil._locale is hardcoded to correspond with EN-US. Therefore when LocaleUtil.fromLanguageId(languageId) is called when languageId is null (which is the case when 'default language' is selected in the virtual hosts menu), the locale selected will always be EN-US. This causes problems with the subsequent error checking for any portal that has removed EN-US as a locale option. Therefore, if the hostname doesn't have a language attached to it, we should simply check for the site default locale. Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
See https://github.com/ChrisKian/liferay-portal/pull/222

**Pull request closed without merging**
