### PR TITLE
[TS] LPS-105757

### PR DESCRIPTION
**Pull request by ChrisKian**
CC @wanderlast
From @jesseyeh-liferay:

## Problem :grimacing:

**[LPS-105757](https://issues.liferay.com/browse/LPS-105757)**

When a Site Administrator attempts to add users to a site via the "Assign Users to This Site" popup from a large pool of users (e.g., 25,000+ users), the popup experiences a big performance hit before the users are (incorrectly) displayed.

#### Overview

The original implementation's logic flow is summarized as follows (key areas bolded):

1. `SelectUsersDisplayContext.getUserSearchContainer()`
    1. **`UserLocalServiceImpl.searchCount()`**
        1. **`buildSearchContext()`**
        1. `DefaultIndexer.search()`
            1. `IndexerSearcherImpl.searchCount()`
                1. `IndexerSearcherImpl._search()`
                    1. `DefaultSearchResultPermissionFilter.search()`
                        1. **`isGroupAdmin()`**
                        1. **`filterHits()`**
    1. **`UserLocalServiceImpl.search()`**
        1. **`buildSearchContext()`**
        1. `DefaultIndexer.search()`
            1. `IndexerSearcherImpl.search()`
                1. `IndexerSearcherImpl._search()`
                    1. `DefaultSearchResultPermissionFilter.search()`
                        1. **`isGroupAdmin()`**
                        1. **`SlidingWindowSearcher.search()`**

`isGroupAdmin()` checks for a `groupId` attribute on the `SearchContext`, which is created via `buildSearchContext()`. However, this attribute is non-existent, and as a result, the logic in the outermost `searchCount()` and `search()` calls incorrectly fall into routines that filter and iterate through the users (via a sliding window), respectively -- these two routines are responsible for the performance hit.

## Solution :tada:

We introduce the `groupId` attribute by deprecating relevant methods that only pass in a `long companyId` in favor of methods that pass in a `ThemeDisplay` instead. From the `ThemeDisplay`, we can retrieve both the company and group IDs, which we use to build the `SearchContext`, thus allowing the `isGroupAdmin()` check to pass for Site Administrators.

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@ChrisKian Overall this change looks good.

The one hesitation I have with this approach is using `ThemeDisplay` as opposed to explicitly requiring `companyId` and `groupId` to be passed in. To me, asking for the values directly seems more clear, but I could be missing something. What do you think?

**Comment by ChrisKian** [comment]
Forwarded to https://github.com/pei-jung/liferay-portal/pull/549 with changes made.

**Pull request closed without merging**
