### PR TITLE
LPS-93427 Convert entries from legacy Instance Settings to be individual entries in Instance Settings

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-93427](https://issues.liferay.com/browse/LPS-93427).

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by xbrianlee** [comment]
ci:test

**Comment by xbrianlee** [comment]
ci:test:bundle

**Comment by xbrianlee** [comment]
ci:test:security

**Comment by jpince** [comment]
backend test results look good :+1: 

@xbrianlee see failure in [FacetedSearcherTest.testSearchByKeywordsIgnoresInactiveSites](https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/284473/AXIS_VARIABLE=23,label_exp=!master/testReport/junit/com.liferay.portal.search.facet.faceted.searcher.test/FacetedSearcherTest/testSearchByKeywordsIgnoresInactiveSites/). Looks like a fluke, but just bringing it up in case it's a flaky test.

**Pull request closed without merging**
