### PR TITLE
LPS-112519 As a portal admin, I can configure whether an account's users must explicitly match a defined list of domains

### PR DESCRIPTION
**Pull request by pei-jung**
Hey Drew,

Can you review my work? Couple things:

1. I extracted all the lang keys in the accounts modules to account-lang
2. Can you double check if my usage of ConfigurationTestUtil is correct for company scoped configurations? 
3. I'm not sure which package to put the configuration category and the custom form declaration. I'm debating between account-service and account-admin-web. Let me know which one you think works better. 

Thanks!

/cc @alee8888

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
Updated branch to fix the SF error.

ci:test:sf

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Pull request closed without merging**
