### PR TITLE
LPS-108187 As an admin, I want to assign the account manager role to organization users so that they can manage accounts associated to that organization

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @alee8888

### CODE REVIEW

**Comment by pei-jung** [comment]
Hey Drew,

Luckily it doesn't seem too hacky to get the control panel menu to show with organization role. I ended up hard coded the permission checks for `MANAGE_ACCOUNTS` on user's organizations (see 59207b0). 

Can you review my changes and see if I miss anything? Thanks!

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
@drewbrokke I don't quite understand the issue that the SF is complaining in `edit_role_permissions_navigation.jspf`. Any ideas?

**Comment by drewbrokke** [comment]
@pei-jung it looks like SF doesn't like that we're making additional calls to `data.put` after the initial usage of map builder. I think we are gonna have to change create new maps for every data attribute. The simplest way would be to just inline this into every attribute: 

```
<%= Collections.singletonMap("resource-href", editPermissionsResourceURL.toString()) &>
```

@hhuijser @brianchandotcom can this rule be adjusted at all to make allowance for this kind of scenario?

Initial map created: https://github.com/drewbrokke/liferay-portal/blob/8c0cc93a46624d2000933ff07b6396153190f3f3/modules/apps/roles/roles-admin-web/src/main/resources/META-INF/resources/edit_role_permissions_navigation.jspf#L56-L58

Copying the boolean logic inside a lambda function just to set a key is not very practical, since now the logic would be in two places (setting the map value, and rendering the markup).

Re-setting the key inside a conditional block: https://github.com/drewbrokke/liferay-portal/blob/8c0cc93a46624d2000933ff07b6396153190f3f3/modules/apps/roles/roles-admin-web/src/main/resources/META-INF/resources/edit_role_permissions_navigation.jspf#L87.

It's also not compatible at all with re-setting the key inside of a loop: https://github.com/drewbrokke/liferay-portal/blob/8c0cc93a46624d2000933ff07b6396153190f3f3/modules/apps/roles/roles-admin-web/src/main/resources/META-INF/resources/edit_role_permissions_navigation.jspf#L163

Thoughts?

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by hhuijser** [comment]
@drewbrokke that check should not be applied to `jsp`.
Guess SF didn't skip since it was in a `jspf`.
This fix should take care of that: https://github.com/hhuijser/liferay-portal/pull/4201

**Comment by drewbrokke** [comment]
Thanks @hhuijser !

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Pull request closed without merging**
