### PR TITLE
LPS-88636 Implement search for site role selection

### PR DESCRIPTION
**Pull request by brianikim**
Resending PR from: https://github.com/drewbrokke/liferay-portal/pull/698 with the changes you have suggested.

Sincerely,
Brian Kim

### CODE REVIEW

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brianikim** [comment]
Hello @drewbrokke ,

I made another commit to better reflect your suggested change. The automatic switch to step 2 should only occur when the keyword is empty, otherwise user selection should trigger it.

**Comment by drewbrokke** [comment]
PR sent to https://github.com/brianchandotcom/liferay-portal/pull/66258

@brianikim thanks for that.  I went ahead and made that change already, and realized my advice about copying the block was not the best.  I instead added an additional condition to the if check here: https://github.com/brianchandotcom/liferay-portal/pull/66258/commits/d586d3941c3165ae9a0e6574e972aaa735a2692e. That way we don't duplicate code.  My mistake.

**Comment by brianikim** [comment]
Hello @drewbrokke ,

Thank you for the changes!

Sincerely,
Brian Kim

**Pull request closed without merging**
