### PR TITLE
LPS-85515 users-admin-web - Update General > Information to match the design

### PR DESCRIPTION
**Pull request by stsquared99**

### CODE REVIEW

**Comment by stsquared99** [comment]
screen shot 2018-10-08 at 9 57 45 am

Unfixable issues:
Parent Organization search container does not format correctly after select
tag-selector taglib formatting

Check with Susanna on "Required Field" help text? Not currently used anywhere else

**Comment by drewbrokke** [comment]
PR sent to https://github.com/brianchandotcom/liferay-portal/pull/63906 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by susanavr** [comment]
Hi guys! @stsquared99 @drewbrokke 
It's Ok to me not to have the help text for the required field. 

Some little things:
The icon inside the table in "Parent organization" look like bold.
Tags are not updated to the new design.

That's it! but I was thinking about how to improve the image selection, which looked like not updated to the new visual guidelines to me. Here you a have a possible solution. Could we do this?

1 formorganizationgeneralinformation copy
3 formorganizationgeneralinformationfilled copy

box:
 - border color: #CDCE9E; 
 - border-radius: 4px; 
 - size 88x88px; 

icon inside: 
 - organization icon
 - size: 64x64px; 
 - color: #A7A9BC;

padding - margin:
 - horizontal space between input and sticker: 24px; 
 - horizontal space between sticker and small button: 16px;
 - vertical space between small buttons (when there are the 2 of them): 16px;
 - horizontal space between buttons and sheet (form box): 24px;

Thank you so much!

**Comment by stsquared99** [comment]
Thanks @susanavr 
For the Tags/Categories selectors, those are inside the liferay-asset:asset-categories-selector and liferay-asset:asset-tags-selector taglibs, which we don't have control over, so we can't change those themselves. Is there perhaps an updated component that we can use instead to match the design?

**Comment by stsquared99** [comment]
@susanavr 
Also for the logo selector, I can make the change, but it is also inside the liferay-ui:logo-selector tag, which would affect everywhere else it is used. I'm not sure how we want to handle this? We might need to check with the other product owners before we could touch anything. I've listed the usages that we don't own below:
contacts-web
layout-admin-web
oauth2-provider-web

**Comment by drewbrokke** [comment]
@stsquared99 sorry if I didn't clarify before, but we actually do own contacts-web, so a change there is fine.

**Pull request closed without merging**
