### PR TITLE
LPS-130651 Slow loading of Users & Organizations page (Cont)

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-130651](https://issues.liferay.com/browse/LPS-130651).

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:upgrade

**Comment by drewbrokke** [comment]
ci:test:search

**Comment by drewbrokke** [comment]
ci:test:users

**Comment by drewbrokke** [comment]
ci:test:accounts

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:search

**Comment by drewbrokke** [comment]
ci:test:users

**Comment by drewbrokke** [comment]
ci:test:accounts

**Comment by drewbrokke** [comment]
@patriciajeanperez can you confirm the functional test failures? I suspect a few of them are real but I'd like to know for sure.

**Comment by patriciajeanperez** [comment]
hey @drewbrokke, just checked. The test failures should be test fixes and not related to this pull.

**Comment by drewbrokke** [comment]
See https://github.com/liferay-usm/liferay-portal/pull/32

**Comment by drewbrokke** [comment]
Thank you @patriciajeanperez!

**Pull request closed without merging**
