### PR TITLE
LPS-129713 Default to "All" filter instead of "Company Users" for Users portlet

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-129713](https://issues.liferay.com/browse/LPS-129713).<br/><br/>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:s

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
The semantic-versioning-jdk8/0 issue was resolved on upstream. Will trigger the usm test suite for more testing.

**Comment by Sharryxue** [comment]
ci:test:usm

**Pull request closed without merging**
