### PR TITLE
LPS-53392 Column emailAddress length should be 254 characters long

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @achaparro @lipusz @ugurcancetin

### CODE REVIEW

**Comment by lipusz** [comment]
ci:reopen

**Comment by pei-jung** [comment]
ci:retest

**Comment by lipusz** [comment]
Hi Drew,

Do you think you can proceed with this today? Please let us know if we can assist you in any way. Thanks!

@drewbrokke

**Comment by drewbrokke** [comment]
Hey Tibor, yes I can look at it today. Thanks for the prod :)

@lipusz

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/48036.  Thanks!

**Pull request closed without merging**
