### PR TITLE
[TECHNICAL-SUPPORT] LPS-89845

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
Pull request submitted to https://github.com/shuyangzhou/liferay-portal/pull/7332.

**Pull request closed without merging**
