### PR TITLE
[TS] LPS-102333

### PR DESCRIPTION
**Pull request by crodriguezy**

### CODE REVIEW

**Comment by crodriguezy** [comment]
hi @drewbrokke , could you please have a look at this PR? I think it is not the best way to fix it but it was the only way I could think of to not introduce breaking changes. 

IMHO the best approach would have been using another identificator as key for the hashmap (an id for each type), but since this would imply changing the model and "breaking" current installations, maybe this is the solution that best fits for the branches.

Thank you.

**Comment by Sharryxue** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
ci:test:stable

**Comment by crodriguezy** [comment]
Hello! Were you able to have a look at this PR? 
Thanks! :)

**Comment by crodriguezy** [comment]
Hi, the customer keeps asking for this fix. Do you think it is safe to, by the moment, include it in a hotfix?

Thank you.

**Comment by dmoraisandrade** [comment]
Hi @crodriguezy, Drew is on paternity leave since 3/10. I will talk to the team to see if somebody els can handle this review.
regards,
Dani

**Comment by crodriguezy** [comment]
Thank you @dmoraisandrade!

**Comment by pei-jung** [comment]
Hi @crodriguezy,

After discussing with our product manager, we've decided that the organization type name should not be modifiable. The reasons being

1) existing orgs created under that type need to be updated
2) existing org types that has the updated org type as its children type need to be updated

We will work on a fix to disallow editing of the org type name. Please let me know if you have any questions. Thanks!

**Comment by crodriguezy** [comment]
Hi @pei-jung,

Will the rest of organization types' attributes (like children types) be still modifiable after your fix?

On the other hand, when will it be available?

Thank you.

**Comment by pei-jung** [comment]
Hi @crodriguezy 

Other attributes will still be modifiable; only the name field will be non-modifiable. I'll work on the fix today and try to get it in either today or tomorrow.

**Comment by crodriguezy** [comment]
Thank you @pei-jung

**Comment by pei-jung** [comment]
Please see https://github.com/pei-jung/liferay-portal/pull/813 for the fix.

**Comment by pei-jung** [comment]
ci:close

**Pull request closed without merging**
