### PR TITLE
LPS-180907 Add publish workspace action

### PR DESCRIPTION
**Pull request by Seiphon**
Hi @drewbrokke, I have test the action workflow on my repo, and it can publish the jar to xannadu successfully.
Here is the link https://github.com/Seiphon/liferay-portal/actions/runs/4675190809/jobs/8280057448
https://repository.liferay.com/nexus/content/repositories/xanadu/com/liferay/workspace/com.liferay.sample.workspace/

### CODE REVIEW

**Comment by Seiphon** [comment]
ci:test:sf

**Review by drewbrokke — CHANGES_REQUESTED** [review]
@Seiphon overall this looks good, thank you. Only two suggestions from me:
1. Rename the file to `publish-sample-workspace.yaml`
2. Squash the commits into a single commit.
Thanks!

**Comment by Seiphon** [comment]
OK, will do it and resend the pr

**Comment by Seiphon** [comment]
Hi @drewbrokke, resent the pr here: https://github.com/drewbrokke/liferay-portal/pull/1417

**Pull request closed without merging**
