### PR TITLE
LPS-104594 Allow search for users by email domains

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-104594](https://issues.liferay.com/browse/LPS-104594).

### CODE REVIEW

**Comment by drewbrokke** [comment]
@pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez @joshchong @lipusz

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:search

**Comment by drewbrokke** [comment]
ci:test:solr

**Comment by drewbrokke** [comment]
ci:test:search-solr

**Comment by drewbrokke** [comment]
ci:test:search-es7

**Comment by joshchong** [comment]
Hey @drewbrokke! Looks like the only relevant failure here is the ElasticsearchIndexInformationTest.testGetFieldMappings test. Can you take a look? Note that this test is within the Elasticsearch 7 module and is different from the one you fixed earlier. You can just rerun ci:test:relevant after pushing up the fix. All other failures are unrelated. Also FYI we aborted the ci:test:solr run since that test run is redundant.

**Comment by drewbrokke** [comment]
Thanks @joshchong! I failed to recognize that they were two separate test failures! 😂

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by joshchong** [comment]
@drewbrokke test results LGTM!

**Comment by drewbrokke** [comment]
PR sent to https://github.com/brianchandotcom/liferay-portal/pull/81212

**Pull request closed without merging**
