### PR TITLE
LPS-107073 Headless API for associating Roles to Users

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-107073](https://issues.liferay.com/browse/LPS-107073).<br><br>Hey @brianchandotcom, this pull still checks the role type, but does not do checks on the userId or groupId. The test cases will come after this pull is merged.<br><br>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
@pyoo47 can we re-run this one?

**Comment by pyoo47** [comment]
Sure, try again.. I am guessing the failure was due to the network outage

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
