### PR TITLE
LPS-72754

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:reopen

**Comment by daviddotzhang** [comment]
@drewbrokke could you review this one ?
It's customer related, so we'd appreciate if you could give this one priority.

**Comment by drewbrokke** [comment]
@daviddotzhang thanks for the bump.  I'll review it today.

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
Pull request sent to https://github.com/brianchandotcom/liferay-portal/pull/49362.  Thanks!

**Pull request closed without merging**
