### PR TITLE
LPS-85537 Add patch info to server administration page

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-85537

Hi @drewbrokke 

I am sending this pr to you because you have reviewed last server administration page changes.

I am adding patch info to that page, now we are only displaying Liferay version. More info see LPS description.

Thank you,
Jorge

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test

**Comment by jorgediaz-lr** [comment]
ci:test

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
PR sent to https://github.com/brianchandotcom/liferay-portal/pull/64629 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
