### PR TITLE
LPS-121998 Add new service Impl methods to account for the new Country fields

### PR DESCRIPTION
**Pull request by alee8888**
@drewbrokke @pei-jung

### CODE REVIEW

**Comment by alee8888** [comment]
ci:test:sf

**Comment by alee8888** [comment]
ci:test:relevant

**Comment by alee8888** [comment]
ci:test:sf

**Comment by alee8888** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
Hello @alee8888 ，
The failed functional tests are related to the commits, based on any of the [Console Output](https://testray.liferay.com/reports/production/logs/test-1-17/1606260608182/test-portal-acceptance-pullrequest(master)/6917/functional-upgrade-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz). Not sure the addition commits had already contains the fix, would you please double check the issue?
There is a warning like following in upgrade process
```
2020-11-25 00:40:44.091 WARN  [main][BaseDB:107] Duplicate entry '0-408' for key 'IX_4B78E87A': create unique index IX_4B78E87A on Country (companyId, number_);
```
and tests failed due to the same LIFERAY_ERROR:

```
LIFERAY_ERROR: Duplicate entry '0-408' for key 'IX_4B78E87A': create unique index IX_4B78E87A on Country (companyId, number_);
```

**Comment by drewbrokke** [comment]
ci:close

**Pull request closed without merging**
