### PR TITLE
LPS-117666 my-user-account service does not return inherited regular roles

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-117666](https://issues.liferay.com/browse/LPS-117666)

Hi Drew,

This is the continuation of https://github.com/drewbrokke/liferay-portal/pull/1131.

I don't see the previous test failures anymore. Regarding [your suggestion on abstracting the common logic](https://github.com/drewbrokke/liferay-portal/pull/1131#issuecomment-663757289), that doesn't seem to be an easy task because the methods are not simply copied, but adjusted to be able to use in UserAccountResourceImpl.

Please let me know if you have any questions or concerns.

Regards,
Istvan

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@istvansajtos thanks for this. I'm having trouble with the fix - it seems like the inherited UserGroup role still does not show up in the response when I follow the steps to reproduce on the ticket. Are those still accurate?

Also, I think we need to add a test case for this change to define the requirements for this endpoint.

Can you please add a test case and double-check the steps to reproduce on the ticket? Please let me know if you have any questions. Thanks!

Closing for now

cc @ChrisKian

**Comment by drewbrokke** [comment]
HI @istvansajtos! Any updates on this?

**Comment by istvansajtos** [comment]
Hi @drewbrokke ,

I have just returned from paternity leave. Soon I will return to this.

**Comment by drewbrokke** [comment]
@istvansajtos welcome back and congratulations! Thanks for the update :)

**Comment by istvansajtos** [comment]
Thank you, @drewbrokke ! :)

**Pull request closed without merging**
