### PR TITLE
LPS-109937 Add API to search for users of an account role

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
Looks good. PR sent to https://github.com/brianchandotcom/liferay-portal/pull/85983

**Comment by drewbrokke** [comment]
I made one small change to a parameter name in the test. See https://github.com/brianchandotcom/liferay-portal/pull/85983/commits/4fe9e5467559e8c1d5498f13fbbf888c9ad83381

**Comment by pei-jung** [comment]
👍, thanks!

**Pull request closed without merging**
