### PR TITLE
LPS-84879

### PR DESCRIPTION
**Pull request by crodriguezy**

### CODE REVIEW

**Comment by crodriguezy** [comment]
ci:test

**Comment by crodriguezy** [comment]
hi @drewbrokke , did you have the time to review this? Please tell me if I should send it to somone else.

Thanks!

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by crodriguezy** [comment]
Hi @drewbrokke , thanks for reviewing it. 

The expected result is the user to be created correctly without any exception being thrown 8you can see the description in https://issues.liferay.com/browse/LPS-84979).

Now we are [not storing the updated object](https://github.com/liferay/liferay-portal/blob/cda43aaeec6659ecadeb2dbde4bde4457b862d7a/portal-impl/src/com/liferay/portal/service/impl/UserLocalServiceImpl.java#L5250) from the persistence layer, so we rely on the the one passed as argument, which is not always the same object.

By not storing and using the updated object, we take the risk of being working with an outdated object and so that of receiving the _StaleObjectException_ when trying to modify it afterwards (one of our customers is currently getting it). 

As per [Shuyang's comment in this related PR](https://github.com/shuyangzhou/liferay-portal/pull/6449#issuecomment-405388777), throwing away the persistance layer returned object is considered as a bug and should be fixed.

I hope this is clearer now, please do not hesitate in asking any other doubt you have :)

**Comment by drewbrokke** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/62949. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
@crodriguezy thanks for the explanation!

**Pull request closed without merging**
