### PR TITLE
LPS-180907 Add publish workspace action

### PR DESCRIPTION
**Pull request by Seiphon**
Hi @drewbrokke , this pr is about creating github action to publish workspaces, please help to review it. Thanks

And another question is that do we need to set github secrets of username and password for the remote repository access when pubish jar to cdn? Or maybe CI team will do it?

### CODE REVIEW

**Comment by Seiphon** [comment]
ci:test:sf

**Comment by Seiphon** [comment]
ci:test:sf

**Comment by Seiphon** [comment]
ci:test:sf

**Review by drewbrokke — APPROVED** [review]

**Review by drewbrokke — CHANGES_REQUESTED** [review]
@Seiphon I think we need to make one adjustment to this workflow. This ant task requires credentials in order to publish, but I do not see that the credentials are passed in anywhere. I believe we would accomplish this using [secrets](https://docs.github.com/en/actions/learn-github-actions/contexts#secrets-context).

**Comment by Seiphon** [comment]
> @Seiphon I think we need to make one adjustment to this workflow. This ant task requires credentials in order to publish, but I do not see that the credentials are passed in anywhere. I believe we would accomplish this using [secrets](https://docs.github.com/en/actions/learn-github-actions/contexts#secrets-context).

OK, I will try to add the credentials and test it

**Pull request closed without merging**
