### PR TITLE
[TECHNICAL-SUPPORT] LPS-74733

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
@drewbrokke Any update on this pull?

**Comment by drewbrokke** [comment]
Hey @jonathanmccann, sorry about the delay.  I'll be reviewing today.

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
Pull request sent to https://github.com/brianchandotcom/liferay-portal/pull/51628.  Thanks@

**Pull request closed without merging**
