### PR TITLE
LPS-64349 Better use Validator

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by csierra** [comment]
hey @drewbrokke there is a SF problem... sending an update

**Comment by csierra** [comment]
ci:retest

**Comment by drewbrokke** [comment]
Pull request sent to JorgeFerrer#699.  Thanks <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
