### PR TITLE
LPS-130750 Add relevance sort option in search.

### PR DESCRIPTION
**Pull request by SamZiemer**
Notes from @brianikim
> https://issues.liferay.com/browse/LPS-130750
> 
> Straightforward issue. QoL improvement to search for Users Admin Portlet so users can sort by Relevance, making their searches faster in locating what they want.
> 
> Sincerely,
> Brian Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by Sharryxue** [comment]
The failed search, index and [reindex integration](https://testray.liferay.com/home/-/testray/case_results?testrayTeamId=1310700916&testrayBuildId=1527422614&testrayRunId=1527422677) tests might related to the changes, re-trigger a relevant test for confirming.

**Comment by Sharryxue** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
Hello @drewbrokke ,

New test result looks good. Let me know if you see any issues with the implementation.

**Comment by drewbrokke** [comment]
LGTM 👍

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
@patriciajeanperez can you double-check to see if any functional tests need to be updated to account for this? Thanks!

**Pull request closed without merging**
