### PR TITLE
LPS-55591 Extract UsersAdmin and MyAccount portlets to OSGi

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:retest

**Comment by drewbrokke** [comment]
ci:retest

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
Hey @pei-jung, can you add an upgrade class as well?  See the class for [UserGroupsAdminWebUpgrade](https://github.com/liferay/liferay-portal/blob/master/modules/apps/user-groups-admin/user-groups-admin-web/src/com/liferay/user/groups/admin/web/upgrade/UserGroupsAdminWebUpgrade.java) (you can pretty much just copy it).  Just let me know when you push the commit.

**Comment by pei-jung** [comment]
Hi Drew,

I added the portlet key class for users admin and updated the branch. Let me know if there's any issues. Thanks!

**Comment by pei-jung** [comment]
ci:retest

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
Some things to take care of:
- [x] Create a PortletProvider to replace uses of PortletKeys.USERS_ADMIN
- [ ] Only remove language keys from core that are exclusive to users_admin
- [ ] Remove other uses of `<footer-portlet-javascript>/html/portlet/users_admin/js/main.js</footer-portlet-javascript>` from `liferay-portlet.xml`.  It looks like the functions in the script are not used in any other portlets.

**Comment by drewbrokke** [comment]
I think once we address the items above we can send it on. Nice job on this pull @pei-jung!  So much work....

**Comment by drewbrokke** [comment]
ci:retest

**Comment by pei-jung** [comment]
ci:retest

**Comment by pei-jung** [comment]
language keys update: see last two commits
remove users_admin/js/main.js: https://github.com/pei-jung/liferay-portal/commit/22248d5c0d4bbcfe451afde199117dd08e9813ba
copy css instead of moving it: https://github.com/pei-jung/liferay-portal/commit/f91600245c0e9af8562db2354f18a2a55d0e9501
import UsersAdminPortletKeys in init.jsp: https://github.com/pei-jung/liferay-portal/commit/290e1a230beaec3dfb0fb2b8e9a25d8fec7f773c
remove users-spring.xml: https://github.com/pei-jung/liferay-portal/commit/d209a356fac93e6d4d3f04c85ec76a19b2fb0919

Thanks!

**Comment by pei-jung** [comment]
ci:retest

**Comment by pei-jung** [comment]
ci:retest

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
ci:retest

**Comment by pei-jung** [comment]
ci:retest

**Comment by pei-jung** [comment]
ci:retest

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
Sent to brian: brianchandotcom:29051 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
