### PR TITLE
LPS-59844

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @drewbrokke,

Attached is an update for http://issues.liferay.com/browse/LPS-59844.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
/cc @mwilliams2014

This is the deprecation of the <liferay-ui:progress /> taglib.

**Comment by mwilliams2014** [comment]
Thanks @jonmak08

**Comment by jonmak08** [comment]
Hey @mwilliams2014,

Let us know if there is anything else we should be adding to the deprecation/removal of these taglibs.

Please let me know if you have any questions.  Thanks!

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
Pull request sent to jonmak08#1359 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
