### PR TITLE
LPS-75989 Merge my-account with users-admin-web

### PR DESCRIPTION
**Pull request by Preston-Crary**
CC @shuyangzhou

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test

**Comment by drewbrokke** [comment]
ci:reopen

**Comment by drewbrokke** [comment]
@brianchandotcom @JorgeFerrer we would like to remove the {code}my-account-web{code} module completely, which means removing the subrepo.  Is this ok?

**Comment by JorgeFerrer** [comment]
I don't have an issue with removing the module and sub-repo if it's not needed any more.

What I would like to know is why are we doing this merge. I've checked the LPS ticket and there is no explanation there. @Preston-Crary I'm sure there are good reasons, but I would appreciate if you could document them in the ticket for future reference.

**Comment by Preston-Crary** [comment]
@JorgeFerrer, okay I've updated the ticket.  Here's a copy of what I put there:

This is a preliminary step towards are lpkg release refactoring. By reducing our API and prohibiting non-API modules from exporting packages we can simplify the release process and avoid causing versioning issues.

Because my-account consumes most of the packages from users-admin and all the JSPs, reducing the exports is not easily possible without either duplicating most of the code or merging the two modules. There is already quite a bit of duplication as my-account copies all the JSPs from users-admin in the bnd and this creates hidden dependencies on most of the packages in users-admin.

Since this duplication is not easily apparent and can lead to more problems later merging the modules seems to be the best option.

**Comment by JorgeFerrer** [comment]
Sounds very reasonable. Thanks for documenting the reason in the ticket.

**Comment by Preston-Crary** [comment]
ci:test

**Comment by drewbrokke** [comment]
@ithildir is there something we need to do about the `copyCompiledJSP` error above?  We removed the only usage of it (from `my-account-web`).

**Comment by Ithildir** [comment]
@drewbrokke: remove https://github.com/liferay/liferay-portal/blob/master/build.xml#L418-L423.

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by drewbrokke** [comment]
@Preston-Crary I removed the offending lines from `build.xml` and re-sent to myself for testing: https://github.com/drewbrokke/liferay-portal/pull/427.  Thanks!

**Pull request closed without merging**
