### PR TITLE
LPS-120300 Only grant the View permission to the User role upon creation of the system roles

### PR DESCRIPTION
**Pull request by hudakl**
Hi,

Could you please review my solution proposal for LPS-120300?

Thank you,
Laci

### CODE REVIEW

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
Hey @hudakl, the change looks good to me. Will you please add an integration test case as well?

You should be able to just adjust the permissions on the Power User role, then run `RoleLocalService.checkSystemRoles(companyId)`, then assert on the Power User role's permissions. Thoughts?

**Comment by hudakl** [comment]
Hi Drew,

Thanks for your feedback. I'll get to working on the integration test. I'll let you know once I'm finished with it.

**Comment by drewbrokke** [comment]
Thanks @hudakl !

**Comment by drewbrokke** [comment]
@hudakl any updates on this?

**Comment by hudakl** [comment]
Hi Drew,

I haven't had time for it yet. Today I could check it and I have an idea for it. The implementation in progress.
Hopefully, I can finish it tomorrow.

Thanks,
Laci
@drewbrokke

**Comment by drewbrokke** [comment]
Closing in favor of https://github.com/drewbrokke/liferay-portal/pull/1179

**Pull request closed without merging**
