### PR TITLE
[TS] LPS-114640

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-114640

From @holatuwol:

> The issue is that `UnicodeFormatter` is already JS-safe, so when we decide to wrap it with another `HtmlUtil.escapeJS`, that causes it to change every `\u` into `\\u`, which is wrong.

CC @tototrinh

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@ChrisKian can we confirm that this does not cause a regression for this ticket? https://issues.liferay.com/browse/LPS-102425. If so then this works for me.

**Comment by ChrisKian** [comment]
Hey @drewbrokke,
There shouldn't be a regression.  The UnicodeFormatter class already escapes strings in unicode format (EX: \u0075).  Applying the HTMLUtil.EscapeJS method as well only escapes the backslashes, which doesn't do anything useful (EX: \x5cu0075).

Let me know if you have other questions, thanks!

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
