### PR TITLE
LPS-124638

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-124638

From @holatuwol: 

> Issue occurs because the code block in `getWhere` only checks for `Long` and `Long[]`. Chose this solution because at around line 1248, there is a similar code block that does the array conversion.

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
LGTM 👍

**Comment by drewbrokke** [comment]
@ChrisKian @holatuwol is there a corresponding integration test case?

**Comment by holatuwol** [comment]
Pull request with integration test:

**Comment by holatuwol** [comment]
ci:close

**Pull request closed without merging**
