### PR TITLE
LPS-125700 Bridge CommerceAccountGroup service to AccountGroup service

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-125700](https://issues.liferay.com/browse/LPS-125700).

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:upgrade

**Comment by drewbrokke** [comment]
ci:test:accounts

**Comment by drewbrokke** [comment]
ci:test:commerce

**Comment by Sharryxue** [comment]
Probably related failure:
- When searching for the deleted account group, got error like following, refer [POSHI report](https://testray.liferay.com/zh/home/-/testray/case_results/1522026473), [console](https://testray.liferay.com/reports/production/logs/2021-03/test-1-14/test-portal-acceptance-pullrequest(master)/7984/functional-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz)
` [1617067300.645][SEVERE]: Unable to retrieve document state unexpected alert open`
- [com.liferay.portal.upgrade.v7_0_0.test.UpgradeResourcePermissionTest](https://testray.liferay.com/zh/home/-/testray/case_results/1522064107) failed on DB2, test may failed for a related issue, would you @drewbrokke help with double checking, thanks.
```
     [exec] com.liferay.portal.upgrade.v7_0_0.test.UpgradeResourcePermissionTest > testUpgrade FAILED
     [exec]     java.lang.AssertionError: DB2 SQL Error: SQLCODE=-204, SQLSTATE=42704, SQLERRMC=ROOT.RESOURCEPERMISSION, DRIVER=4.24.92: create unique index IX_8D83D0CE on ResourcePermission (companyId, name, scope, primKey, roleId)
     [exec] 
     [exec]     DB2 SQL Error: SQLCODE=-204, SQLSTATE=42704, SQLERRMC=ROOT.RESOURCEPERMISSION, DRIVER=4.24.92: create index IX_49AEC6F3 on ResourcePermission (companyId, name, scope, primKeyId, roleId, viewActionId)
     [exec] 
     [exec]     DB2 SQL Error: SQLCODE=-204, SQLSTATE=42704, SQLERRMC=ROOT.RESOURCEPERMISSION, DRIVER=4.24.92: create index IX_26284944 on ResourcePermission (companyId, primKey)
     [exec] 
     [exec]     DB2 SQL Error: SQLCODE=-204, SQLSTATE=42704, SQLERRMC=ROOT.RESOURCEPERMISSION, DRIVER=4.24.92: create index IX_F6BAE86A on ResourcePermission (companyId, scope, primKey)
     [exec] 
     [exec]     DB2 SQL Error: SQLCODE=-204, SQLSTATE=42704, SQLERRMC=ROOT.RESOURCEPERMISSION, DRIVER=4.24.92: create index IX_D5F1E2A2 on ResourcePermission (name)
     [exec] 
     [exec]     DB2 SQL Error: SQLCODE=-204, SQLSTATE=42704, SQLERRMC=ROOT.RESOURCEPERMISSION, DRIVER=4.24.92: create index IX_A37A0588 on ResourcePermission (roleId)
     [exec] 
     [exec]     DB2 SQL Error: SQLCODE=-204, SQLSTATE=42704, SQLERRMC=ROOT.RESOURCEPERMISSION, DRIVER=4.24.92: create index IX_F4555981 on ResourcePermission (scope)
     [exec]     	at org.junit.Assert.fail(Assert.java:89)
```

Issue probably not related
- The [semantic-versioning-jdk8](https://testray.liferay.com/zh/home/-/testray/case_results/1522024714) baseline issue should not related
- No related issue found in ci:test:commerce suite
- No related issue found in ci:test:relevant suite

**Comment by drewbrokke** [comment]
Closing in favor of https://github.com/drewbrokke/liferay-portal/pull/1347

**Pull request closed without merging**
