### PR TITLE
LPS-198875 upgrade plexus-utils version 3.0.24

### PR DESCRIPTION
**Pull request by simonjhy**
@drewbrokke it has been passed all gradle-plugins test and project template test(except the service builder version test, it has been fix by this commit https://github.com/drewbrokke/liferay-portal/pull/1522/commits/34c40387a8a09c65cba3c9423d7bbadeca26324b). Here is test result https://github.com/simonjhy/liferay-portal/pull/178.

### CODE REVIEW

**Review by drewbrokke — APPROVED** [review]
LGTM 👍 Thanks @simonjhy!

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
ci:forward:force

**Comment by drewbrokke** [comment]
@simonjhy looks like a merge conflict. Can you please rebase on master and send a new PR? Thanks!

**Comment by simonjhy** [comment]
> @simonjhy looks like a merge conflict. Can you please rebase on master and send a new PR? Thanks!

OK

**Pull request closed without merging**
