### PR TITLE
LPS-71092 Members in a parent site with Site Administrator Role do not have the same rights in the underlying child site

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @jorgeferrer @ealonso @arthurchan35 @Preston-Crary

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:retest

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pei-jung** [comment]
ci:stop

**Comment by pei-jung** [comment]
ci:retest
updated test and pushed to branch

**Comment by pei-jung** [comment]
ci:retest

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
