### PR TITLE
LPS-124466 Match front-end email validation to back-end email validat…

### PR DESCRIPTION
**Pull request by SamZiemer**
Notes from @brianikim:

> https://issues.liferay.com/browse/LPS-124466
> 
> Straight-forward fix. Front-end email validation should match back-end email validation for consistency.
> 
> Back-end email validation is done using: 
> https://github.com/liferay/liferay-portal/blob/9f006e02a098939d1dbc2cad64f9ca7a2b9f3520/portal-kernel/src/com/liferay/portal/kernel/util/Validator.java#L1226

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@SamZiemer this looks fine to me, though I have not thoroughly vetted the regex pattern. Is it a recreation of the pattern found in the `Validator` backend class? 

Also, go ahead and re-send through the frontend team at @liferay-frontend. This changes their components and could potentially affect other areas of portal, so it should ultimately go through them. They may also want tests for the regex pattern. Thanks! 

Closing this pull in favor of a pull to the liferay-frontend user.

**Comment by brianikim** [comment]
Hey @drewbrokke , the regex pattern is a recreation of the pattern found in the Validator backend class. @SamZiemer , Let me know if you will be sending it to @liferay-frontend or if you wanted me to send.

**Comment by SamZiemer** [comment]
Thanks @drewbrokke, forwarded here: https://github.com/liferay-frontend/liferay-portal/pull/688

**Pull request closed without merging**
