### PR TITLE
[TS] LPS-111417

### PR DESCRIPTION
**Pull request by ChrisKian**
From @kevhlee:

> Ticket: https://issues.liferay.com/browse/LPS-111417
> 
> The issue was that the redirect URL required additional parameters, causing the issue described in the ticket. To fix this issue, I created a new method that constructs the correct redirect URL and use it to replace the iterator URL of the search container for the account roles page. I used the following as reference for my solution:
> 
> * <https://github.com/brianchandotcom/liferay-portal/pull/83327/commits>
> * <https://github.com/kevhlee/liferay-portal/blob/LPS-111417/modules/apps/account/account-admin-web/src/main/resources/META-INF/resources/account_entries_admin/edit_account_role.jsp#L27-L29>
> 
> With regards,
> Kevin

CC @wanderlast

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
PR sent to https://github.com/drewbrokke/liferay-portal/pull/1021

**Pull request closed without merging**
