### PR TITLE
LPS-112667

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/88187

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Everything works fine. I'll forward to Brian with no changes.

**Comment by adolfopa** [comment]
See https://github.com/adolfopa/liferay-portal/pull/1419

**Comment by drewbrokke** [comment]
Closing in favor of https://github.com/brianchandotcom/liferay-portal/pull/88211

**Pull request closed without merging**
